- resources/web/guide/6/6.css
- resources/web/homepage/css/dark.css
- resources/web/homepage/css/home.css
- src/slic3r/GUI/BambuPlayer/BambuPlayer.h
fix some typo (## ,)  and color
> fix typo and color

- src/BambuStudio.cpp
- src/libslic3r/Preset.cpp
- src/libslic3r/Print.cpp
- src/libslic3r/PrintConfig.cpp
- src/libslic3r/PrintConfig.hpp
- src/slic3r/GUI/BackgroundSlicingProcess.cpp
- src/slic3r/GUI/Tab.cpp
Automatically call external post-process scripts before exporting G-Code
> Add Post-processing

- resources/profiles/Ratrig/filament/RatRig Generic ABS.json
- resources/profiles/Ratrig/filament/RatRig Generic ASA.json
- resources/profiles/Ratrig/filament/RatRig Generic PA-CF.json
- resources/profiles/Ratrig/filament/RatRig Generic PA.json
- resources/profiles/Ratrig/filament/RatRig Generic PC.json
- resources/profiles/Ratrig/filament/RatRig Generic PETG.json
- resources/profiles/Ratrig/filament/RatRig Generic PLA-CF.json
- resources/profiles/Ratrig/filament/RatRig Generic PLA.json
- resources/profiles/Ratrig/filament/RatRig Generic PVA.json
- resources/profiles/Ratrig/filament/RatRig Generic TPU.json
- resources/profiles/Ratrig/machine/RatRig V-Cast 0.4 nozzle.json
- resources/profiles/Ratrig/machine/RatRig V-Cast 0.6 nozzle.json
- resources/profiles/Ratrig/machine/RatRig V-Core 3 300 0.4 nozzle.json
- resources/profiles/Ratrig/machine/RatRig V-Core 3 400 0.4 nozzle.json
- resources/profiles/Ratrig/machine/RatRig V-Core 3 500 0.4 nozzle.json
- resources/profiles/Ratrig/machine/RatRig V-Minion 0.4 nozzle.json
- resources/profiles/Ratrig/process/0.08mm Extra Fine @RatRig.json
- resources/profiles/Ratrig/process/0.12mm Fine @RatRig.json
- resources/profiles/Ratrig/process/0.15mm Optimal @RatRig.json
- resources/profiles/Ratrig/process/0.20mm Standard @RatRig.json
- resources/profiles/Ratrig/process/0.24mm Draft @RatRig.json
- resources/profiles/Ratrig/process/0.28mm Extra Draft @RatRig.json
- resources/profiles/Ratrig/process/fdm_process_ratrig_common.json
Fix to RatRig profiles, especially V-Cast
> Fix to RatRig profiles

- src/libslic3r/Extruder.cpp
- src/libslic3r/Extruder.hpp
- src/libslic3r/GCode.cpp
- src/libslic3r/GCode/CoolingBuffer.cpp
- src/libslic3r/GCode/SpiralVase.cpp
- src/libslic3r/GCodeReader.cpp
- src/libslic3r/GCodeWriter.cpp
- src/libslic3r/Preset.cpp
- src/libslic3r/Print.cpp
- src/libslic3r/PrintConfig.cpp
- src/libslic3r/PrintConfig.hpp
- src/libslic3r/libslic3r.h
- src/slic3r/GUI/Tab.cpp
Add the option to use non-relative extrusion in printer config screen. Some extruders do not play well with relative extrusion...
> Enable absolute/relative extrusion option on non BBL printers

- deps/wxWidgets/wxWidgets.cmake
fix for mac build 
pls look at linux build process
bug #226
> fix_mac build

- src/libslic3r/GCode.cpp
- src/libslic3r/Print.cpp
- src/libslic3r/Print.hpp
- src/libslic3r/calib.cpp
- src/libslic3r/calib.hpp
- src/slic3r/CMakeLists.txt
- src/slic3r/GUI/AMSMaterialsSetting.cpp
- src/slic3r/GUI/AmsMappingPopup.cpp
- src/slic3r/GUI/ExtrusionCalibration.cpp
- src/slic3r/GUI/MainFrame.cpp
- src/slic3r/GUI/MainFrame.hpp
- src/slic3r/GUI/Plater.cpp
- src/slic3r/GUI/Plater.hpp
- src/slic3r/GUI/SFCalibrationDlg.cpp
- src/slic3r/GUI/SFCalibrationDlg.hpp
> PA Calib dialog

- src/slic3r/GUI/ConfigManipulation.cpp
- src/slic3r/GUI/Tab.cpp
new fix vase mode like bambulab
> bambulab fix 69b884e

- src/libslic3r/Fill/Fill.cpp
- src/libslic3r/Flow.hpp
- src/libslic3r/Layer.hpp
- src/libslic3r/LayerRegion.cpp
- src/libslic3r/Preset.cpp
- src/libslic3r/PrintConfig.cpp
- src/libslic3r/PrintConfig.hpp
- src/libslic3r/PrintObject.cpp
- src/libslic3r/libslic3r.h
- src/slic3r/GUI/GUI_Factories.cpp
- src/slic3r/GUI/Tab.cpp
Signed-off-by: SoftFever <softfeverever@gmail.com>
> New feature: bridge density

- src/libslic3r/GCode.cpp
> fix z hop bug

- resources/profiles/Custom/process/0.28mm Extra Draft @MyKlipper.json
This PR fixes a mistake in "0.28mm Extra Draft @MyKlipper.json"
> Fix mistake in "0.28mm Extra Draft @MyKlipper.json"

- README.md
Easier solution to allow opening the app
> Easier solution to allow opening the app on OSX described in README.md

- src/libslic3r/AppConfig.cpp
- src/libslic3r/AppConfig.hpp
- src/libslic3r/PresetBundle.cpp
- src/libslic3r/PresetBundle.hpp
- src/slic3r/GUI/Plater.cpp
- src/slic3r/GUI/Tab.cpp
Also change max filament from 16 to 64
> QoL: remember each printer's filament/bed/process settings

- bbl/i18n/es/OrcaSlicer_es.po
> Some Spanish string fixes

- CMakeLists.txt
- src/CMakeLists.txt
- src/libslic3r/CMakeLists.txt
- src/slic3r/CMakeLists.txt
https://github.com/prusa3d/PrusaSlicer/commit/0ffcfd8393457fd035576436752267c9a1e6bbcc
> Use namespaces to link against libcereal >= 1.3.1

- localization/i18n/cs/OrcaSlicer_cs.po
I would like to request the addition of the word skirt to the *.pot file for translation, see picture. And at the same time, I'm sending the PR of Czech with an added translation.
> Updating the translation into Czech

- src/slic3r/GUI/GUI_App.cpp
修复:拓竹用户不同步设备列表
优化:检查更新时概率卡住GUI
> Check the new version asynchronously  修复拓竹用户不同步设备列表

- src/slic3r/GUI/DeviceManager.cpp
Thank you for telling me how to do @SoftFever
> P1S LAN mode not working #1882

- src/slic3r/GUI/GUI_App.cpp
> Fixed crashes caused by failed version checks 修复:检查更新概率崩溃

- src/libslic3r/AppConfig.cpp
- src/libslic3r/AppConfig.hpp
- src/slic3r/GUI/Mouse3DController.cpp
- src/slic3r/GUI/Mouse3DController.hpp
Some people prefer their axes inverted when using a spacemouse. With this, you can invert any set of axes you want (if you have a spacemouse).
> Add option in the CTRL-M dialog to invert axes

- localization/i18n/cs/OrcaSlicer_cs.po
I am sending an updated Czech translation.
I just noticed that BambuStudio was entered for some phrases, so I'm wondering if it will change to OrcaSlicer.
Thank you and best regards, Mošner
> update czech translate

- localization/i18n/zh_TW/OrcaSlicer_zh_TW.po
> Update Tranditional Chinese locale

- src/libslic3r/Config.cpp
This should fix #1397 #1435 #1946 #1990
> Fix double quotes escape (#1397 #1435 #1946 #1990)

- BuildLinux.sh
- README.md
- Small changes for Ubuntu 23.04
- Moved the creation of the main $ROOT/build directory so it doesn't end up owned by root, causing an error later.
- Moved the "usage" message to a function and refactored some code
> Changes for Ubuntu 23.04. General housekeeping.

- src/slic3r/Utils/CalibUtils.cpp
This fixes the #2019 crash cause by type mismatch.
> Fix calibrtion crash (#2019)

- localization/i18n/zh_TW/OrcaSlicer_zh_TW.po
Updated some strings to match Taiwanese terms
> Updated TW translation

- src/libslic3r/PrintObject.cpp
- src/libslic3r/SurfaceCollection.cpp
- src/libslic3r/SurfaceCollection.hpp
Cherrypicked from https://github.com/prusa3d/PrusaSlicer/commit/14e0cd0e960b5f384511541bc1ed8089eb4c2436
> Parallelized PrintObject::bridge_over_infill()

- src/BaseException.cpp
- src/libslic3r/Config.hpp
- src/libslic3r/GCode/PostProcessor.cpp
- src/libslic3r/MeshSplitImpl.hpp
- src/libslic3r/Print.cpp
- src/mcut/CMakeLists.txt
- src/slic3r/GUI/IMSlider.cpp
- src/slic3r/GUI/WebGuideDialog.cpp
- src/slic3r/GUI/calib_dlg.cpp
- src/slic3r/GUI/wxMediaCtrl2.cpp
- src/slic3r/Utils/Bonjour.cpp
- src/slic3r/Utils/TCPConsole.cpp
Fixed a lot of build warnings on Windows (some of which were actual bugs, missing return statements, etc).
> Fix build warnings on windows, fix various bugs/logic errors/missing returns/etc, update boost::bind

- src/libslic3r/GCode.cpp
- src/libslic3r/Preset.cpp
- src/libslic3r/PrintConfig.cpp
- src/libslic3r/PrintConfig.hpp
- src/slic3r/GUI/Tab.cpp
> Add: option to setup a cost per hour per printer #571

- src/libslic3r/Fill/Fill.cpp
- src/libslic3r/Preset.cpp
- src/libslic3r/PrintConfig.cpp
- src/libslic3r/PrintConfig.hpp
- src/slic3r/GUI/ConfigManipulation.cpp
- src/slic3r/GUI/Tab.cpp
adds a field to the ironing section that allows you to change the angle ironing is done
> add ironing angle

- src/libslic3r/Fill/Fill.cpp
> Fix crash when use adaptive cubic sparse infill (#2315)

- src/slic3r/GUI/PartPlate.cpp
- src/slic3r/GUI/PartPlate.hpp
> Show tooltips for plate buttons (#2176)

- resources/web/guide/24/24.js
- resources/web/guide/24/index.html
> 选择打印机增加关键字搜索

- src/libslic3r/PrintObjectSlice.cpp
this also fixes #2344 and fixes #2350
> Remove `fix_slicing_errors` because it makes no sense

- localization/i18n/zh_cn/OrcaSlicer_zh_CN.po
Because I found that someone else had submitted another version a few minutes before I submitted it, I closed my previous submission and merged it with it.
1.Added some translation related to tools change.
2.Added some simple sentence translations.
3.Repeatedly proofread the translation
And checked for errors
> update zh_CN local

- src/slic3r/GUI/GLCanvas3D.cpp
- src/slic3r/GUI/GLCanvas3D.hpp
> More camera tweaks

- resources/profiles/Flashforge/machine/Flashforge Adventurer 5M 0.4 Nozzle.json
- resources/profiles/Flashforge/machine/Flashforge Adventurer 5M 0.6 Nozzle.json
- resources/profiles/Flashforge/machine/Flashforge Adventurer 5M Pro 0.4 Nozzle.json
- resources/profiles/Flashforge/machine/Flashforge Adventurer 5M Pro 0.6 Nozzle.json
- resources/profiles/Flashforge/machine/fdm_flashforge_common.json
- resources/profiles/Flashforge/machine/fdm_klipper_common.json
Added machine pause code for Flashforge printers to support pause action in firmware 2.3.6-2.1.9-20231101
> Adjusted Flashforge machine profiles

- localization/i18n/de/OrcaSlicer_de.po
> Fix: Height range Modifier translation in German #2613

- src/slic3r/GUI/Gizmos/GLGizmoSeam.hpp
> Fix min brush size when using scroll wheel (#2534)

- resources/profiles/Creality/machine/Creality K1 Max.json
- resources/profiles/Creality/machine/Creality K1.json
This should fix #2609
Fix #2345
> Fix creality k1/max default materials (#2609)

- src/slic3r/GUI/GCodeViewer.cpp
This fixes the issue mentioned here https://github.com/SoftFever/OrcaSlicer/pull/2799#issuecomment-1819800701
> Another fix to the preview shell

- CMakeLists.txt
This is a small cmake fix for a build issue that I ran into on Fedora and Ubuntu.
> Fix cmake error

- src/libslic3r/utils.cpp
This should reduce app startup time by a few seconds on Windows if you have lots of printer profiles added.
> Use windows API to copy files

- src/libslic3r/Fill/Fill.cpp
- src/libslic3r/Preset.cpp
- src/libslic3r/PrintConfig.cpp
- src/libslic3r/PrintConfig.hpp
- src/slic3r/GUI/Tab.cpp
Internal thick bridge off:  
Internal thick bridge on:
> thick internal bridges

- src/libslic3r/PerimeterGenerator.cpp
Fix for sandwich wall ordering not working post BBS latest feature merge.
> Feature Merge: Fix for inner-outer-inner mode post BBS feature merge

- src/slic3r/GUI/3DBed.cpp
- src/slic3r/GUI/3DBed.hpp
This should slightly improve the GUI performance
> Only regenerate bed triangles if actually changed

- src/slic3r/GUI/Gizmos/GLGizmoSVG.cpp
(cherry picked from commit prusa3d/PrusaSlicer@f31d7f1d8c9b6d65295521bbbcbcd48c64879727)
Fixes issue https://github.com/prusa3d/PrusaSlicer/issues/11759
> Fix checking is volume svg

- src/slic3r/GUI/MainFrame.cpp
> Fix window maximize when task bar is on the left.

- src/slic3r/GUI/3DScene.cpp
- src/slic3r/GUI/GCodeViewer.cpp
> Fix regression that shell is not rendered unless slice is completed

- src/libslic3r/GCode.cpp
- src/libslic3r/Preset.cpp
- src/libslic3r/PrintConfig.cpp
- src/libslic3r/PrintConfig.hpp
- src/slic3r/GUI/Tab.cpp
> Add a new option "emit_machine_limits_to_gcode"

- src/slic3r/GUI/Jobs/PlaterWorker.hpp
> Trigger task progress update on paint event as well

- localization/i18n/OrcaSlicer.pot
- localization/i18n/cs/OrcaSlicer_cs.po
- localization/i18n/de/OrcaSlicer_de.po
- localization/i18n/en/OrcaSlicer_en.po
- localization/i18n/es/OrcaSlicer_es.po
- localization/i18n/fr/OrcaSlicer_fr.po
- localization/i18n/hu/OrcaSlicer_hu.po
- localization/i18n/it/OrcaSlicer_it.po
- localization/i18n/ja/OrcaSlicer_ja.po
- localization/i18n/ko/OrcaSlicer_ko.po
- localization/i18n/list.txt
- localization/i18n/nl/OrcaSlicer_nl.po
- localization/i18n/ru/OrcaSlicer_ru.po
- localization/i18n/sv/OrcaSlicer_sv.po
- localization/i18n/tr/OrcaSlicer_tr.po
- localization/i18n/uk/OrcaSlicer_uk.po
- localization/i18n/zh_CN/OrcaSlicer_zh_CN.po
- localization/i18n/zh_TW/OrcaSlicer_zh_TW.po
- resources/data/hints.ini
- src/OrcaSlicer.cpp
- src/libslic3r/PrintConfig.cpp
- src/slic3r/GUI/CreatePresetsDialog.cpp
- src/slic3r/GUI/MediaPlayCtrl.cpp
- src/slic3r/GUI/Plater.cpp
- src/slic3r/GUI/Widgets/SideTools.cpp
- src/slic3r/GUI/WipeTowerDialog.cpp
fixed [#3191](https://github.com/SoftFever/OrcaSlicer/issues/3191)
> Feature/add more hints and fix/update locale

- localization/i18n/OrcaSlicer.pot
- localization/i18n/cs/OrcaSlicer_cs.po
- localization/i18n/de/OrcaSlicer_de.po
- localization/i18n/en/OrcaSlicer_en.po
- localization/i18n/es/OrcaSlicer_es.po
- localization/i18n/fr/OrcaSlicer_fr.po
- localization/i18n/hu/OrcaSlicer_hu.po
- localization/i18n/it/OrcaSlicer_it.po
- localization/i18n/ja/OrcaSlicer_ja.po
- localization/i18n/ko/OrcaSlicer_ko.po
- localization/i18n/nl/OrcaSlicer_nl.po
- localization/i18n/ru/OrcaSlicer_ru.po
- localization/i18n/sv/OrcaSlicer_sv.po
- localization/i18n/tr/OrcaSlicer_tr.po
- localization/i18n/uk/OrcaSlicer_uk.po
- localization/i18n/zh_CN/OrcaSlicer_zh_CN.po
- localization/i18n/zh_TW/OrcaSlicer_zh_TW.po
- resources/data/hints.ini
- src/slic3r/GUI/Gizmos/GLGizmoAdvancedCut.cpp
- src/slic3r/GUI/Gizmos/GLGizmoCut.cpp
- src/slic3r/GUI/KBShortcutsDialog.cpp
Fixed a funny typo in shortcuts
> Fixed typo

- localization/i18n/tr/OrcaSlicer_tr.po
Update OrcaSlicer_tr.po - TURKISH translation update
> Update OrcaSlicer_tr.po - TURKISH translation update

- localization/i18n/de/OrcaSlicer_de.po
> Fix de for 1.9 release

- src/slic3r/GUI/Gizmos/GLGizmosCommon.cpp
Cherry-picked from bambulab/BambuStudio@1e99ce9535ace1d1858efe38e5f9a0a7db135a6e
Fixes #3404
> Fix crash when click the color paint gizmo when object part is selected

- localization/i18n/uk/OrcaSlicer_uk.po
Added and fixed some Ukrainian translations.
> edit Ukrainian translation

- resources/profiles/BBL/process/0.48mm Standard @BBL X1C 0.8 nozzle.json
Removed P1S 0.6mm nozzle from process profile.
> Update 0.48mm Standard @BBL X1C 0.8 nozzle.json

- src/slic3r/GUI/GUI_ObjectList.cpp
> Fix NaN when adding negative part (#3423)

- resources/profiles/Elegoo/machine/Elegoo Neptune 3 Max 0.4 nozzle.json
- resources/profiles/Elegoo/machine/Elegoo Neptune 3 Plus 0.4 nozzle.json
- resources/profiles/Elegoo/machine/Elegoo Neptune 3 Pro 0.4 nozzle.json
- resources/profiles/Elegoo/machine/Elegoo Neptune X 0.4 nozzle.json
Added M600 for Elegoo Neptune 3 series, they support that command from 2022 👍 
And removed bad PAUSE command from Neptune X.
> M600 for Neptune 3 series (and removed from Neptune X)

- resources/profiles/Qidi/machine/fdm_qidi_x3_common.json
correct thumbnails scale  on Qidi X3 printer
> Qidi x 3 thumbnail scale

- src/slic3r/GUI/Gizmos/GLGizmoScale.cpp
- src/slic3r/GUI/Gizmos/GLGizmoScale.hpp
> Fix constrainted scale (scale with ctrl key pressed)

- README.md
I forget every time, so this documentation is as much for me as anybody else. :)
> Document building and debugging with XCode.

- src/slic3r/GUI/Gizmos/GLGizmoCut.cpp
This PR:
- Makes the grabber larger
- Marks the color of upper & lower part
This should solve the issue raised here https://github.com/SoftFever/OrcaSlicer/issues/3699#issuecomment-1893747386 by @chuckkay
> QoL: Some UI improvements to Cut Gizmo

- src/slic3r/GUI/Selection.cpp
> Retain mirror state when scaling using text input (#3643)

- localization/i18n/es/OrcaSlicer_es.po
updated some strings from the spanish translation
> Update Spanish translation

- src/libslic3r/PrintConfig.cpp
https://github.com/SoftFever/OrcaSlicer/issues/3555#issuecomment-1911147595
Thanks @dcchillin46 for the advice~
> Update the naming of the layer order option to intra-layer order

- resources/images/color_picker_border_dark.svg
As per title, a quick fix to address a missing asset causing the application to crash post latest BBL feature merge.
> Fix crashing on AMS filament edit

- .github/ISSUE_TEMPLATE/config.yml
Make reporting easier - part I
> Make reporting easier - part I

- src/slic3r/GUI/GUI_ObjectList.cpp
> Fix object list crash on click (#2823)

- src/libslic3r/PerimeterGenerator.cpp
> Fixed a bug that in edge cases, wrong top surfaces were detected

- localization/i18n/fr/OrcaSlicer_fr.po
Updated po French file for newly added Scarf joint seams 🥳
> Added new French translations

- localization/i18n/tr/OrcaSlicer_tr.po
Corrected incorrect translations
> Update Turkish Language translation

- src/slic3r/GUI/Tab.cpp
> Fixed an issue that changing printer selection clears out Process overrides

- src/libslic3r/PrintConfig.cpp
- src/libslic3r/PrintConfig.hpp
- src/libslic3r/PrintObject.cpp
> Fix an issue that only 1 bottom/top will be generated when ensure vertical thickness is set to None

- resources/profiles/Creality/filament/Creality Generic PA-CF @K1-all.json
- resources/profiles/Creality/filament/Creality Generic PA-CF.json
- resources/profiles/Creality/filament/Creality Generic PLA-CF.json
Fixed a potential regression introduced in recent update.
Will avoid getting stuck later
> Fix for missing K1 references

- resources/profiles/Anker/machine/Anker M5C 0.6 nozzle.json
> Fix Anker M5C 0.6 bed size

- resources/profiles/Artillery/machine/Artillery Sidewinder X1 0.4 nozzle.json
> Fix excessive maximum z accelleration for Artillery Sidewinder X1

- src/libslic3r/AppConfig.cpp
- src/slic3r/GUI/Preferences.cpp
- src/slic3r/GUI/Tab.cpp
Add an option to allow user disable printer configuration
Fixes #4750
Fixes #2705
Tested with some multi color .3mf files
> Add an option to allow user disable printer configuration

- src/libslic3r/GCode.cpp
Fixed a bug that overhang slowdown may slowdown too much in some cases.
before, it slowed down to 4 mm/s despite we had minimal speed to 10:
after:
Speculate generated gcode
> fix wrong overhang slowdown value

- BuildLinux.sh
- linux.d/README.md
- linux.d/arch
- linux.d/fedora
- linux.d/ubuntu
* change to ninja build system
* distribution specific logic broken out
* n/9 progress entries make no sense, removing
* {}'ing all variables
* sorting help output
* sorting package lists
* project doesn't use submodules, removing logic
> rework of Linux build scripts

- src/slic3r/GUI/Tab.cpp
- src/slic3r/GUI/Widgets/TabCtrl.cpp
• Updates underline color for Selected tab with orca color
• Fixes position changes on tabs with calculating tab width from bold font
New vs Old
> Tab improvements

- deps/OpenCV/OpenCV.cmake
> disable eigen for OpenCV

- resources/profiles/Creality/machine/Creality Ender-3 V3 0.4 nozzle.json
- resources/profiles/Creality/machine/Creality Ender-3 V3 0.6 nozzle.json
When addind Ender 3 V3, the default process is not the one set on the configuration. A space is missing...
> Fixed default profiles for Ender 3 V3

- localization/i18n/OrcaSlicer.pot
- localization/i18n/ca/OrcaSlicer_ca.po
- localization/i18n/cs/OrcaSlicer_cs.po
- localization/i18n/de/OrcaSlicer_de.po
- localization/i18n/en/OrcaSlicer_en.po
- localization/i18n/es/OrcaSlicer_es.po
- localization/i18n/fr/OrcaSlicer_fr.po
- localization/i18n/hu/OrcaSlicer_hu.po
- localization/i18n/it/OrcaSlicer_it.po
- localization/i18n/ja/OrcaSlicer_ja.po
- localization/i18n/ko/OrcaSlicer_ko.po
- localization/i18n/nl/OrcaSlicer_nl.po
- localization/i18n/pl/OrcaSlicer_pl.po
- localization/i18n/pt_BR/OrcaSlicer_pt_BR.po
- localization/i18n/ru/OrcaSlicer_ru.po
- localization/i18n/sv/OrcaSlicer_sv.po
- localization/i18n/tr/OrcaSlicer_tr.po
- localization/i18n/uk/OrcaSlicer_uk.po
- localization/i18n/zh_CN/OrcaSlicer_zh_CN.po
- localization/i18n/zh_TW/OrcaSlicer_zh_TW.po
>> Removes check to disable nozzle override from Bambu Studio. (#5459)
> Updated string after merged #5459

- src/libslic3r/GCode.cpp
> Fix time cost not being considered in total cost

- src/slic3r/Utils/Http.cpp
> Fix PrusaLink upload when PUT is used

- localization/i18n/ru/OrcaSlicer_ru.po
Russian Translation Update for OrcaSlicer V2.1.0 Official Release.
> Update russian translations (2.1.0 Release)

- src/slic3r/GUI/SelectMachine.cpp
Restores fix from this PR that were lost in a subsequent change.
https://github.com/SoftFever/OrcaSlicer/pull/5459
> Restore nozzle override fix

- linux.d/clear-linux-os
Add some initial support for Clear Linux OS (https://www.clearlinux.org/).
> support Clear Linux OS

- localization/i18n/ko/OrcaSlicer_ko.po
This PR updates the Korean translation for v2.1.1.
> Update Korean Translation (v2.1.1)

- localization/i18n/de/OrcaSlicer_de.po
New German translation for missing msgid’s
> add new de for v2.1.1

- src/slic3r/Utils/Http.cpp
> Try fixing build with gcc 13.3 (SoftFever/OrcaSlicer#5991)

- src/libslic3r/AppConfig.cpp
- src/slic3r/GUI/Plater.cpp
- src/slic3r/GUI/Preferences.cpp
Add option to arrange plate after cloning:
> Auto arrange plate after cloning

- .github/workflows/build_deps.yml
- .github/workflows/build_orca.yml
> pin cmake version to 3.28

- .github/workflows/update-translation.yml
- run_gettext.bat
- run_gettext.sh
- scripts/HintsToPot.py
This PR adds an automation workflow that updates the translation catalog when the relevant source files are updated.
The workflow is triggered by changes of the file(s) listed in [localization/i18n/list.txt](https://github.com/SoftFever/OrcaSlicer/blob/main/localization/i18n/list.txt).
Resolves #5961
- Proof-of-concept workflow: <https://github.com/ElectricalBoy/OrcaSlicer/actions/runs/9737476435>
Generated d7f6dc8
> CI: Create Automated Workflow for Translation Catalog Updates

- src/slic3r/GUI/GUI_App.cpp
- src/slic3r/GUI/PrinterWebView.cpp
- src/slic3r/GUI/PrinterWebView.hpp
Helps when debugging printer interfaces
Tested on Windows
> Enable WebView devtools if developer mode is enabled

- src/libslic3r/Print.cpp
- src/libslic3r/PrintObject.cpp
- src/slic3r/GUI/PartPlate.cpp
> Properly find used extruders when infill/wall_filament is set

- src/libslic3r/Fill/FillConcentric.cpp
Shift concentric infill seams for at least 0.5mm to increase strength and prevent blob formation.
Before:
After:
Could be done configurable, but I guess it's better to always shift seams.
> Stagger concentric infill seams.

- resources/profiles/Artillery/filament/Artillery ABS.json
- resources/profiles/Artillery/filament/Artillery PETG.json
- resources/profiles/Artillery/filament/Artillery PLA Basic.json
- resources/profiles/Artillery/filament/Artillery PLA Matte.json
- resources/profiles/Artillery/filament/Artillery PLA Silk.json
- resources/profiles/Artillery/filament/Artillery PLA Tough.json
- resources/profiles/Artillery/filament/Artillery TPU.json
- resources/profiles/Artillery/machine/Artillery Sidewinder X3 Plus 0.4 nozzle.json
- resources/profiles/Artillery/machine/Artillery Sidewinder X3 Pro 0.4 nozzle.json
- resources/profiles/Artillery/machine/Artillery Sidewinder X4 Plus 0.4 nozzle.json
- resources/profiles/Artillery/machine/Artillery Sidewinder X4 Pro 0.4 nozzle.json
- resources/profiles/Artillery/process/0.20mm Standard @Artillery X3Plus 0.4 nozzle.json
- resources/profiles/Artillery/process/0.20mm Standard @Artillery X3Pro 0.4 nozzle.json
- resources/profiles/Artillery/process/0.20mm Standard @Artillery X4Plus 0.4 nozzle.json
- resources/profiles/Artillery/process/0.20mm Standard @Artillery X4Pro 0.4 nozzle.json
Update Artillery's machine, filament and process profiles
> Artillery proflies update

- src/slic3r/GUI/GUI.cpp
- src/slic3r/GUI/GUI.hpp
This fixes #6449.
Detailed descussions are in the original issue.
> Fix "Open Containing Folder" on Linux

- src/libslic3r/GCode.cpp
- src/libslic3r/GCode/SeamPlacer.cpp
- src/libslic3r/GCode/SeamPlacer.hpp
Small refactoring - remove unused parameter from `SeamPlacer::place_seam` method
> Remove unused parameter from place_seam method

- src/libslic3r/LayerRegion.cpp
- src/libslic3r/PrintObject.cpp
- src/libslic3r/utils.cpp
Fixes #6642
Cherry picked from https://github.com/prusa3d/PrusaSlicer/commit/b133579126e6cee44f841f66dbae018455e32117
Huge thanks for their excellent work!
> Fix bridge anchor when bridge is also the top surface

- src/imgui/imgui_widgets.cpp
- src/slic3r/GUI/Gizmos/GLGizmoEmboss.cpp
- src/slic3r/GUI/Jobs/PrintJob.cpp
- src/slic3r/GUI/ObjColorDialog.cpp
- src/slic3r/GUI/Plater.cpp
- src/slic3r/GUI/WebGuideDialog.cpp
- src/slic3r/GUI/WipeTowerDialog.cpp
Small fixes of various warnings, functionality shouldn't be affected.
> Warnings: various fixes

- src/slic3r/GUI/GCodeViewer.cpp
- src/slic3r/GUI/GLCanvas3D.cpp
- src/slic3r/GUI/GUI_Factories.cpp
- src/slic3r/GUI/HintNotification.cpp
- src/slic3r/GUI/IMSlider.cpp
- src/slic3r/GUI/Jobs/PrintJob.cpp
- src/slic3r/GUI/Jobs/RotoptimizeJob.cpp
- src/slic3r/GUI/Jobs/SendJob.cpp
> Warnings: remove empty code

- src/libslic3r/GCode/ToolOrdering.cpp
> Bugfix: gapfill was assigned with wrong extruder/filament

- resources/profiles/Anycubic/machine/Anycubic Kobra 0.4 nozzle.json
> Fix Anycubic Kobra 0.4 nozzle profile

- README.md
- Readme.txt
- SECURITY.md
Basically i deleted the old Reademe.txt that was not in use, upgraded the Security doc and proved a little the readme fixing some typos and formatting plus adding the icon of the project to the top left
> Please provide a summary of the changes made in this PR. Include details such as:
> * What issue does this PR address or fix?
Docs reliability  
> * What new features or enhancements does this PR introduce?
Improved different sections in the docs
> * Are there any breaking changes or dependencies that need to be considered?
N/A
> Improvementes in readme and security docs

- src/slic3r/GUI/Plater.cpp
Fix #6801
Cherry picked from https://github.com/bambulab/BambuStudio/commit/ed81888b6cfd5b7c07aa4bacf5a629c4dcfe51dd, thanks BambuStudio!
> FIX:open or replace 3MF file case insensitive

- cmake/modules/MacOSXBundleInfo.plist.in
- src/libslic3r/Utils.hpp
- src/platform/osx/Info.plist.in
- src/slic3r/GUI/Downloader.cpp
- src/slic3r/GUI/InstanceCheck.cpp
support downloading from makerworld on Mac by default.
fix #3753
> support downloading from makerworld on Mac by default.

- src/libslic3r/PrintConfig.cpp
- src/slic3r/GUI/Plater.cpp
- src/slic3r/GUI/Plater.hpp
> Fix a bed type regression

- src/slic3r/GUI/SlicingProgressNotification.cpp
Makes situations like #6098 less confusing.
Old:
New:
> Support multi-line progress information rendering

- doc/Calibration.md
fix typo in docs
https://github.com/SoftFever/OrcaSlicer/issues/7101
> Fix typo in Calibration.md

- resources/profiles/Kingroon.json
> Fix: kp3s v1 json configuration error

- src/slic3r/Utils/CalibUtils.cpp
Fixes #6028
Fixes #6249
Fixes #7224
> Fix crash when doing PA calib using pattern method from calib tab

- src/libslic3r/Format/bbs_3mf.cpp
> Fix 3mf object type to conform the 3mf core spec

- src/slic3r/GUI/Mouse3DController.cpp
Update the device list to match the upstream spacenavd one.
> Mouse3DController: Add SpaceMouse Wireless BT support

- src/libslic3r/ShortestPath.cpp
Cherry picked from prusa3d/PrusaSlicer@534792e249da3efb83a62279f532b6690d028592
Thanks @supermerill and Prusa!
> Fix bug ShortestPath.cpp (#13331)

- CMakeLists.txt
- src/slic3r/GUI/AboutDialog.cpp
Changes: 
1. Always display build number for all build
2. Made some aesthetic changes
Ref to @ElectricalBoy's [#6516](https://github.com/SoftFever/OrcaSlicer/pull/6516)
> aesthetic change for build info

- .github/workflows/build_orca.yml
> free mac space

- localization/i18n/fr/OrcaSlicer_fr.po
Added missing French translations
> Added French translations

- src/slic3r/GUI/GUI_App.cpp
- src/slic3r/GUI/Tab.cpp
https://github.com/SoftFever/OrcaSlicer/pull/7483
a more reasonable pr.
> Fix：wrong extruder count by switching printers with tab

- src/libslic3r/Fill/Fill.cpp
- src/libslic3r/Preset.cpp
- src/libslic3r/PrintConfig.cpp
- src/libslic3r/PrintConfig.hpp
- src/slic3r/GUI/ConfigManipulation.cpp
- src/slic3r/GUI/GUI_Factories.cpp
- src/slic3r/GUI/Tab.cpp
Added Ironing Inset feature requested in https://github.com/SoftFever/OrcaSlicer/issues/5812, https://github.com/SoftFever/OrcaSlicer/issues/3808 and https://github.com/SoftFever/OrcaSlicer/discussions/2778.
Cherry picked from https://github.com/bambulab/BambuStudio/commit/4b23b42b2238efecf81439b6cf20e68d12648f89
> Feature Ironing Inset added

- src/libslic3r/PrintConfig.cpp
Fix a regression error caused in #7969
> Fix "Too small ironing spacing" error in default config

- .github/workflows/build_all.yml
> Fix flatpak build

- src/libslic3r/GCode/GCodeProcessor.cpp
… and triggers preheat 
Fix #7842
> Fix issue that `TIMELAPSE_TAKE_FRAME` is recognized as tool change command

- src/slic3r/GUI/Gizmos/GLGizmoEmboss.cpp
- src/slic3r/GUI/Jobs/CreateFontNameImageJob.cpp
- src/slic3r/GUI/Jobs/CreateFontStyleImagesJob.cpp
Fix #7916
CHerry picked from prusa3d/PrusaSlicer@b67c4785f0d300b5615126ea1df1d518dd6d00b0
CHerry picked from prusa3d/PrusaSlicer@eb9b8c0c2b112f0f7649e58f4f6d7977380b8442 
Thanks Prusa!
> Update Emboss font preview alignment

- src/libslic3r/GCode/ToolOrdering.cpp
> Fix wrong custom gcode layer caused by rounding error

- src/libslic3r/Preset.cpp
- src/slic3r/GUI/Tab.cpp
Redo the fix for #7860 and #7483.
Also fix #8019
> Fix extruder number issue when SEMM is not enabled

- src/slic3r/GUI/Gizmos/GLGizmosManager.cpp
> Fix issue that flatten gizmo faces not updated after reload from disk

- src/slic3r/GUI/Plater.cpp
Fix #7952
Cherry picked from bambulab/BambuStudio@539dea08854673045db779332fd1c2a0d994beda 
Cherry picked from bambulab/BambuStudio@b5d18d4ae7a5b1c40e728ac93a96d36dabe83d42 
> Fix reload step modifiers/parts

- src/libslic3r/Format/STEP.cpp
Fix #3169
cherry picked from bambulab/BambuStudio@90f325792dc4910b80d69c9d6a5677f24b8fa259 
> FIX: step model split COMPOUND and COMPOUNSOLID type

- src/slic3r/GUI/MainFrame.cpp
Fix #8085
Due to the limitation of windows, to allow the task bar to work properly, I have to leave a small gap at the edge of the window when maximized. This only take affect when auto-hide taskbar is enabled.
See https://stackoverflow.com/a/61540163/3289421
This code is adopted from https://gist.github.com/MortenChristiansen/6463580, huge thanks to @MortenChristiansen
> Fix auto-hide taskbar overlapping issue when maximized

- localization/i18n/zh_TW/OrcaSlicer_zh_TW.po
This PR provides a comprehensive update to the Traditional Chinese localization of the OrcaSlicer project. It addresses inconsistencies and outdated translations.
Updated localization files: Refined translations in OrcaSlicer_zh_TW.po to align with modern terminology and contextually accurate phrasing.
Issues Addressed:
- Fixes inconsistencies in Traditional Chinese translations.
- Aligns localization with the latest feature updates introduced in OrcaSlicer.
1. Reviewed the added Traditional Chinese translations to ensure accuracy and consistency.
2. Tested the application to confirm no unintended side effects in the Ul or functionality.
> Comprehensive Update in Traditional Chinese

- src/libslic3r/GCode.cpp
> Make sure to move to prime tower before moving down

- src/slic3r/GUI/Gizmos/GLGizmoFlatten.cpp
Fix #8139
Follow up of a66fc86e203572f84a0761d607fc7e0170e3afd7
> Fix issue that gizmo grabbers stop working

- README.md
As stated in the header.
The **_.info_** domain appears to have been taken down.
Please correct me if I'm wrong.
closes #8158
> updated fake 'orcaslicer - websites'

- flatpak/io.github.softfever.OrcaSlicer.yml
Note: you also need to update flatpak config to add desired locales to flatpak environment via `flatpak config --set languages='en;ru'; flatpak update` or `flatpak --user config --set languages='en;ru'; flatpak --user update`
> flatpak: install translations in flatpak

- src/slic3r/Utils/PresetUpdater.cpp
Fix #8094
Replace #8102
Thanks @buzzhuzz for the initial investigation and PR
> Fix custom profiles added/removed each other run

- resources/profiles/Sovol/process/0.08mm High Quality @Sovol SV06 ACE 0.4 nozzle.json
- resources/profiles/Sovol/process/0.12mm Quality @Sovol SV06 ACE 0.4 nozzle.json
- resources/profiles/Sovol/process/0.12mm Standard @Sovol SV06 ACE 0.2 nozzle.json
- resources/profiles/Sovol/process/0.20mm Standard @Sovol SV06 ACE.json
- resources/profiles/Sovol/process/0.20mm Standard @Sovol SV06 Plus ACE.json
- resources/profiles/Sovol/process/0.28mm Fast @Sovol SV06 ACE 0.4 nozzle.json
- resources/profiles/Sovol/process/0.30mm Standard @Sovol SV06 ACE 0.6 nozzle.json
- resources/profiles/Sovol/process/0.40mm Standard @Sovol SV06 ACE 0.8 nozzle.json
For improve quality of print related to  : https://github.com/SoftFever/OrcaSlicer/pull/8180
Thank for @bcat for your great work.
I think we can improve again the print quality of SV06 ACE (In next time if you are in discord @bcat probably better for make tests)
> Sovol SV06 ACE Reset wall_sequence

- .github/workflows/build_deps.yml
- cmake/modules/Findlibnoise.cmake
- deps/CMakeLists.txt
- flatpak/io.github.softfever.OrcaSlicer.yml
- src/libslic3r/PerimeterGenerator.cpp
> fix build errors

- resources/profiles/Creality/filament/Creality Generic ABS @Hi-all.json
- resources/profiles/Creality/filament/Creality Generic ASA @Hi-all.json
- resources/profiles/Creality/filament/Creality Generic PETG @Hi-all.json
- resources/profiles/Creality/filament/Creality Generic PLA @Hi-all.json
- resources/profiles/Creality/filament/Creality Generic TPU @Hi-all.json
There are missing commands in filaments, those commands are in filament_start_gcode.
This PR will add them !
> Added missing filament_start_gcode to Creality Hi

- src/slic3r/GUI/AboutDialog.cpp
just set conditions on wrong side on previous commit https://github.com/SoftFever/OrcaSlicer/pull/8189
> Fix for about page

- .github/workflows/build_all.yml
> disable flatpak upload

- localization/i18n/de/OrcaSlicer_de.po
update translation for new features
> update de translation

- src/clipper/clipper.hpp
Fixed a regression bug caused by #8195
Ref to: https://github.com/SoftFever/OrcaSlicer/pull/8263#issuecomment-2646052614
> fix a crash bug when generating support

- resources/profiles/Creality.json
- resources/profiles/Creality/filament/Creality Generic PLA Wood @Hi-all.json
- resources/profiles/Creality/machine/Creality Hi.json
New kind of filament ready to use for Creality Hi !
> Add Creality Generic PLA Wood for Creality Hi

- src/libslic3r/GCode/FanMover.hpp
> Fix Fan mover when absolute E is used

- resources/profiles/BBL.json
- resources/profiles/BBL/filament/SUNLU/SUNLU Marble PLA @base.json
- resources/profiles/BBL/filament/SUNLU/SUNLU PETG @base.json
- resources/profiles/BBL/filament/SUNLU/SUNLU PLA Matte @base.json
- resources/profiles/BBL/filament/SUNLU/SUNLU PLA+ 2.0 @base.json
- resources/profiles/BBL/filament/SUNLU/SUNLU PLA+ @BBL A1 0.2 nozzle.json
- resources/profiles/BBL/filament/SUNLU/SUNLU PLA+ @BBL A1M.json
- resources/profiles/BBL/filament/SUNLU/SUNLU PLA+ @base.json
- resources/profiles/BBL/filament/SUNLU/SUNLU Silk PLA+ @base.json
- resources/profiles/BBL/filament/SUNLU/SUNLU Wood PLA @base.json
- Updated filament parameters from SUNLU 2024 TDS (https://3dsunlu.com/pages/materials)
- Fixed PLA Marble naming
- Fixed A1/A1M Setting ID
> Updated/fixed SUNLU filament parameters for BBL

- src/libslic3r/GCode/GCodeProcessor.cpp
Reverts SoftFever/OrcaSlicer#8388
Revert it as It will break multi tool
> Revert "Fix strange M73 behaviour, where M73 is still present, even if disabled"

- localization/i18n/pt_BR/OrcaSlicer_pt_BR.po
Add some pt-BR translations that were missing.
> Add some missing pt-BR translations

- localization/i18n/pt_BR/OrcaSlicer_pt_BR.po
> Add missing pt-BR translations

- src/slic3r/GUI/GLCanvas3D.cpp
Adopted from bambulab/BambuStudio@ba1951338045b04537159052a64e167bdac411ae and bambulab/BambuStudio@d0e91b5164afdb5b13e8b837aea6dfc884596546
Old:
New:
> Fix fov so off-plate objects can be rendered properly

- src/libslic3r/GCodeWriter.cpp
Revert for now, please ref to #7326 for more details
Reverts SoftFever/OrcaSlicer#7208
> Revert "Avoid collisions when moving Z down"

- .github/workflows/check_profiles.yml
- resources/profiles/Elegoo/filament/ELEGOO/Elegoo ASA.json
- resources/profiles/Elegoo/filament/ELEGOO/Elegoo PETG PRO.json
- resources/profiles/Elegoo/filament/ELEGOO/Elegoo PLA Matte.json
- resources/profiles/Elegoo/filament/ELEGOO/Elegoo PLA PRO.json
- resources/profiles/Elegoo/filament/ELEGOO/Elegoo PLA Silk.json
- resources/profiles/Elegoo/filament/ELEGOO/Elegoo PLA+.json
- resources/profiles/Elegoo/filament/ELEGOO/Elegoo PLA-CF.json
- resources/profiles/Elegoo/filament/ELEGOO/Elegoo PLA.json
- resources/profiles/Elegoo/filament/ELEGOO/Elegoo RAPID PETG+.json
- resources/profiles/Elegoo/filament/ELEGOO/Elegoo RAPID PETG.json
- resources/profiles/Elegoo/filament/ELEGOO/Elegoo RAPID PLA+.json
- scripts/orca_extra_profile_check.py
> add extra profile checks

- src/libslic3r/Preset.cpp
- src/libslic3r/Preset.hpp
- src/slic3r/GUI/CreatePresetsDialog.cpp
> Fix a crash issue then exporting preset bundle

- resources/profiles/BBL.json
- resources/profiles/BBL/filament/AliZ/AliZ PA-CF @P1-X1.json
- resources/profiles/BBL/filament/AliZ/AliZ PETG @P1-X1.json
- resources/profiles/BBL/filament/AliZ/AliZ PETG-CF @P1-X1.json
- resources/profiles/BBL/filament/AliZ/AliZ PETG-Metal @P1-X1.json
- resources/profiles/BBL/filament/AliZ/AliZ PLA @P1-X1.json
> Fix AMS mapping bug

- src/libslic3r/PrintConfig.cpp
Fix strings missing localization on PrintConfig
> Fix strings missing localization on PrintConfig

- README.md
> Added small Japanese translation

- src/libslic3r/GCode.cpp
> apply adaptive pa in object mode

- src/platform/unix/BuildLinuxImage.sh.in
Cleaned up and simplified the logic of PR #8373
> Cleanup the logic for Zink Override

- localization/i18n/uk/OrcaSlicer_uk.po
> chore: Improve Ukrianian translation

- localization/i18n/ca/OrcaSlicer_ca.po
Catalan language updated to OrcaSlicer v2.3.0-beta2
> Catalan language updated to OrcaSlicer v2.3.0-beta2

- localization/i18n/OrcaSlicer.pot
- localization/i18n/ca/OrcaSlicer_ca.po
- localization/i18n/cs/OrcaSlicer_cs.po
- localization/i18n/de/OrcaSlicer_de.po
- localization/i18n/en/OrcaSlicer_en.po
- localization/i18n/es/OrcaSlicer_es.po
- localization/i18n/fr/OrcaSlicer_fr.po
- localization/i18n/hu/OrcaSlicer_hu.po
- localization/i18n/it/OrcaSlicer_it.po
- localization/i18n/ja/OrcaSlicer_ja.po
- localization/i18n/ko/OrcaSlicer_ko.po
- localization/i18n/nl/OrcaSlicer_nl.po
- localization/i18n/pl/OrcaSlicer_pl.po
- localization/i18n/pt_BR/OrcaSlicer_pt_BR.po
- localization/i18n/ru/OrcaSlicer_ru.po
- localization/i18n/sv/OrcaSlicer_sv.po
- localization/i18n/tr/OrcaSlicer_tr.po
- localization/i18n/uk/OrcaSlicer_uk.po
- localization/i18n/zh_CN/OrcaSlicer_zh_CN.po
- localization/i18n/zh_TW/OrcaSlicer_zh_TW.po
I missed one string on the #8471 patch
> Add leftover strings from "overwrite dialog" fix

- src/slic3r/GUI/Plater.cpp
> Switch to print-by-layer mode automatically for PA pattern test

- src/libslic3r/Print.hpp
> Fix issue that painted brim is not generated if brim width is set to 0

- localization/i18n/ru/OrcaSlicer_ru.po
> Update Russian translation

- src/slic3r/GUI/BackgroundSlicingProcess.cpp
- src/slic3r/GUI/GUI_App.cpp
Fix issue that when you open a gcode file in Orca the gcode preview disappears immediately after been loaded.
> Fix gcode viewer not working properly when opening .gcode files

- src/libslic3r/Print.cpp
- src/slic3r/GUI/BackgroundSlicingProcess.cpp
- src/slic3r/GUI/CreatePresetsDialog.cpp
- src/slic3r/GUI/Gizmos/GLGizmoEmboss.cpp
- src/slic3r/GUI/Gizmos/GLGizmoMeasure.cpp
Some strings were not marked for translation.
> Mark strings missing from translation

- .github/workflows/orca_bot.yml
Feature requests don't go stale
n/a
n/a
> stale bot: exempt "enhancement" label

- src/libslic3r/GCodeWriter.cpp
> Fix crash when slicing batch PA pattern test

- localization/i18n/de/OrcaSlicer_de.po
> fix de after update locale

- resources/profiles/Sovol/machine/Sovol SV07 0.4 nozzle.json
- resources/profiles/Sovol/machine/Sovol SV08 0.2 nozzle.json
- resources/profiles/Sovol/machine/Sovol SV08 0.4 nozzle.json
- resources/profiles/Sovol/machine/Sovol SV08 0.6 nozzle.json
- resources/profiles/Sovol/machine/Sovol SV08 0.8 nozzle.json
> Add pause gcode command to Sovol SV08 & SV07

- resources/profiles/Creality.json
- resources/profiles/Creality/process/0.16mm Optimal @Creality CR-6 0.2.json
- resources/profiles/Creality/process/0.16mm Optimal @Creality CR-6 0.6.json
> Show Creality CR-6 Optimal processes

- localization/i18n/zh_TW/OrcaSlicer_zh_TW.po
Updated and improved the localization for the upcoming 2.3.0-rc release in Traditional Chinese.
No UI changes applicable for this update.
Verified the Traditional Chinese localization by checking various UI texts in the application.
> Traditional Chinese Localization Update in 2.3.0-rc

- src/slic3r/GUI/GUI_App.cpp
- src/slic3r/GUI/GUI_App.hpp
- src/slic3r/GUI/Plater.cpp
> Use .gcode.3mf as ext for gcode 3mf files

- src/libslic3r/PresetBundle.cpp
- src/libslic3r/PresetBundle.hpp
- src/slic3r/GUI/GUI_App.cpp
- src/slic3r/GUI/Plater.cpp
Back up user folder for each version to prevent custom profile lost caused by sync.
> backup user folder for each version

- localization/i18n/pt_BR/OrcaSlicer_pt_BR.po
Adding more pt-BR translations
> Adding more pt-BR translations

- src/libslic3r/PresetBundle.cpp
Backup user folder to user_backup-v{version} folder instead of zip file.
This simplify the logic, and have better support of unicode filenames
> Backup user folder to folder instead of zip file

- src/libslic3r/Support/TreeSupport.cpp
> Fix crash when support bottom interface layer is set to `same as top` 

- localization/i18n/ru/OrcaSlicer_ru.po
Translation update (po version 2.3.0 Official Release), correction of errors, add missing strings.
> Russian translation update

- src/libslic3r/Print.cpp
- src/libslic3r/PrintConfig.cpp
Add support for Fibreglass Reinforced PETG
> Add PETG-GF filament type

- deps/MPFR/MPFR.cmake
- flatpak/io.github.softfever.OrcaSlicer.yml
As suggested by @vovodroid, avoid referring to mpfr-current.
https://github.com/SoftFever/OrcaSlicer/pull/9007#issuecomment-2745310796
> avoid using https://www.mpfr.org/mpfr-current link

- src/libslic3r/GCode.cpp
This PR fixes issues of vase mode, when you have raft printed in a different filament.
The layer that color change happens will forced to be printed in normal mode.
Fix #8387
> Fix vase mode with filament change

- scripts/pack_profiles.sh
- src/slic3r/GUI/GUI_App.cpp
- src/slic3r/Utils/PresetUpdater.cpp
Fixed a crash bug of OTA feature
Fixed a bug that OTA update didn't work for OrcaFilamentLibrary
Add a help script to pack OTA package
> Fix broken profile OTA

- src/libslic3r/PrintObject.cpp
> Avoid creating bridges on very tiny surface cracks

- src/slic3r/GUI/GUI_App.cpp
> Disable BBL server error dialog

- src/slic3r/GUI/GUI_ObjectList.cpp
- src/slic3r/GUI/GUI_ObjectList.hpp
> Fix split to objects crash

- src/libslic3r/Fill/FillBase.cpp
- src/libslic3r/Fill/FillPlanePath.cpp
Fix issue in https://github.com/SoftFever/OrcaSlicer/pull/8993
> Ensure the flow calib pattern to be printed in desired order

- src/slic3r/GUI/MainFrame.cpp
> Fix shortcut collision on macOS

- src/slic3r/GUI/GLCanvas3D.cpp
> Camera rotate around current plate center if plate is empty

- src/libslic3r/calib.cpp
- src/libslic3r/calib.hpp
- src/slic3r/GUI/Plater.cpp
> Fix PA calib crash when default line width is set to 0

- src/slic3r/GUI/Tab.cpp
Fix https://github.com/SoftFever/OrcaSlicer/issues/8895#issuecomment-2764217763
> Fix issue that option visibility not updated after resetting

- src/libslic3r/GCode.cpp
> Don't apply adaptive PA in PA calibration

- src/libslic3r/GCode.cpp
> Avoid unnecessary travel in scarf seam

- resources/web/guide/0/load.css
Update text color so it's more visible in dark mode:
Old:
New:
> Update profile selector loading text color

- src/libslic3r/GCode.cpp
- src/libslic3r/GCode.hpp
Fix for  **Enabling object skirt.** #6487 - allow start skirt angle per object.
> Fix skirt start angle per object

- src/slic3r/GUI/AMSMaterialsSetting.cpp
> Fix AMS filament selection compatible check

- README.md
Add social media links to the project so people can follow the **real** social media accounts. There's only a Twitter/X account added so far. I'd be happy to add more.
Additional context: There are many fake accounts, and this addition to the `README.md` helps users determine which accounts are real. Adding the links will protect users and the OrcaSlicer project.
Screenshot of the `README.md` with a social media link.
Made the change and previewed in Github.
> Update README.md with social media links.

- scripts/orca_extra_profile_check.py
1. Support checking `compatible_printers` from parent profiles
2. Improve error message when `compatible_printers` is missing
> Improve profile check script

- scripts/orca_extra_profile_check.py
Make sure it output the correct file path in error message
> Fix profile check error msg

- resources/profiles/OrcaFilamentLibrary.json
- resources/profiles/OrcaFilamentLibrary/filament/FusRock/FusRock ABS-GF @System.json
- resources/profiles/OrcaFilamentLibrary/filament/FusRock/FusRock ABS-GF @base.json
Fix FusRock ABS-GF Parameters in .bbl , 
Add Global Parameters for FusRock ABS-GF
> Fix FusRock ABS-GF Parameters in .bbl , Add Global Parameters for FusRock ABS-GF

- .cursorignore
- .github/workflows/build_all.yml
- .github/workflows/build_orca.yml
- deps/TIFF/TIFF.cmake
> reenable appimage build on ubuntu 24.04

- src/libslic3r/PrintConfig.cpp
- src/slic3r/GUI/BonjourDialog.cpp
- src/slic3r/GUI/CreatePresetsDialog.cpp
- src/slic3r/GUI/GUI_App.cpp
- src/slic3r/GUI/Jobs/PrintJob.cpp
- src/slic3r/GUI/ParamsPanel.cpp
- src/slic3r/GUI/ReleaseNote.cpp
- src/slic3r/GUI/Tab.cpp
- src/slic3r/GUI/WebViewDialog.cpp
I have found more strings not marked for translation.
> Add translation markers on more unstranslated strings

- deps/CGAL/0001-clang19.patch
- deps/CGAL/CGAL.cmake
- deps/OpenCV/0002-clang19-macos.patch
- deps/OpenCV/OpenCV.cmake
- deps/OpenVDB/0001-clang19.patch
- deps/OpenVDB/OpenVDB.cmake
- deps/PNG/0002-clang19-macos.patch
- deps/PNG/PNG.cmake
- src/slic3r/GUI/GUI_App.cpp
- src/slic3r/GUI/ModelMall.cpp
- src/slic3r/GUI/Project.cpp
- src/slic3r/GUI/WebDownPluginDlg.cpp
- src/slic3r/GUI/WebGuideDialog.cpp
Fix Xcode 16.3 build by applying patches from
LibPNG: https://github.com/pnggroup/libpng/commit/893b8113f04d408cc6177c6de19c9889a48faa24
OpenVDB: https://github.com/AcademySoftwareFoundation/openvdb/commit/930c3acb8e0c7c2f1373f3a70dc197f5d04dfe74
CGAL:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=281880
> Fix Xcode 16.3 build

- resources/web/guide/0/load.js
Fix https://github.com/SoftFever/OrcaSlicer/pull/9118#issuecomment-2841201356
> Fix filament/printer selection loading page translation

- src/libslic3r/GCode.cpp
Fix #9374
Cherry picked from bambulab/BambuStudio@b51ff1721ddc2080c4f7e487f67c4f1a722bf091
> Fix floating brim

- src/slic3r/GUI/Tab.cpp
matches width of combo box with other parameter boxes
BEFORE
AFTER
> Fix filament type parameter box uses wrong width

- src/slic3r/GUI/3DBed.cpp
- src/slic3r/GUI/Gizmos/GLGizmoBrimEars.cpp
> Fix brim ear render when camera projection changed

- src/libslic3r/GCode/GCodeProcessor.cpp
> Fix preview gcode misalignment caused by placeholder postprocess

- deps/GMP/0001-GMP_GCC15.patch
- deps/GMP/GMP.cmake
- src/mcut/source/math.cpp
This time the changeset is smaller than with GCC 14. GMP change is a port / expansion on a commit merged into official GMP repo (not yet released).
Closes https://github.com/SoftFever/OrcaSlicer/issues/9564
> Fix building with GCC 15

- src/slic3r/GUI/Gizmos/GLGizmoBrimEars.cpp
- src/slic3r/GUI/Gizmos/GLGizmoBrimEars.hpp
- src/slic3r/GUI/Gizmos/GLGizmosManager.cpp
Fix issue that project is not marked dirty until the brim paint gizmo is closed.
cherry picked from commit bambulab/BambuStudio@a1037509aef57b2276bba3ddcab33a6bfeebf87a
Thanks Bambu!
> Brim ear updates model object in real-time

- src/libslic3r/PrintObject.cpp
Fix https://github.com/SoftFever/OrcaSlicer/pull/9332#issuecomment-2976266642
> Don't split tiny cracks on first layer

- resources/profiles/OrcaFilamentLibrary.json
- resources/profiles/OrcaFilamentLibrary/filament/Valment/Valment PLA @System.json
- resources/profiles/OrcaFilamentLibrary/filament/Valment/Valment PLA @base.json
- resources/profiles/OrcaFilamentLibrary/filament/Valment/Valment PLA Galaxy @System.json
- resources/profiles/OrcaFilamentLibrary/filament/Valment/Valment PLA Galaxy @base.json
- resources/profiles/OrcaFilamentLibrary/filament/Valment/Valment PLA Silk @System.json
- resources/profiles/OrcaFilamentLibrary/filament/Valment/Valment PLA Silk @base.json
- resources/profiles/OrcaFilamentLibrary/filament/Valment/Valment PLA-CF @System.json
- resources/profiles/OrcaFilamentLibrary/filament/Valment/Valment PLA-CF @base.json
Valmet filament pla derivative filaments have been added.
> Valmet filament pla derivative filaments have been added.

- resources/profiles/BBL/process/fdm_process_common.json
> Fix invalid value for `symmetric_infill_y_axis`

- src/libslic3r/Format/bbs_3mf.cpp
> Update 3mf key for fuzzy skin painting to match BBS

- README.md
> Adjust the CAUTION format to make it more visible, as there are more fake websites claim to be official

- resources/profiles/OrcaFilamentLibrary.json
- resources/profiles/OrcaFilamentLibrary/filament/FDplast/FDplast ABS @System.json
- resources/profiles/OrcaFilamentLibrary/filament/FDplast/FDplast ABS @base.json
- resources/profiles/OrcaFilamentLibrary/filament/FDplast/FDplast HIPS @System.json
- resources/profiles/OrcaFilamentLibrary/filament/FDplast/FDplast HIPS @base.json
- resources/profiles/OrcaFilamentLibrary/filament/FDplast/FDplast PETG @System.json
- resources/profiles/OrcaFilamentLibrary/filament/FDplast/FDplast PETG @base.json
- resources/profiles/OrcaFilamentLibrary/filament/FDplast/FDplast PLA @System.json
- resources/profiles/OrcaFilamentLibrary/filament/FDplast/FDplast PLA @base.json
- resources/profiles/OrcaFilamentLibrary/filament/FDplast/FDplast SBS @System.json
- resources/profiles/OrcaFilamentLibrary/filament/FDplast/FDplast SBS @base.json
- resources/profiles/OrcaFilamentLibrary/filament/FDplast/FDplast TPU @System.json
- resources/profiles/OrcaFilamentLibrary/filament/FDplast/FDplast TPU @base.json
Added filaments by FDplast:
- ABS;
- HIPS;
- PETG;
- PLA;
- SBS;
- TPU.
> feat: add ABS, HIPS, PETG, PLA, SBS, TPU filaments by FDplast

- .github/workflows/claude-code-review.yml
- build_release_macos.sh
It's more consistent to develop configurations in IDE like VS Code.  
Make developers' lives easier.
> Update macOS build script to use Ninja Multi-Config generator

- localization/i18n/de/OrcaSlicer_de.po
to fast forgotten some translations here is the fix
> fix more de translation 

- localization/i18n/it/OrcaSlicer_it.po
Updated IT localization for the recently introduced features
> Update Italian translation

- localization/i18n/it/OrcaSlicer_it.po
Correzione di 4 righe tradotte con il traduttore automatico
> Correct 4 Italian translations

- src/dev-utils/CMakeLists.txt
- src/libslic3r/CMakeLists.txt
This PR:
- Fixes #10652
- Fixes 999 cmake warnings:
- fixes: 999 CMake Warnings at src/dev-utils/CMakeLists.txt:39 (add_custom_command)
- cmake clenup: adds PUBLIC/PRIVATE to libslic3r; attempt to reduce warnigns from eigen
> Fixes 999 CMake Warnings

- src/slic3r/Utils/RetinaHelperImpl.mm
Reverts SoftFever/OrcaSlicer#10827
> Revert "Set NSWindow color space to sRGB on macOS"
