- .github/workflows/appimage.yml
- BuildLinux.sh
- deps/wxWidgets/wxWidgets.cmake
- src/platform/unix/build_appimage.sh.in
I have created a PR to create AppImages using GitHub Actions Workflow. 
The main modification I made was add a flag to BuildLinux.sh so it'll skip the memory check as it's not a problem to compile with less ram. That ram check could be removed but I've just simply added a flag to skip it. 
I also added a check to see if you are attempting to run the appimage build in a docker container so it'll patch the appimagetool so it'll run and use the extract and run option in that scenario. GH Action workflow isn't in a container but when testing with [nektos/act](https://github.com/nektos/act) it was needed to confirm the build was working correctly. 
I've incorporated @zhaofengli 's fix  [Disable EGL for wxGLCanvas](https://github.com/zhaofengli/BambuStudio/tree/wx-no-egl) with my PR to get the …
> app image builder feature

- src/libslic3r/Fill/Fill.cpp
- src/libslic3r/GCode.cpp
In case of using Monotonic Line pattern as Top surface pattern our internal solid infills will have a lot of redundant gap fills.
This is second layer of 10 bottom layers and each will have the same gap fills, with more complex geometry it will be even worse. Prusa Slicer do not have "Monotonic Line" pattern at all so we do not have such problem. In case if we want to have "Monotonic Line" pattern as option for the topmost layers, it will be much faster to force internal infills by monotonic one. If we want to provide control over internal solid infill, it would be more clear to make separate GUI controls for this.
Additionally I have fixed issue "Patterntype for Solid and top layer #134"
> Force using of monotonic infill pattern for internal solid infill.

- src/libslic3r/GCodeWriter.cpp
- src/libslic3r/Preset.cpp
- src/libslic3r/Print.cpp
- src/libslic3r/PrintConfig.cpp
- src/libslic3r/PrintConfig.hpp
- src/slic3r/GUI/ConfigManipulation.cpp
- src/slic3r/GUI/Tab.cpp
Add option to automatically adjust accel_to_decel to 50% of chosen acceleration. This option is only displayed when using klipper.
> Option for klipper only: Adjustment of "accel_to_decel"

- src/libslic3r/GCode/GCodeProcessor.cpp
Changed estimated time string in order to be fully compatible with klipper_estimator. Format is now the same as Slic3r, PrusaSlicer and SuperSlicer
> Compatibility with klipper_estimator

- src/slic3r/GUI/Plater.cpp
> fix_compiler_error no viable overloaded '='

- deps/CMakeLists.txt
CMake 3.24 introduces a new policy for managing timestamps on extracted contents of downloaded archives. This change specifies the new behavior should be used for dependencies to eliminate the warning printed when the policy is not set.
> Cleanup DOWNLOAD_EXTRACT_TIMESTAMP warning for CMake 3.24

- build_release_macos.sh
Also emit a diagnostic when neither system is available for the Mac, which will encourage the developer to install one of them (I'm a macports user, not a brew user, but it works either way).
> Make this work with either brew or macports

- src/libslic3r/PrintConfig.cpp
In commit https://github.com/SoftFever/OrcaSlicer/commit/c7dbf848a62b56ea83fa5cc169b961f31d42b979 the default filament color was changed. This reverts that change in order to implement https://github.com/SoftFever/OrcaSlicer/issues/759
> Revert the default filament color change

- src/slic3r/GUI/GCodeViewer.cpp
The BambuStudio color gradient for Flow/Speed etc. (Fuchsia to Sea Serpent) is way less intuitive than the default PrusaSlicer one (Blue to Red).
This reverts that change.
> Original PrusaSlicer gradient for GCodeViewer

- src/libslic3r/GCode.cpp
- src/slic3r/GUI/Field.cpp
- src/slic3r/GUI/MainFrame.cpp
for IDEX printers, It is necessary to check whether the extruder is used in the slice for preheating, nesting and other operations, like:
```
{if is_extruder_used[0]}M104 S{temperature[0]} T0 ;preheat T0{endif}
{if is_extruder_used[1]}M104 S{temperature[1]} T1 ;preheat T1{endif}
```
> Add a new placehoder `is_extruder_used` for IDEX printers

- src/libslic3r/PrintConfig.cpp
- src/slic3r/GUI/Tab.cpp
Minor change to correct double "Fan speedup time" label (now only included in the `Line` object), and add hyphen to "speed-up", which should be the correct spelling.
> Fixed double-label for fan speed-up time, fixed label to include hyphen

- src/libslic3r/PlaceholderParser.cpp
- src/slic3r/GUI/3DBed.cpp
- src/slic3r/GUI/DeviceManager.cpp
- src/slic3r/Utils/TCPConsole.cpp
Fixed some build warnings on deprecated boost headers, unified using correct boost/bind headers, and fixed logical error in `src/slic3r/GUI/DeviceManager.cpp`:
```
this->upgrade_display_state == UpgradingInProgress;
```
should actually be:
```
this->upgrade_display_state = (int)UpgradingDisplayState::UpgradingInProgress;
```
> Fix build warnings, update deprecated boost headers

- src/libslic3r/TreeSupport.cpp
When support line width is set to 0 (automatic), tree supports do not automatically pull the default line width, leaving it at 0.
This causing an exception to be thrown and the application to crash.
This change fixes that.
> Bugfix for zero-width tree supports

- src/libslic3r/Print.cpp
In a multi-head printer, there is no need to check for temperature differneces in the filaments.
However, it is necessary to check if there is a significant difference in bed temperature. Following the prusaslicer, i have provided a warning message for this.
> Fix check multi filament valid

- src/libslic3r/GCodeWriter.cpp
- Always emit the SET_VELOCITY_LIMIT ACCEL=<acceleration> command when the Klipper firmware flavor is selected
- Only append the ACCEL_TO_DECEL parameter if enabled in config
> [BUGFIX] Fix emitting Klipper SET_VELOCITY_LIMIT commands

- src/libslic3r/Model.cpp
- src/libslic3r/calib.hpp
- src/slic3r/GUI/Plater.cpp
As first reported by @FillPavS in #1547:
> I've found a bug. When I create a temperature test, a PA test is added to it
> [...]
> I found out that the error appears after some actions. Here's what you need to do to reproduce-
> 
>     1. Create a PA test and click the slice button.
> 
>     2. Without closing the program, create a new project and do not save anything.
> 
>     3. Create any test - temperature, flow, retract and others.
> 
> 
> Now the PA test will appear with them until you restart the program.
They reported that this happened on Windows 10. This bug doesn't appear on MacOS, though I was able to confirm that the `Model.calib_pa_pattern` was still hanging around in the background there, too.
This PR should fix the bug.
> Fix overly persistent pressure advance pattern

- src/slic3r/GUI/Widgets/StateColor.cpp
wxFAIL will always generate an assert error and does not expect a condition.
> Fix wxWidgets debugging macros

- resources/config.json
Added P1S to config.json, copied from BambuStudio (https://github.com/bambulab/BambuStudio/blob/master/resources/config.json).  
Fixes #1712, as the printer type can now be identified and the filament type select list is populated correctly.
> Add P1S to config.json, copied from BambuStudio.  

- src/libslic3r/TreeSupport.cpp
- src/slic3r/GUI/ConfigManipulation.cpp
This fixes the raft width when normal tree support is enabled
> Fix raft size when non-organic tree support is enabled

- src/libslic3r/PerimeterGenerator.cpp
- src/libslic3r/Preset.cpp
- src/libslic3r/PrintConfig.cpp
- src/libslic3r/PrintConfig.hpp
- src/slic3r/GUI/ConfigManipulation.cpp
- src/slic3r/GUI/Tab.cpp
Regarding #1343, I trying to add the option to enforce min wall width to nozel size on first layer. It should be improve the adhesion in some cases.
Here is an example:
It really hard for these tiny lines attach to bed if you print with infill first.
After it's enabled, it's more like the classical wall generator.
> Add option to enforce first layer min wall width

- src/libslic3r/GCode/GCodeProcessor.cpp
Cherrypicked from https://github.com/prusa3d/PrusaSlicer/commit/abbc99924ef27a3fe5c703c23bd15ec353848d5f
Before:
After:
> Fix GCode viewer first layer height in vase mode

- src/slic3r/GUI/GUI_Preview.cpp
> Fix gcode viewer on linux

- src/libslic3r/Model.hpp
- src/libslic3r/Print.cpp
- src/libslic3r/PrintObject.cpp
- src/libslic3r/Slicing.cpp
- src/libslic3r/Slicing.hpp
- src/libslic3r/Support/SupportCommon.cpp
- src/libslic3r/Support/SupportMaterial.cpp
- src/libslic3r/Support/TreeSupport.cpp
- src/slic3r/GUI/ConfigManipulation.cpp
- Show error message and disable slicing when using organic supports with variable layer height
- Fix crash when using default tree style
- Hide "support critical regions only" option unless non-organic tree support is selected（#2195)
> Various support improvements and bugfixes

- src/slic3r/GUI/ImageGrid.cpp
- src/slic3r/GUI/ImageGrid.h
- src/slic3r/GUI/Plater.cpp
- src/slic3r/GUI/Preferences.cpp
- src/slic3r/Utils/OctoPrint.cpp
This removes the dependency on legacy wxWidgets configurations, and makes OrcaSlicer compile on STL builds.
Also, the wxStringList class has been obsolete for at least 20 years, and disappeared from the documentation.
Replace with wxArrayString.
> Fix compatibility with STL builds of wxWidgets

- src/slic3r/GUI/CalibrationWizardCaliPage.cpp
- src/slic3r/GUI/StatusPanel.cpp
These will not compile on STL builds of wxWidgets. I assume that on the non-STL variants, the first argument is cast to a boolean, which might be a bug…
> GUI: Fix calls to PrintingTaskPanel::show_profile_info

- src/slic3r/GUI/Field.cpp
wxButton->GetBitmap() may return an invalid wxBitmap. Guard against this.
> GUI/Field: Fix crash in color picker init

- resources/profiles/Voxelab/filament/fdm_filament_common.json
The Aquila is an Ender 3 Clone should use the same filament diameter.  
https://github.com/SoftFever/OrcaSlicer/blob/ec90d7f3e4a534157706a263e847ad8ca924809b/resources/profiles/Creality/filament/fdm_filament_common.json#L64
This incorrect size causes cryptic under-extrusion errors for new users.
> Fix filament diameter for Voxelab Aquila to match Creality Ender 3

- src/libslic3r/Preset.cpp
- src/libslic3r/PrintConfig.cpp
- src/libslic3r/PrintConfig.hpp
- src/libslic3r/PrintObject.cpp
- src/libslic3r/PrintObjectSlice.cpp
- src/slic3r/GUI/Tab.cpp
#https://github.com/prusa3d/PrusaSlicer/pull/10976
> Add elephant foot compensation over multiple layers

- src/libslic3r/PerimeterGenerator.cpp
Another PR on the sandwich mode wall ordering bringing it closer to perfection :)
When working on pressure equalizer I noticed an edge case with the inner-outer-inner algorithm where it failed to re-order the perimeters correctly, resulting in a noticeable layer bulge.
This is because a first internal perimeter is extruded before the adjacent external perimeter as seen below. This edge case occurs when an external perimeter is shared between multiple "islands" in the same ordered_extrusions perimeter list. Hence some first internal perimeters were extruded before the external perimeter as they belonged in a separate island.
**Before:**
We can see a bulge in the layer above the front hole bridges. We can also see a further bulges above the front "window".
Looking into the slicer layer view …
> Inner-Outer-Inner mode - additional fix where an external perimeter is shared between multiple islands in the same ordered_extrusions perimeter list

- src/slic3r/GUI/IMSlider.cpp
- src/slic3r/GUI/IMSlider.hpp
#2045
This shows the estimated print time to the hovered layer.
> Show estimated print time in the ruler

- src/slic3r/GUI/IMSlider.cpp
To reproduce:
1. Slice the model.
2. Add a pause in preview.
3. Slice again.
4. Then delete the pause.
5. Notice that the print button is disabled, but the slice button is not enabled.
This PR fixes this issue.
> Fix issue that the slice button is still disabled after a tick is deleted

- src/slic3r/GUI/IMSlider.cpp
This addresses the concern at https://github.com/SoftFever/OrcaSlicer/pull/2305#issuecomment-1745470779
> Show both layer time and tick info when tick is highlighted

- src/libslic3r/PrintConfig.cpp
- src/slic3r/GUI/ConfigManipulation.cpp
add a tooltip to ironing_pattern and hide ironing_pattern when no ironing mode is picked
I don't believe there is a tooltip for ironing_pattern in BBS, but ironing_pattern is hidden when no ironing is selected
> toggle visibility of ironing_pattern on selection of ironing type

- src/libslic3r/GCode.cpp
fixes #2306 where gcode to turn off chamber heating is hardcoded into the slicer. BBS has also removed this line of code in their source.
> Fix M141 S0 at end of gcode

- src/libslic3r/PerimeterGenerator.cpp
- src/libslic3r/PerimeterGenerator.hpp
This fixes #2326 and potentially other performance issues when overhang extra perimeter is turned on for complicated multi-part models.
> Fix issue with overhang-extra-perimeter on complicated multi-part models (#2326)

- src/libslic3r/PrintObject.cpp
The error was introduced as part of the "Extend sparse infill" porting.
Reproduce:
1. Add a cube
2. Set infill pattern to cubic
3. Slice
4. Then change the pattern to adaptive cubic
5. Slice
6. Crash
This PR fixes this issue.
https://github.com/prusa3d/PrusaSlicer/commit/1a0d8f5130559aa57ca7f5a83da7e1e2e3629481#diff-3ec83cd4f72e61c92f69178305a0298e90e2d8b43a3d88ca2f8edccde4e02c7aL709-R736
Not sure why I missed this part during the initial port :P
> Fix crash when switching between different infill patterns

- README.md
- src/libslic3r/Point.hpp
- src/libslic3r/Preset.cpp
- src/libslic3r/Print.hpp
- src/libslic3r/PrintConfig.cpp
- src/libslic3r/PrintConfig.hpp
- src/libslic3r/PrintObject.cpp
- src/libslic3r/PrintObjectSlice.cpp
- src/slic3r/GUI/ConfigManipulation.cpp
- src/slic3r/GUI/Tab.cpp
I've ported automatic polyhole conversion from super slicer.
I'm happy to change the PR as required.
Closes #626
> Ported automatic hole to polyhole conversion from superslicer

- src/slic3r/GUI/GUI_ObjectList.cpp
Partial solution for #2086 (do not close - this PR does not fully fix the issue, it just makes one place better)
This PR focuses on fixing the Object's list text rendering on linux-based OSes. As some people reported, for Linux users with Dark mode enabled, the Object's list renders its text in black-ish color, making it impossible to read. I'm not sure about that in general, but for me at least, switching temporarily to light mode also didn't fix the problem (comparing to other places where that trick does fix the problem, temporarily), as it was rendered all white.
The proposed fix for that is quite simple - for linux platforms, apply the base text color, which then seems to be handled by dark mode color changing as expected.
> Fix object's list text color on Linux (GH-2086)

- src/slic3r/GUI/CalibrationWizardPresetPage.cpp
Reproduce:
1. Connect to a BambuLab printer.
2. Switch to the calibration tab.
3. Crash
Orca does not have `extruder_type` field in printer profile.
> Fix crash on BBL's calibration tab

- src/CMakeLists.txt
- src/libslic3r/CMakeLists.txt
- src/libslic3r/GCode.cpp
- src/libslic3r/GCode/GCodeProcessor.cpp
- src/libslic3r/GCode/Thumbnails.cpp
- src/libslic3r/GCode/Thumbnails.hpp
- src/libslic3r/Preset.cpp
- src/libslic3r/Print.cpp
- src/libslic3r/PrintConfig.cpp
- src/libslic3r/PrintConfig.hpp
- src/qoi/CMakeLists.txt
- src/qoi/README.md
- src/qoi/qoi.h
- src/qoi/qoilib.c
- src/slic3r/GUI/Tab.cpp
First major change is adding the option for thumbnail format under the thumbnail size option. The options ported from PrusaSlicer are PNJ, PJG, and QOI.
Second major change is the addition of the BIQU, or BigTreeTech, image format that is used on their TFTs. Doing this also required a small change to the GCodeProcessor.post_process method that passes through the existing end of line characters
fixes #1894
> Thumbnail Formats Option Ported from PrusaSlicer and add BIQU/BTT format

- src/libslic3r/PrintObjectSlice.cpp
1. Use the project here https://github.com/SoftFever/OrcaSlicer/pull/2382#issuecomment-1763359837
2. Slice
3. Check the bottom layer, which is somehow filled:
This PR fixes this issue:
> Fix layer path order when multi-layer elephant compensation is used

- src/libslic3r/PlaceholderParser.cpp
using the old placeholder parser syntax
> Fix crash when referencing an invalid variable name

- src/libslic3r/GCode.cpp
- src/libslic3r/PrintConfig.cpp
Fixes a few minor issues when handling the "Cooling overhang threshold". Mainly addressed the issue of incorrect fan speed for the internal perimeter when the "Cooling overhang threshold" is set to "0%".
Test model: https://www.printables.com/model/342481-overhang-test-regular
> fix: fix cooling overhang threshold

- src/libslic3r/PrintConfig.cpp
- src/slic3r/GUI/Tab.cpp
As per discord chat - updated tool tip and removed min print speed disabling feature when slow printing down for better layer cooling is de-selected as the min print speed serves as a print speed floor for the filament.
> Updated tool tip and removed min print speed disabling when slowdown for layer cooling is de-selected

- src/slic3r/GUI/Tab.cpp
Just a quick small bug - only lift above and below settings duplicated in the retraction and lift z enforcement section of the extruder settings. This removes the duplicate entry in the retraction section.
> Fix duplicate entry of Only Lift Z above and below in the extruder tab

- src/libslic3r/AppConfig.cpp
- src/slic3r/GUI/GUI_App.cpp
- src/slic3r/GUI/Preferences.cpp
Allows the user to select between the app opening to the default home page or the prepare tab.
> Add default page selection

- src/slic3r/Utils/FixModelByWin10.cpp
(cherry picked from commit prusa3d/PrusaSlicer@04ac99a54e9bc3500dbd32d94d5996798cb894f3)
Currently the slicer freezes if any model part failed to repair. This pr fixes this issue.
> fix deadlock condition varaible use in netfabb wrapper

- src/libslic3r/Support/TreeSupport.cpp
This fixes issue that support blocker produces different results when switching between organic/non-organic tree supports.
Before:
After:
[呼呼呼碳纤维1.zip](https://github.com/SoftFever/OrcaSlicer/files/13248410/1.zip)
> Organic: Fix support blocker

- src/libslic3r/Fill/Fill.cpp
- src/libslic3r/Preset.cpp
- src/libslic3r/PrintConfig.cpp
- src/libslic3r/PrintConfig.hpp
- src/libslic3r/PrintObject.cpp
- src/slic3r/GUI/ConfigManipulation.cpp
- src/slic3r/GUI/Tab.cpp
Partly reverted commit 075a08bca8a033c896c48f2d3612f74ff7a19716
This should fix #2602 and fix #2623
> Add back the option to disable `ensure vertical shell thickness` and `detect narrow internal solid infill`

- resources/profiles/Anker/machine/fdm_machine_common.json
AnkerMake printers use and perform (slightly) better when using Marlin 2 gocde rather then Marlin Legacy gcode.
> Update AnkerMake printers to make use of Marlin 2 gcode

- resources/profiles/Anker/machine/Anker M5.json
- resources/profiles/Anker/machine/Anker M5C.json
- resources/profiles/Anker/machine/fdm_machine_common.json
The previous defaults were only meant for the M5, not the M5c
> Update the retraction defaults to account for the M5c

- src/slic3r/GUI/Gizmos/GLGizmoText.cpp
- src/slic3r/GUI/IMSlider.cpp
This pr fixes the following two issues:
1. text gizmo input dialog caption misalignment  https://github.com/SoftFever/OrcaSlicer/pull/2603#issuecomment-1793690180
2. layer label left edge been cut off on Linux https://github.com/SoftFever/OrcaSlicer/pull/2603#issuecomment-1793816210
Also fixes #2415
> Fix some gui issues

- src/libslic3r/GCode/AvoidCrossingPerimeters.cpp
- src/libslic3r/GCode/AvoidCrossingPerimeters.hpp
This fixes #2621
Before:
After:
These fixes are cherry-picked from PrusaSlicer.
> Fixes scars on thing walls when "avoid crossing wall" is turned on

- src/slic3r/GUI/PartPlate.cpp
Partially fix #2661
The command in #2661 will still not work, due to missing the option `thumbnails_format`. Re-save the project using latest OrcaSlicer might solve that one.
> Fix cli segfault (#2661)

- resources/web/guide/21/21.css
- resources/web/guide/21/21.js
- resources/web/guide/21/index.html
This fixes #2563
Adopted from #2464 by @ZdDroid
> Add search printer model in Setup wizard

- src/libslic3r/Extruder.hpp
- src/libslic3r/GCode.cpp
- src/libslic3r/PrintConfig.hpp
> Fix a regression issue that retraction is not correct when wipe is off

- src/libslic3r/PerimeterGenerator.cpp
> Fix scaling of `min_width_top_surface` when using abs value

- .github/workflows/build_orca.yml
- src/BaseException.cpp
- src/StackWalker.cpp
When we distribute the app to users, it won't come with the PBD file bundled due to the size, which means we will not be able to show the debug symbols (such as function name, source file location, line number etc.) in the crash log. And given the fact that current crash log only shows the virtual address of each function call, it's hard to calculate the RVA of the function which will then be used to locate the function using the PBD file.
This PR shows the section id and the offset within that section for the function address of each stack frame, which then can be used to calculate the function's RVA and also locate the debug symbol in PBD with the help of WinDBG.
The format of the output will be:
`<function virtual address> <section number>:<section offset> <module path>`, and the …
> Improve Windows crash log

- src/libslic3r/GCode/Thumbnails.hpp
Should remedy the issues mentioned in  https://github.com/SoftFever/OrcaSlicer/issues/2741
> Fix for QOI thumbnails not working

- src/slic3r/GUI/GUI_ObjectLayers.cpp
> Fix layer height modifier layout (#2708)

- resources/profiles/Flashforge/process/fdm_process_flashforge_0.20.json
For some reason this value stayed in this profile file after a recent merge and it's now been removed again.
Aligned with [this commit](https://github.com/SoftFever/OrcaSlicer/commit/565732a0278c2b463fb6252a87d6e4662ae7c33f).
@SoftFever - Please merge this PR.
> Removed print_flow_ratio from Flashforge process

- src/slic3r/GUI/GCodeViewer.cpp
- src/slic3r/GUI/ImGuiWrapper.cpp
- src/slic3r/GUI/ImGuiWrapper.hpp
This inserts an overview of all inserted user-specified gcodes, such as the filament change, pause and custom gcodes.
The layer on which the gcode is located is displayed, as well as a time estimate.
If there is no user-specified gcode in the print, nothing is displayed.
Closes: #2191
> Adds overview for custom gcodes like pause, change filament, custom #2191

- src/nanosvg/README.txt
- src/nanosvg/nanosvg.h
- src/nanosvg/nanosvgrast.h
- src/slic3r/GUI/GLTexture.cpp
- src/slic3r/GUI/OpenGLManager.cpp
- src/slic3r/GUI/OpenGLManager.hpp
This should fix #2713
Also fix #2782
cherry picked from commit prusa3d/PrusaSlicer@971f2a08e2758ea1d91e75af9b1443d14b41f895
cherry picked from commit prusa3d/PrusaSlicer@eee4453993ba38f3f11c8f89c56cefa50eaaf74b
> Fix PNG build plate texture not rendering on AMD GPUs

- src/slic3r/GUI/GLCanvas3D.cpp
Currently on windows, when you resize the window relatively small, the end of the toolbar will be clipped like so:
This is what it look like on Linux/macOS:
This PR fixes this issue so it behaves like on Linux/macOS:
> Fix toolbar rendering on Windows

- src/slic3r/GUI/GCodeViewer.cpp
Some changes in the recent measuring gizmo port makes the model semi-transparent shell overlapping the gcode paths and make the lines less clear:
More examples at: https://github.com/SoftFever/OrcaSlicer/pull/2603#issuecomment-1817501192
This pr fixes this issue:
> Fix color blending of preview shells

- src/libslic3r/Fill/Fill.cpp
- src/libslic3r/Layer.hpp
- src/libslic3r/LayerRegion.cpp
- src/libslic3r/Preset.cpp
- src/libslic3r/PrintConfig.cpp
- src/libslic3r/PrintConfig.hpp
- src/libslic3r/PrintObject.cpp
- src/slic3r/GUI/Tab.cpp
Introducing a parameter to adjust the internal bridge flow ratio.
This is the flow ratio used for bridges over sparse infill. Currently it is tied to the bridge flow ratio which on some occasions causes issues. 
For example:
1. Bridge flow ratio increased beyond 1 to get more reliable bridging for regular bridges; however this causes bulging and pillowing on top surfaces as the internal bridges are now over extruded. This is compounded by the fact that the slicer uses the thick bridge logic for all internal bridges which already extrudes more material compared to non thick external bridges.
2. As the internal bridge is always extruded as a thick bridge for reliability purposes, allowing the user to fine tune the flow rate for this internal bridge can help in models with high sparse infill …
> Internal Bridge Flow rate parameter introduction

- src/libslic3r/LayerRegion.cpp
- src/libslic3r/PrintConfig.cpp
- src/libslic3r/PrintObject.cpp
- src/slic3r/GUI/ConfigManipulation.cpp
- src/slic3r/GUI/Tab.cpp
1. Fix issue that sparse infill threshold no longer working
2. Turn all internal sparse infill into solid infill if infill density is 100%
3. Allow combining solid infill when sparse infill density is 100%
4. Move internal solid infill pattern settings into the Infill section
This should fix #2645
> Various infill improvements

- resources/profiles/Flashforge/machine/Flashforge Adventurer 5M 0.4 Nozzle.json
- resources/profiles/Flashforge/machine/Flashforge Adventurer 5M 0.6 Nozzle.json
- resources/profiles/Flashforge/machine/Flashforge Adventurer 5M Pro 0.4 Nozzle.json
- resources/profiles/Flashforge/machine/Flashforge Adventurer 5M Pro 0.6 Nozzle.json
Hi! @SoftFever @mariuske 
Lately we encountered some issues in using Flashforge printers with the Orca1.8.0 version. And some adjustments need to be made to the machine G-code part.
These are the two issues/recommendations while using the Orca 1.8.0 version:
1. The first print after shutting down the system has a problem of not extruding filament. However, the issue does not occur on subsequent prints. Upon investigation, it was found that this version of the software lacks two lines of code in the initial G-code. This issue dates back to the previous commit #2632 .  @mariuske  FYI: These two lines have to be kept as before to solve this issue.
2. Another feedback concerns the pre-extrusion of printers, which occurs on the left and back sides, making it difficult to remove the skirt.  3D …
> Flashforge: Machine G-code Fix

- src/libslic3r/GCode.cpp
Now arc fitting should work properly for internal walls.
Also max volumetric speed won't affect arc fitting results anymore.
Fixed #1257 #1256 #1329 #1257 #1257
> Improve arc fitting when new overhang slowdown is used

- src/libslic3r/GCode/GCodeProcessor.cpp
- src/libslic3r/GCode/GCodeProcessor.hpp
- src/libslic3r/GCodeWriter.cpp
- src/libslic3r/Preset.cpp
- src/libslic3r/Print.cpp
- src/libslic3r/PrintConfig.cpp
- src/libslic3r/PrintConfig.hpp
- src/slic3r/GUI/Tab.cpp
Add option to stop the slicer from emitting any M73 command in gcode, even M73 commands in start/end/custom/etc gcode will be completely removed as well.
Fix #2114
> Add option to disable emitting M73 gcode (#2114)

- src/slic3r/GUI/CreatePresetsDialog.cpp
- src/slic3r/GUI/Tab.cpp
> Dev 1.9 - Fix Spelling Mistake on Create Printer dialog box

- src/slic3r/GUI/GLCanvas3D.cpp
- src/slic3r/GUI/Plater.cpp
1. Make the collapse button smaller
2. Fix button color in dark mode
3. Add tooltip
4. Fix sidebar collapse hotkey
5. Other small bugfixes
> Various fix & improvements to collapse sidebar

- src/libslic3r/MeshBoolean.cpp
Surface_mesh iterators no longer return references, so it's necessary to use const references or copies when iterating.
> Fix build error with CGAL 5.6 with -std=gnu++17 on Fedora

- src/slic3r/GUI/Plater.cpp
Edge case scenario as default line width should always be set but updating the code nonetheless to set some sensible default values when they are missing.
Addresses bug https://github.com/SoftFever/OrcaSlicer/issues/3043
> Updated PA test to address crash when default line width was zero

- resources/profiles/Snapmaker/filament/fdm_filament_common.json
- resources/profiles/Snapmaker/machine/fdm_common.json
The multi-extruder system does not need cooling features. It generates a lot of unnecessary retractions and slow moves  when switching tool heads, which increases the overall printing time.
> Disable the cooling moves for snapmaker printers

- src/libslic3r/Extruder.cpp
When wipe was enabled it results in a zero length retract after the wipe is performed. This results in a no-op in the Extruder::retract and also means that the m_restart_extra was not set after the wipe command. That resulted in the next de-retraction having a 0 restart extra length.
Bambu is working around this issue by wiping 95% of the retraction and then doing a small retraction, which sets the restart extra length value as seen here:
I am 50-50 whether this change will introduce any regressions, so would appreciate a code review if possible?
> Fix #2662 - "Extra length on restart" setting is ignored when wipe is enabled

- doc/air-filtration.md
The SPEED parameter of SET_FAN_SPEED needs to be between 0.0  and 1.0. Since the S param, which is between 0 and 255, was being passed as is to SPEED, it effectively resulted in the target fan running at 100% if any value > 0 was passed to M106.
> Fix value passed to SPEED in air-filteration.md macro.

- src/slic3r/GUI/GLCanvas3D.cpp
- src/slic3r/GUI/Plater.cpp
This fixes issue that the sidebar is missing if slicer is opened with command line arg, includes:
- Open 3mf file with file association
- Drag & drop 3mf file to slicer executable
- Run slicer from terminal with file path parameter
- Other similar situation that will pass a file path in main function parameter
> Fix sidebar not shown when open 3mf file from command line arg

- src/slic3r/GUI/Plater.cpp
1. Fixes issue https://github.com/SoftFever/OrcaSlicer/pull/3172#issuecomment-1862396619
2. Retain sidebar size when switching between prepare/preview tab and other tabs
> Another sidebar improvement PR

- resources/profiles/Creality/machine/Creality Ender-3 V3 KE.json
- resources/profiles/Creality/machine/Creality Ender-3 V3 SE.json
As requested, here is the fix for default materials listing of Ender 3 V3 printers.
> Fixed Ender 3 V3's default materials

- src/slic3r/GUI/Plater.cpp
- src/slic3r/Utils/CalibUtils.cpp
VFA Test has a bug where it would not run the vase mode algorithm if the user had the detect thin walls parameter selected.
This PR fixes this by deselecting the parameter in the calibration methods.
Softfever, I promise that's all from me this week :D
> Bug fix: VFA Test fix

- src/slic3r/GUI/GUI_App.cpp
Now the logs are generated under the log folder, just like what BBS does:
Fixes #3209
> Fix tutk logs location (#3209)

- src/slic3r/GUI/GCodeViewer.cpp
Fix issue that the legend window expands to all available horizontal space if scrollbar is displayed:
> Fix preview legend window size

- README.md
An update to your readme.  Personally I prefer to install redistributable runtimes from the source rather than self hosted.  Thus I included alternative download links to Microsoft.
Additionally, I know the bash script installs the depends in Linux but I included those.
I also added some notes to the windows build instructions to provide convenience.
> Update README.md to provide alternative download links of webview2 runtimes

- resources/profiles/Elegoo/machine/Elegoo Neptune 4 (0.2 nozzle).json
- resources/profiles/Elegoo/machine/Elegoo Neptune 4 (0.4 nozzle).json
- resources/profiles/Elegoo/machine/Elegoo Neptune 4 (0.6 nozzle).json
- resources/profiles/Elegoo/machine/Elegoo Neptune 4 (0.8 nozzle).json
- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Max (0.2 nozzle).json
- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Max (0.4 nozzle).json
- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Max (0.6 nozzle).json
- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Max (0.8 nozzle).json
- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Plus (0.2 nozzle).json
- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Plus (0.4 nozzle).json
- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Plus (0.6 nozzle).json
- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Plus (0.8 nozzle).json
- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Pro (0.2 nozzle).json
- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Pro (0.4 nozzle).json
- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Pro (0.6 nozzle).json
- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Pro (0.8 nozzle).json
- resources/profiles/Elegoo/machine/Elegoo Neptune X 0.4 nozzle.json
The Elegoo Neptune 4 series correctly implements PAUSE command in order to use it directly as change_filament_gcode.
So I suggest using it as the default command for that action.
The users are free to change it anyway, but for newbies, it will be easier to use.
> Added PAUSE command for change_filament_gcode on Elegoo Neptune 4 series

- src/slic3r/GUI/GLCanvas3D.cpp
- src/slic3r/GUI/Gizmos/GLGizmosManager.cpp
- src/slic3r/GUI/KBShortcutsDialog.cpp
- Bring back the shortcut to zoom in & out, this helps when mouse scroll wheel is not usable.
- Fix emboss gizmo shortcut
> QoL: Keyboard shortcuts updates & fixes

- resources/profiles/Creality/machine/Creality CR-10 Max 0.4 nozzle.json
- resources/profiles/Creality/machine/Creality CR-10 V2 0.4 nozzle.json
- resources/profiles/Creality/machine/Creality CR-6 Max 0.2 nozzle.json
- resources/profiles/Creality/machine/Creality CR-6 Max 0.4 nozzle.json
- resources/profiles/Creality/machine/Creality CR-6 Max 0.6 nozzle.json
- resources/profiles/Creality/machine/Creality CR-6 Max 0.8 nozzle.json
- resources/profiles/Creality/machine/Creality CR-6 SE 0.2 nozzle.json
- resources/profiles/Creality/machine/Creality CR-6 SE 0.4 nozzle.json
- resources/profiles/Creality/machine/Creality CR-6 SE 0.6 nozzle.json
- resources/profiles/Creality/machine/Creality CR-6 SE 0.8 nozzle.json
- resources/profiles/Creality/machine/Creality Ender-3 0.4 nozzle.json
- resources/profiles/Creality/machine/Creality Ender-3 S1 0.4 nozzle.json
- resources/profiles/Creality/machine/Creality Ender-3 S1 Pro 0.4 nozzle.json
- resources/profiles/Creality/machine/Creality Ender-3 V2 0.4 nozzle.json
An option has been added with A1 printers from BBL, it's called "printer_structure".
When it is set to "i3", that option automatically ticks the box to align parts on Y axis in order to improve quality.
I added this parameter to every i3 printers from Creality.
> Added i3 printer_structure to Creality printers

- src/slic3r/GUI/OptionsGroup.cpp
Percent config values are managed as float types, but decimal precision is not displayed in the GUI. This change uses the `double_to_string()` converstion rather than casting to an int when retrieving the config option value.
I noticed this specifically when fine tuning the infill density for some large weight sensitive prints and the decimal values were lost each time the field was redisplayed in the GUI. The confusing thing was the correct precision value was still being used for all slicing calculations.
> Display accurate precision for percent config values

- resources/images/camera_switch.svg
- resources/images/camera_switch_dark.svg
- src/slic3r/GUI/CameraPopup.cpp
- src/slic3r/GUI/CameraPopup.hpp
- src/slic3r/GUI/StatusPanel.cpp
- src/slic3r/GUI/StatusPanel.hpp
This allows adding a custom IP camera source from the camera settings popup. Camera stream is shown in a WebView widget with native controls and possible scrollbars stripped away. Original bambulab camera also remains functional if one exists, and a button is added to toggle between them.
Tested on Windows with Bambu Lab P1S.
Demo:
> Support custom IP camera

- resources/profiles/Anker/process/fdm_process_common.json
Correct support_base_pattern to not cause import failure when adding an Anker printer
> Default Anker support_base_pattern (Fixes #3326)

- src/libslic3r/Fill/Lightning/Generator.cpp
Fixes #3567.
Firstly attempt to set it to the default line width. If that is not provided either, set it to a sane default based on the nozzle diameter.
> [Bug fix] Fixes lightning infill with sparse infill width set to 0 causes "divide by zero" fatal error

- src/libslic3r/GCode/SpiralVase.cpp
Fixes #3603 
Before:
After
Before
After:
> [Bug fix] Fixes retraction on layer change being performed when retract travel threshold is set to 0

- src/slic3r/GUI/Gizmos/GLGizmoPainterBase.cpp
Fixes #3395
Fixes #3487
Also fixes an issue that seam & support painting gizmo render improperly when wireframe is enabled:
The wireframe is displayed properly in MMU gizmo:
But looks like this when switching to seam/support gizmo:
> Fix painting Gizmo rendering on AMD Vega GPUs

- src/slic3r/GUI/Plater.cpp
Keep the sidebar width between reopening the app, and between hidding & showing the sidebar, and between docking & undocking it.
> Remember the sidebar size

- localization/i18n/OrcaSlicer.pot
- localization/i18n/en/OrcaSlicer_en.po
- localization/i18n/hu/OrcaSlicer_hu.po
- localization/i18n/ja/OrcaSlicer_ja.po
- localization/i18n/nl/OrcaSlicer_nl.po
- localization/i18n/sv/OrcaSlicer_sv.po
- src/slic3r/GUI/CreatePresetsDialog.cpp
> Fixes #3721 - Typo in lang files

- src/libslic3r/Print.cpp
IDEX printers(Snapmaker J1 / Raise3D E2) allow printing with different types of filaments.
But OrcaSlicer only support `single extruder multi material` so i use the number of nozzles.
> Don't check the temperature of multi filament for multi toolhead printers

- src/slic3r/GUI/PartPlate.cpp
- src/slic3r/GUI/PartPlate.hpp
> Add plate name edit btn

- src/libslic3r/GCode.cpp
BBL has printing by object Gcode disabled. This just re enables it. Fixes #2593
> Re-enable printing by object gcode

- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Pro (0.2 nozzle).json
- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Pro (0.4 nozzle).json
- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Pro (0.6 nozzle).json
- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Pro (0.8 nozzle).json
This PR corrects the Neptune 4 Pro's `printable_area`.
I was printing some drawer divider bins that pushed right up to the limits of the N4P's build plate size.  These adjustments were required to prevent the printer from printing into voids or encountering firmware-imposed limits on bed travel.
These are the issues I encountered:
- The build plate is 235mm wide, not 225 mm wide.  
- This discrepancy results objects being printed left of where is expected, and renders space on the right side of the build plate unreachable / unusable.
- This isn't a big deal compared to the Y-Coordinate issues.
- On the N4P, `0x0` is not on the usable build plate area.
- `y=0` is in the center of the build plate's easy-remove tab.
- It's OK to print the priming strip near `115x0`, but it isn't OK to let …
> corrected printable_area

- src/libslic3r/GCode/GCodeProcessor.cpp
- src/libslic3r/GCode/GCodeProcessor.hpp
The `config.filament_load_time.values` and `config.filament_unload_time.values` are completely ignored. This was working in PrusaSlicer and apparently BBS converted the `GCodeProcessor::TimeProcessor.filament_load_times` and `GCodeProcessor::TimeProcessor.filament_unload_times` from being `std::vector<float>` to just `float` and they were using the BBS specific and currently hidden `machine_load_filament_time` and `machine_unload_filament_time` config values. Reverted that change by copying those lines from PrusaSlicer.
> Fix #3311: filament Load / Unload time was not used in time estimation

- resources/profiles/Anker/filament/Anker Generic ABS.json
- resources/profiles/Anker/filament/Anker Generic ASA.json
- resources/profiles/Anker/filament/Anker Generic PA-CF.json
- resources/profiles/Anker/filament/Anker Generic PA.json
- resources/profiles/Anker/filament/Anker Generic PC.json
- resources/profiles/Anker/filament/Anker Generic PETG-CF.json
- resources/profiles/Anker/filament/Anker Generic PETG.json
- resources/profiles/Anker/filament/Anker Generic PLA Silk.json
- resources/profiles/Anker/filament/Anker Generic PLA+.json
- resources/profiles/Anker/filament/Anker Generic PLA-CF.json
- resources/profiles/Anker/filament/Anker Generic PLA.json
- resources/profiles/Anker/filament/Anker Generic PVA.json
- resources/profiles/Anker/filament/Anker Generic TPU.json
- resources/profiles/Anker/process/fdm_process_anker_common.json
Previous PR ( https://github.com/SoftFever/OrcaSlicer/pull/3845 ) has an error with the M5c profiles that will cause it to break filament and process profiles for existing users. This PR corrects that error.
> Fixes Anker M5C profiles

- src/libslic3r/GCode.cpp
I received feedback that stringing has slightly worsened in some cases since version 1.9. After investigating and testing, it turns out that this issue occurs when `retract amount before wipe` is set to 0. This is because, after restricting the retraction speed during the wipe, Orca tends to perform a large amount of retraction after the wipe is completed in this scenario. This, to some degree, defeats the purpose of the wipe.
Before the fix:  
After the fix:  
@igiannakas
> Enforce retraction before wipe

- src/libslic3r/Model.hpp
Partly revert 73ab032e8288cbcadfe41691c590561a469b57f9
Fix https://github.com/SoftFever/OrcaSlicer/pull/3890#issuecomment-1916792002
> Fix issue with auto orient a scaled object.

- src/libslic3r/GCode.cpp
Thank Gina Häußge for reporting the issue.
> Security: skip writing print_host and apikey in gcode

- src/slic3r/GUI/HMS.cpp
The default 'en' language for HMS errors has been added for the Polish language. Nevertheless, the optimal solution would be to allow disabling updates for languages that are not supported on the BambuLab server and retain only local reading
> Update HMS.cpp set language code to en by default for PL language

- resources/profiles/Creality/machine/Creality Ender-3 V3 SE 0.4 nozzle.json
Fixing the present print to move the bed forward, not backwards.
Example from Cura:
> Creality Ender-3 V3 SE: Fix present print

- resources/profiles/Creality.json
It looks like a regression has been introduced in https://github.com/SoftFever/OrcaSlicer/commit/31d1d03578398e5de1f5e173548b5a83e23d7553
"0.20mm Standard @Creality K1Max (0.4 nozzle)" is loaded twice, this PR should fix the issue.
And then fix #4047
> Fix for #4047

- resources/profiles/Creality/filament/Creality Generic TPU.json
- resources/profiles/Creality/machine/Creality Ender-3 0.2 nozzle.json
- resources/profiles/Creality/machine/Creality Ender-3 0.4 nozzle.json
- resources/profiles/Creality/machine/Creality Ender-3 0.6 nozzle.json
- resources/profiles/Creality/machine/Creality Ender-3 0.8 nozzle.json
A regression has been introduced in https://github.com/SoftFever/OrcaSlicer/commit/31d1d03578398e5de1f5e173548b5a83e23d7553
Should fix #4087 
I also added missing "i3" printer_structure
> Fixed Ender 3 profile inheritance

- src/libslic3r/GCode/PostProcessor.cpp
If `$SHELL` is not defined on unix, setting postprocessing scripts errors with `execve failed: No such file or directory`.
A workaround is to make sure that `$SHELL` is set to the full path to a shell. The issue is that `execv`, used to execute postprocessing scripts, requires the full path to an executable as it doesn't seem to take `$PATH` into account.
Copied from https://github.com/prusa3d/PrusaSlicer/commit/87a51165f321f0f4853ed5d6f76108e0073c12ba
> Fix for postprocessing scripts not working on UNIX when $SHELL is undefined

- src/slic3r/GUI/Gizmos/GizmoObjectManipulation.cpp
> Fix move gizmo on parts

- resources/profiles/TwoTrees.json
- resources/profiles/TwoTrees/filament/TwoTrees Generic PETG @SK1.json
- resources/profiles/TwoTrees/filament/TwoTrees Generic PLA Matte @SK1.json
- resources/profiles/TwoTrees/filament/TwoTrees Generic PLA Silk @SK1.json
- resources/profiles/TwoTrees/filament/TwoTrees Generic PLA-CF @SK1.json
- resources/profiles/TwoTrees/machine/TwoTrees SK1.json
- src/slic3r/GUI/Gizmos/GizmoObjectManipulation.cpp
Profile changes for TwoTrees SK1 : 
- New filament : PLA Matte
- Changed flow rate for PLA-CF, PLA Silk and PETG
> TwoTrees SK1 Profiles : New filament (PLA Matte) and tuned volumetric flow rates

- src/libslic3r/Layer.cpp
- src/libslic3r/PerimeterGenerator.cpp
- src/libslic3r/Preset.cpp
- src/libslic3r/PrintConfig.cpp
- src/libslic3r/PrintConfig.hpp
- src/libslic3r/PrintObject.cpp
- src/slic3r/GUI/ConfigManipulation.cpp
- src/slic3r/GUI/Tab.cpp
Add an option "wall direction", which allows you to change the wall direction per-part/object/layer.
Might be useful if you have parts that printed upside down and you want a unified surface appearance when assembled.
> Allow specify wall directions

- src/libslic3r/GCode.cpp
- src/libslic3r/Preset.cpp
- src/libslic3r/PrintConfig.cpp
- src/libslic3r/PrintConfig.hpp
- src/libslic3r/PrintObject.cpp
- src/slic3r/GUI/Tab.cpp
This will enable Orca Slicer users to call adaptive bed meshes directly in the Machine Start G-code without the need to install any plugins or modify the firmware settings.
Marlin:
```
G29 X{bed_mesh_probe_count[0]} Y{bed_mesh_probe_count[1]} L{adaptive_bed_mesh_min[0]} R{adaptive_bed_mesh_max[0]} F{adaptive_bed_mesh_min[1]} B{adaptive_bed_mesh_max[1]} T V4
```
Klipper:
```
; Always pass `ADAPTIVE_MARGIN=0` because Orca has already handled `adaptive_bed_mesh_margin` internally
BED_MESH_CALIBRATE mesh_min={adaptive_bed_mesh_min[0]},{adaptive_bed_mesh_min[1]} mesh_max={adaptive_bed_mesh_max[0]},{adaptive_bed_mesh_max[1]} ALGORITHM=[bed_mesh_algo] PROBE_COUNT={bed_mesh_probe_count[0]},{bed_mesh_probe_count[1]} ADAPTIVE=1 ADAPTIVE_MARGIN=[adaptive_bed_mesh_margin]
```
RRF:
```
M557 …
```
> Add direct adaptive bed mesh support

- src/slic3r/GUI/CreatePresetsDialog.cpp
- src/slic3r/GUI/CreatePresetsDialog.hpp
Though I haven't tested this thoughly, there is a risk that the exported profile can't be imported etc (otherwise why did BBL disable this?).
> Allow exporting filament profiles for non-bbl printers

- src/CMakeLists.txt
- src/imguizmo/CMakeLists.txt
- src/imguizmo/ImGuizmo.cpp
- src/imguizmo/ImGuizmo.h
- src/imguizmo/LICENSE
- src/imguizmo/README.md
- src/libslic3r/AppConfig.cpp
- src/slic3r/CMakeLists.txt
- src/slic3r/GUI/AboutDialog.cpp
- src/slic3r/GUI/Camera.cpp
- src/slic3r/GUI/Camera.hpp
- src/slic3r/GUI/GLCanvas3D.cpp
- src/slic3r/GUI/GLCanvas3D.hpp
- src/slic3r/GUI/GUI_App.hpp
- src/slic3r/GUI/MainFrame.cpp
Initial work on adding a 3D navigator gizmo. Build on top of the amazing https://github.com/CedricGuillemet/ImGuizmo library by @CedricGuillemet.
Todos:
> QoL: 3D navigator

- src/libslic3r/PrintConfig.cpp
- src/libslic3r/PrintConfig.hpp
- src/slic3r/CMakeLists.txt
- src/slic3r/GUI/PhysicalPrinterDialog.cpp
- src/slic3r/GUI/PhysicalPrinterDialog.hpp
- src/slic3r/GUI/PrinterCloudAuthDialog.cpp
- src/slic3r/GUI/PrinterCloudAuthDialog.hpp
- src/slic3r/Utils/Obico.cpp
- src/slic3r/Utils/Obico.hpp
- src/slic3r/Utils/PrintHost.cpp
- src/slic3r/Utils/PrintHost.hpp
My apologies for this huge PR. We tried pretty hard to encapsulate the bulk of the functions in files specific to Obico.
This PR is to add a PrintHost for Obico so that the user can connect to Obico cloud in OrcaSlicer, as well as to directly manage the cloud printer on the "Device" tab.
We tried to stick to existing convention that is consistent with other options such as OctoPrint. The only new concept we introduced was `PrintHost.is_cloud`. If the printHost is cloud, the "Test" button will open a webview to prompt login.
The handshake to automatically retrieve an auth token after the user has logged in is in PrinterCloudAuthDialog. We wrote and tested it based on the Obico cloud. But we tried to keep it generic.
The bulk of Obico-specific logics are encapsulated in Obico.cpp. Some bled …
> Support for Obico cloud integration

- build_release_macos.sh
Fixes issue raised here https://github.com/SoftFever/OrcaSlicer/pull/4310#issuecomment-1981475541
Before I wrongfully assumed that default CMake generator for both deps and slicer is Xcode.
This is not true, as deps used implicitly-defaulted Unix Makefiles. Fix by separating generator used for Slicer and deps, leaving the choice to use Ninja for both.
Right now Xcode generator is not supported for deps and must be fixed separately.
> FIX: revert default CMake generator for deps on macOS

- CMakeLists.txt
- deps/TIFF/TIFF.cmake
Downgrade `enum-constexpr-conversion` error to warning.
Explicitly disable `libdeflate support` in `TIFF` depencency.
[PrusaSlicer already does that](https://github.com/prusa3d/PrusaSlicer/blob/4f035bceb75661719b23d13fceddc62ccab6c54e/deps/%2BTIFF/TIFF.cmake#L12)
Signed-off-by: Dzmitry Neviadomski <nevack.d@gmail.com>
> FIX: Support building with latest Xcode 15.3

- src/libslic3r/GCode/PressureEqualizer.cpp
- src/libslic3r/GCode/PressureEqualizer.hpp
- src/slic3r/GUI/Plater.cpp
The regression is introduced when we allow apply "Extrusion rate smoothing" on vase mode in #4264 
Specifically, at the transition point from normal printing to vase mode, the volumetric_extrusion_rate_end becomes significantly smaller than volumetric_extrusion_rate_start. This discrepancy can cause a feed rate of 0 if the extrusion rate smoothing value is set too low.
_image from Discord member: NigelTufnel_
> fix an issue that pressure eq may cause 0 feedrate in vase mode

- src/libslic3r/Preset.cpp
- src/libslic3r/PrintConfig.cpp
- src/libslic3r/PrintConfig.hpp
- src/libslic3r/PrintObject.cpp
- src/slic3r/GUI/ConfigManipulation.cpp
- src/slic3r/GUI/Tab.cpp
The previous user experience was somewhat confusing, particularly with the settings for ensure_vertical_shell_thickness and reduce_wall_solid_infill.
This PR improves the UI and refines the functionality of these options:
1. Changed ensure_vertical_shell_thickness to an enum value type to simplify selection and improve clarity.
2. Introduced an option to completely disable this feature, giving users more control over their printing preferences.
@igiannakas FYI. The 'Critical Only" is same as this combination you added in this PR #3235.
> Optimize ensure vertical feature's UX

- src/libslic3r/Print.cpp
> UX: check and warn users if print speed/accel/jerk are higher than the machine limits

- deps/wxWidgets/wxWidgets.cmake
The reason to do this is that wxWidgets repo is pretty large, so initial clone can take a lot of time and disk space.
~~The only caveat is that building for Windows requires different tarball because of configured line endings as stated in docs.~~
~~You may find this controversial, but I don't see any downsides right now.~~
~~The only thing to be checked is that applying patches works correctly.~~
UPD: Switched to shallow git clone.
> ENH: Switch wxWidgets dep to a shallow git clone. 

- src/CMakeLists.txt
- src/slic3r/GUI/AboutDialog.cpp
Also remove duplicated definition for `MACOSX_BUNDLE_COPYRIGHT`.
Mainly affects About dialog.
I decided to check it in 2.0.0 beta, and found it surprising that the year was not yet updated :smile:
@SoftFever I think you may want it to be merged before 2.0.0 final release.
> chore(slicer): Update copyright year to 2024

- src/platform/unix/build_appimage.sh.in
AppImageTool no longer hardcoded to _x86_64_ to allow generation of AppImage files on _aarch64_ build hosts
> Allow AppImage generation in aarch64 build hosts

- resources/web/data/text.js
- resources/web/model/index.html
The string 'no model information' has been added for translation. It is available as 'orca2' in text.js.
> Added a string 'no model information' for translation

- resources/profiles/Qidi/process/fdm_process_qidi_x3_common.json
Hi,
I faced an issue with the Qidi profile, the "detect_thin_wall" feature is disabled.
This caused bad extrusion for some parts of ERCFv2 that have supports integrated, like this part : 
Without thin walls detection : 
With thin walls detection : 
@Hukete I mention to check if you agree with this change
> Enable detect_thin_wall for Qidi printers

- src/libslic3r/PrintObject.cpp
Reverting the automatic application of reduced infill bridge filtering for lightning infill introduced in this PR https://github.com/SoftFever/OrcaSlicer/pull/3319 as:
1. this is now a user option anyway and 
2. I've found it created too many bridges when printing with a 0.25 nozzle and lightning infill on some models.
> Revert automatic application of reduced internal bridge filtering for lightning infill

- src/slic3r/GUI/Gizmos/GLGizmoPainterBase.cpp
Fix this issue:
https://github.com/SoftFever/OrcaSlicer/assets/1537155/de9d8a33-807b-49a9-bd2e-34701a7fab4c
> Fix issue that painter sphere is rendered at the wrong position

- src/libslic3r/PrintObject.cpp
Fixed a regression bug that top surface was mistaken as bridge.
To produce this bug, just set thick top shell layer when slicing Orca cube
Fixes #4648
@igiannakas 
I reverted this part of the change. I tested the case you mentioned, it seems fine too
https://github.com/SoftFever/OrcaSlicer/pull/3285#discussion_r1444632150
> Wrong bridge detection result

- src/libslic3r/GCode.cpp
- src/libslic3r/GCode/SeamPlacer.cpp
- src/libslic3r/GCode/SeamPlacer.hpp
- src/libslic3r/Layer.cpp
- src/libslic3r/Preset.cpp
- src/libslic3r/PrintConfig.cpp
- src/libslic3r/PrintConfig.hpp
- src/libslic3r/PrintObject.cpp
- src/slic3r/GUI/ConfigManipulation.cpp
- src/slic3r/GUI/Tab.cpp
I didn't originally plan to add this feature to 2.0 as I wanted to do some more tests.
However, it turns out I don't have time to do more testing, so I will release it for more people to test.
> Add overhang threshold for scarf joint seam

- src/slic3r/GUI/PhysicalPrinterDialog.cpp
after switching from certain host type
> Fix issue that print host and webui settings are not properly reset

- src/slic3r/GUI/HttpServer.cpp
- src/slic3r/GUI/HttpServer.hpp
- src/slic3r/GUI/Jobs/OAuthJob.cpp
Caused by use-after-free error.
And some minor improvements to the OAuth components.
> Fix 3rd party login issue on macOS

- src/slic3r/GUI/RemovableDriveManager.cpp
Removable media is not ejected on linux platform
Make get_removable_drive_from_path() check if path is a dir or not. Trim last component in latter case only.
> gui: fix media eject on linux (#4700)

- src/libslic3r/calib.cpp
- src/libslic3r/calib.hpp
Printer z offset is not accounted for in the line and pattern pressure advance calibration gcode generators.
Tested with positive and negative z offsets.
> Add z offset to pressure advance calibration (line and pattern)

- src/OrcaSlicer.cpp
- src/libslic3r/GCode.cpp
- src/slic3r/GUI/PartPlate.cpp
Fixes: #1194
Changes:
- Replaced `extruder_clearance_max_radius` with `extruder_clearance_radius` to resolve the CLI error
- Add `if (m_plater)` before accessing preset_bundle in `generate_logo_polygon` and before `generate_plate_name_texture`
- Add thumbnails to export only if thumbnail callback is defined
> Fix segmentation fault when running CLI

- src/slic3r/GUI/IMSlider.cpp
"Jump to Layer" popup is not shown neither by Shift+G nor by pressing context menu.
This change fixes that bad behavior.
> Fix go-to-layer dialog in gcode preview

- src/libslic3r/PrintObject.cpp
Quick and dirty.
Haven't got time to dive deep to the original code logic yet.
Initial testing result seems fine.
@igiannakas 
[OrcaCube.zip](https://github.com/SoftFever/OrcaSlicer/files/14735411/OrcaCube.zip)
> Wrong bridge detection result (FOR TESTING ONLY)

- src/slic3r/GUI/GUI_Factories.cpp
Show the actual filament labels in the "Change Filament" context menu instead of "Filament 1", "Filament 2", etc.
This makes it much quicker to tell what filament is being selected, especially when utilizing the "sync from AMS" button with a printer with several AMS units attached.
**This is not yet tested** due to https://github.com/SoftFever/OrcaSlicer/issues/4920, but the [corresponding PR I opened against Bambu Studio](https://github.com/bambulab/BambuStudio/pull/3830) has been tested and works fine - both in the main view (which uses `append_menu_item_change_filament`) and in the assemble view (which uses `append_menu_item_change_extruder`), as well as with both built-in filament profiles and with user- and project-custom filament profiles.
> Display filament labels in "change filament" context menus

- src/slic3r/GUI/GLCanvas3D.cpp
Plater disappeared when zoom-to-mouse enabled and user tries to zoom
with a side view enabled (Ctrl+<3..6>).
Mouse/screen center position estimation in 3D is made by calculating
intersection of a mouse vector which comes 'through' the screen with an
XY plane. However, when screen is parallel to Z axis, intersection point
located at infinite which results in infinite camera translation vector.
This change switches mouse position estimation to use of projection
matrix like its done for camera panning.
Fixes #4797, #4579, #3615
> gui: fix zoom-to-mouse 

- localization/i18n/OrcaSlicer.pot
- localization/i18n/ca/OrcaSlicer_ca.po
- localization/i18n/cs/OrcaSlicer_cs.po
- localization/i18n/de/OrcaSlicer_de.po
- localization/i18n/en/OrcaSlicer_en.po
- localization/i18n/es/OrcaSlicer_es.po
- localization/i18n/fr/OrcaSlicer_fr.po
- localization/i18n/hu/OrcaSlicer_hu.po
- localization/i18n/it/OrcaSlicer_it.po
- localization/i18n/ja/OrcaSlicer_ja.po
- localization/i18n/ko/OrcaSlicer_ko.po
- localization/i18n/nl/OrcaSlicer_nl.po
- localization/i18n/pl/OrcaSlicer_pl.po
- localization/i18n/ru/OrcaSlicer_ru.po
- localization/i18n/sv/OrcaSlicer_sv.po
- localization/i18n/tr/OrcaSlicer_tr.po
- localization/i18n/uk/OrcaSlicer_uk.po
- localization/i18n/zh_CN/OrcaSlicer_zh_CN.po
- localization/i18n/zh_TW/OrcaSlicer_zh_TW.po
Correct typo.  Existing text states **transver** and should be **transfer**
Before:
After:
Built and ran the code on Arch Linux.
> correct typo: transver vs transfer

- .github/workflows/build_deps.yml
- .github/workflows/build_orca.yml
- .github/workflows/publish_docs_to_wiki.yml
Allow workflow to be run by developers locally through [act](https://github.com/nektos/act)
Before:
```
[Build Deps/build_deps.yml/Build Deps]   ✅  Success - Main Build on Ubuntu
[Build Deps/build_deps.yml/Build Deps] ⭐ Run Main Upload Ubuntu artifacts
[Build Deps/build_deps.yml/Build Deps]   🐳  docker cp src=/home/jamin/.cache/act/actions-upload-artifact@v4/ dst=/var/run/act/actions/actions-upload-artifact@v4/
[Build Deps/build_deps.yml/Build Deps]   🐳  docker exec cmd=[node /var/run/act/actions/actions-upload-artifact@v4/dist/upload/index.js] user= workdir=
[Build Deps/build_deps.yml/Build Deps]   💬  ::debug::followSymbolicLinks 'true'
[Build Deps/build_deps.yml/Build Deps]   💬  ::debug::implicitDescendants 'true'
[Build Deps/build_deps.yml/Build Deps]   💬 …
```
> Act adjustments

- src/libslic3r/PrintConfig.cpp
adding units to the input field for the filter_out_gap_fill float for better comprehension and consistency
> Adding units [mm] for filter_out_gap_fill in PrintConfig.cpp

- src/slic3r/GUI/GUI_ObjectList.cpp
• Add cube
• Add SVG as Positive/Negative/Modifier
• Right click SVG on object list
Normally it should show "Edit SVG" for this item like "Edit Text" but not. this commit fixes it
Left (fixed) - Right shows generic menu
> Add missing "Edit SVG" item for Add/Negative/Modifier SVG objects in object list

- src/slic3r/GUI/GUI_ObjectList.cpp
Orca crashes >
• add cube 
• add SVG / TEXT as positive / negative / modifier
• select it and change its type to support enforcer / blocker
I removed them from dropdown menu but its many not be real solution if we want to allow them as support enforcer / blocker
Problem can be at code of support enforcer / blocker
Also there is no SVG / TEXT menu item on context menu support enforcer / blocker
> Fix crash when changing type of SVG / TEXT modifier

- resources/profiles/Anycubic/machine/Anycubic Kobra 2 0.4 nozzle.json
The correct value is undefine.
Related to a comment in https://github.com/SoftFever/OrcaSlicer/issues/3991#issuecomment-2079796653
Filament loading will crash if this value is `undefined` instead of `undefine`.
```text
[error]	2024-04-26 19:34:05.440249[Thread 0x00003784]:Slic3r::ConfigBase::load_from_json: parse C:\Users\Kristian\AppData\Roaming\OrcaSlicer\system/Anycubic/machine/Anycubic Kobra 2 0.4 nozzle.json got a generic exception, reason = Invalid value provided for parameter nozzle_type: undefined
[error]	2024-04-26 19:34:05.440249[Thread 0x00003784]:Slic3r::PresetBundle::load_vendor_configs_from_json::<lambda_2e6da75a0232aea84d16ba067e6fa242>::operator (): load config file C:\Users\Kristian\AppData\Roaming\OrcaSlicer\system/Anycubic/machine/Anycubic Kobra 2 0.4 nozzle.json …
```
> Fix invalid nozzle_type undefined for 'Anycubic Kobra 2 0.4 nozzle' system machine

- resources/profiles/Qidi/machine/Qidi X-Max 0.4 nozzle.json
- resources/profiles/Qidi/machine/Qidi X-Plus 0.4 nozzle.json
The current start G-Code for Qidi X-Max 1/2 and X-Plus 1/2 will start printing before the first-layer temperature is reached.
Resulting is usually a big blog of filament on the nozzle and failed print.
This PR will add the original g-code for setting start temperature (M109 and M190) and the printer will wait until temperature is reached.
Reference full (original) Qidi start code for a X-Plus printer setting bed temp to 63 and nozzle to 215
```
M82 ;absolute extrusion mode
G28
G0 X270 Y5 Z50 F3600
M190 S63
M109 S215.0
G92 E-16
G0 Y5 Z0.3 F3600
G1 X5 E0 F2400
```
Tested and works.
> Adjusted start g-code for Qidi X-Max/X-Plus 1 and 2.

- DockerRun.sh
- Dockerfile
DockerBuild.sh was failing on dependencies, masked by exit 0. Cause was the addition of an autoreconf to the MPFR cmake, requires libtool which was missing from the package install in the Dockerfile.
Added --rm to DockerRun.sh for convenience.
> Fixup docker build/run

- resources/profiles/Creality/machine/Creality Ender-3 V3 0.4 nozzle.json
- resources/profiles/Creality/machine/Creality Ender-3 V3 0.6 nozzle.json
Orca complains that the jerk of the basic profile is higher than the maximum jerk of the printer. Since the printer is as capable as a K1, I increased the printer's maximum jerk to 12 to be able to quickly print the infill.
> Ender3 v3 maximum jerk fix

- src/imgui/imconfig.h
Problem is both shares same ID on code
```
const wchar_t ClipboardBtnDarkIcon       = 0x0836;
const wchar_t PrevArrowBtnIcon            = 0x0836; 
```
Before
After
> Fix measure gizmo "Copy to Clipboard" button icon for dark mode

- src/libslic3r/GCode/WipeTower.cpp
- src/libslic3r/GCode/WipeTower2.cpp
When using a non BBL printer (i.e. klipper or other) the wipe tower filament use statistics where displaying 0 for all filaments except one and incorrectly counting the purge volume in the wipe tower per filament. The total volume was correct though.
See below:
This PR addresses this issue by correctly tagging the start and end of the wipe tower and correctly assigning the printer type (BBL or non BBL) in the Gcode processor when the corresponding Wipe towers are initialised.
> Fix wipe tower not showing purged filament volume for non BBL SEMM

- src/libslic3r/Fill/Fill.cpp
- src/libslic3r/Fill/FillBase.hpp
- src/libslic3r/Preset.cpp
- src/libslic3r/PrintConfig.cpp
- src/libslic3r/PrintConfig.hpp
- src/libslic3r/PrintObject.cpp
- src/slic3r/GUI/ConfigManipulation.cpp
- src/slic3r/GUI/GUI_Factories.cpp
- src/slic3r/GUI/Plater.cpp
- src/slic3r/GUI/Tab.cpp
1. Allow user to set sparse/solid infill direction independently.
2. Allow user user to disable solid infill direction rotation for solid infill, this is useful when printing transparent materials.
https://github.com/SoftFever/OrcaSlicer/assets/103989404/9ccdb6e7-2030-4e73-a2a2-0691102181a4
> Infill direction enhancements

- src/slic3r/GUI/GLCanvas3D.cpp
• This allows closing when other toolbar icon clicked
• Also allows closing gizmo when its icon clicked
• Gizmo still keeps open when other areas clicked
Before (GIF)
• Clicking other gizmos not closing variable layer height and overlaps with other gizmos
After (GIF)
• Gizmo closes itself when other gizmos activated
I have tried rotate while variable layer height gizmo open. but it resets it self and i guess its not a planned feature. Recommended to use as a popup window if that's used like this
What's your opinion on this?
> Close Variable layer height gizmo when other toolbar buttons clicked

- src/libslic3r/GCode.cpp
- src/slic3r/GUI/Preferences.cpp
Fixes #4875, #4694 
Checks the below conditions for Klipper firmware:
1. If the total number of mesh points is 6 -> use Lagrange interpolation
2. If the total number of mesh points is greater than 6, use Bicubic
3. If bicubic is used, ensure that at least 4 points are present in both X and Y. 
This appears consistent with the Klipper documentation below and the KAMP implementation.
algorithm: lagrange
Default Value: lagrange
The algorithm used to interpolate the mesh. May be lagrange or bicubic. **Lagrange interpolation is capped at 6 probed points** as oscillation tends to occur with a larger number of samples. **Bicubic interpolation requires a minimum of 4 probed points along each axis**, if less than 4 points are specified then lagrange sampling is forced. If mesh_pps is set to 0 then …
> Fix bed mesh algorithm for 3 point bicubic algorightm

- src/libslic3r/GCode/WipeTower2.cpp
- src/libslic3r/GCode/WipeTower2.hpp
- src/libslic3r/Preset.cpp
- src/libslic3r/Print.cpp
- src/libslic3r/PrintConfig.cpp
- src/libslic3r/PrintConfig.hpp
- src/slic3r/GUI/ConfigManipulation.cpp
- src/slic3r/GUI/Plater.cpp
- src/slic3r/GUI/Tab.cpp
This PR aims to address the static coded nature of the maximum speed used for purging in the purge tower. Currently the speed limit is set to 90mm/sec which works well; however speed gains can be made by increasing this if the printer is able to bridge at higher speeds in the wipe tower.
This PR introduces a max speed limit for the purge tower. The existing, as is limits of volumetric flow for the filament and sparse infill speeds are respected. Same for the ramping up of purge speed up to the limit.
**Before:**
**After:**
Tested on my V2.4 350 with ERCF successfully with 150mm/sec with no adverse effect on the prime tower stability, while saving a considerable amount of time from the print - in the example above around 4 hours...!
Regression test: Confirmed that option is not visible on …
> SEMM: Introduced parameter to control the maximum speed used for purging in the purge tower

- resources/profiles/Creality/filament/Creality Generic ABS.json
- resources/profiles/Creality/filament/Creality Generic PETG.json
- resources/profiles/Creality/filament/Creality Generic PLA.json
- resources/profiles/Creality/filament/Creality Generic TPU.json
- resources/profiles/Creality/machine/Creality Sermoon V1 0.4 nozzle.json
- resources/profiles/Creality/machine/Creality Sermoon V1.json
Description - Creality Sermoon V1 - added generic filaments and machine settings
Added Creality Generic PLA, TPU, ABS and PETG.  Updated the thumbnail size from 32x32 to 64x64.  Added initial extruder clearance values.  Set to brass nozzle type.
> Creality Sermoon V1 - added generic filaments and machine settings

- src/slic3r/GUI/Tab.cpp
Before
After
I'm planning to fix all margin related problems at separate commit
> Hide revert and delete preset buttons while search box focused

- src/slic3r/GUI/GUI_Factories.cpp
Adds "Add Model" item for plate and background context menus
• One of the most used functions like arrange, split or etc. they are already exist on toolbar and context menu
• Knowing add / import function on context menu is useful and adds a alternative way to import model
• you don't have to move mouse to toolbar. reduces mouse movements
• I'm sure many people will found useful. especially people that came from cura. I'm still searching this item on context menu
• I added menu item to end of menu to keep same order otherwise old users will click to "add model" every time instead "add primitive"
• "Add models" already exist in translations. Does not require additional translations
Code can be shorter if it was used like this
```
#ifdef __WINDOWS__
auto add_icon = "menu_add_part"
#else …
```
> Add "Add Models" to plate and background context menu

- src/slic3r/GUI/Plater.cpp
This makes loading multiple step files much easier.
> QoL: Add option to not show non-utf8 step warn

- resources/profiles/Qidi/process/fdm_process_qidi_x3_common.json
This commit is a consequence of this PR https://github.com/SoftFever/OrcaSlicer/pull/5352 so I disabled Arc Fitting option for all Qidi models that had it enabled.
This improve surface finish on stock printers.
> Disabled arc fitting for Qidi X3/Q1 series

- src/slic3r/GUI/MsgDialog.cpp
- src/slic3r/GUI/MsgDialog.hpp
Current implementation of RichMessageDialog creates and pushes extra checkbox widget into button button sizer which already filled in with wxEXPAND items. That pushes position of newly added checkbox to the left-most position which makes it invisibe for some users.
Optimize implementation of RichMessageDialog using m_checkbox_dsa of MessageDialog instead of creating a new one. As a result, position of the checkbox is right below the main text section.
Adresses #5333
Original dialog:
Updated dialog:
> gui: improve RichMessageDialog

- src/slic3r/GUI/ObjectDataViewModel.cpp
New vs Old
• used font size for spacing width. this also gives better result for scaling
how to get all 3 icons for same list item
• Pick a step file or use a model with open mesh
• Use cut and add connector then perform cut. ignore dialog for fix
Another scenario for multiple icons
• Add a cube
• Add a modifier
• Cut with pins
I'm sure there are many other combinations for multiple icons with / without cut
Also found this minor bug
• Scaling not works on that icons on original source if scaling changes while orca running
> Add spacing between icons of objects list item if it has multiple icons

- src/slic3r/GUI/GCodeViewer.cpp
- src/slic3r/GUI/GLCanvas3D.cpp
- src/slic3r/GUI/KBShortcutsDialog.cpp
This change improves gcode preview navigation:
1. Added Home/End key actions in order to se horizontal (moves) slider to the start/end position respectively.
2. Automatically switch to the next layer on pressing right at the last position of the layer. Same for the pressing left at the first position.
https://github.com/SoftFever/OrcaSlicer/assets/46728448/4fe6dd27-cb94-428a-94a2-791b7519cd6c
Manual testing only.
Community testers are welcome.
> Improve gcode preview navigation

- src/slic3r/GUI/Tab.cpp
Bug appeared after https://github.com/SoftFever/OrcaSlicer/pull/5386
Updates all tabs instead only active tab
Maybe requires a bit more testing
> Fix parameters not updating on non active tabs

- src/libslic3r/PrintConfig.cpp
The incorrect identification of strings with the c-format >> no-c-format has been fixed
> fix_c-format->>-no-c-format

- src/libslic3r/PrintConfig.cpp
This adjustment is based on feedbacks and my own daily use experience.
gap_fill_target -> gftNowhere
z_hop_types -> zhtSlope
ensure_vertical_shell_thickness -> evstModerate
top_surface_pattern -> ipMonotonicLine
> Orca Slicer default parameter tweaks

- src/slic3r/Utils/OctoPrint.cpp
Fixed the issue where the port was not being obtained when retrieving the Host, because according to the specification ([https://www.rfc-editor.org/rfc/rfc7230#section-5.4](https://chatgptnw.s2time.com:4443/url)), the host for this request needs to include the port.
This issue can be reproduced in v2.0.0. If your device address is a domain name with a port (e.g., [https://example.com:8080](https://chatgptnw.s2time.com:4443/url)), uploading gcode will fail.
Tested in v2.0.0
> Fixed not get port when obtaining the host.

- src/libslic3r/GCode/SeamPlacer.cpp
- src/libslic3r/GCode/SeamPlacer.hpp
> improve seam performance

- src/libslic3r/GCode.cpp
Setting ```slow_down_layers``` to 2 or more results in wrong number of slowed down layers.
Do not increment layer_id since bottom layer (#0) handled separately.
At slow_down_layers=0 and slow_down_layers=1 acts the same slowing down first layer.
Values slow_down_layers >= 2 defines exact number of layers printed at slower speeds.
Addresses #4898 
Manual tests. Test gcode with different ```slow_down_layers``` values attached: 
[slow_down_layers-test.zip](https://github.com/SoftFever/OrcaSlicer/files/15369200/slow_down_layers-test.zip)
> fix slow_down_layers

- src/libslic3r/GCode.cpp
- src/libslic3r/Print.cpp
- src/libslic3r/Print.hpp
This uses the BBS project name from the `Project` tab which could be susceptible to upstream changes removing this feature.
The project_name template only works when you open a 3MF file. If you create a new project and set the project name `Model.model_info` is always null whether you save the project or not. If you save the current project, switch to a new project/different project, then re-load it then the template works as expected.
I'm not sure if it's an issue with this implementation or something else upstream.
This is distinct from the project file name in that it can be used to group multiple 3MF files under the same project. For example if you are printing parts for a Voron printer on a Voron 2.4 and Trident, you would have a 3MF file per printer but you may not want the …
> feat: add model_name and plate_number placeholders

- src/slic3r/GUI/SelectMachine.cpp
Addresses #5380 
Reverts the change from Bambu that disables the ability to override the nozzle size check.
I was able to compile and run this in Ubuntu.
I placed my 0.25mm Revo nozzle and sliced and printed. In the 2.1 nightly it blocks me. With this change I can now successfully print.
> Removes check to disable nozzle override from Bambu Studio.

- scripts/generate_presets_vendors.py
- src/slic3r/GUI/CreatePresetsDialog.cpp
Added Anker printers to filament presets dialog.
Added helper to generate formatted hard-coded strings in the dialog from the available profile JSON files.
Many popular/common filament vendors are now pre-populated in the custom filament vendor list. 
Now entries are sorted alphabetically rather than randomly.
Output from the helper script:
```
Scripts dir: /home/anselor/source/OrcaSlicer/scripts
Looking in /home/anselor/source/OrcaSlicer/resources/profiles
{"Anker",              "Anycubic",           "Artillery",          "Bambulab",           "BIQU",
"Comgrow",            "CONSTRUCT3D",        "Creality",           "Custom Printer",     "Dremel",
"Elegoo",             "Flashforge",         "FLSun",              "FlyingBear",         "Folgertech",
"InfiMech",           "Kingroon", …
```
> Added additional filament vendors.

- src/libslic3r/PrintConfig.cpp
Fixes #5475
It seems like the word `infill` was meant to be used rather than `walls`
> Fix potential typo with print infill first tooltip

- src/libslic3r/Fill/FillCrossHatch.cpp
Optimize the cross-hatch infill pattern to improve strength when low infill density is used.
The cross-hatch pattern increases the printing speed, but it does not perform well when the infill density is low.
This PR improves the strength when density is low.
Before:
After:
> optimize cross hatch infill to enchance strength

- localization/i18n/fr/OrcaSlicer_fr.po
G-code shouldn't be translated by "code G", but some of them were still in the translations, this fixes them for the sake of consistency.
> Fixes remaining "code G" in French translations

- src/libslic3r/GCode.cpp
See https://github.com/bambulab/BambuStudio/commit/525c0464a3f2cbfb15e6460580f60b29c5a27c48
> Fix issue that skip object won't trigger filament change when print-by-object is used

- src/libslic3r/GCode/GCodeProcessor.cpp
- src/libslic3r/GCode/GCodeProcessor.hpp
Orca now take "Flow ratio" value in filament settings into account when display flow for each extrusion in g-code legend.
> Take filament flow ratio into account when displaying flow in gcode legend

- src/imguizmo/ImGuizmo.cpp
- src/imguizmo/ImGuizmo.h
- src/slic3r/GUI/GLCanvas3D.cpp
- Add text to faces
- Better color scheme
> Better 3D navigator

- src/libslic3r/Fill/Fill.cpp
This PR fixes the "Line" sparse infill bug, it was lined up instead of interlaced.
Compiled and tested in Windows11.
Fixes #5655
> Fix Line sparse infill

- resources/profiles/Flashforge/filament/FusRock Generic NexPA-CF25.json
- resources/profiles/Flashforge/filament/FusRock Generic PAHT-CF.json
- resources/profiles/Flashforge/filament/FusRock Generic PET-CF.json
- resources/profiles/Flashforge/filament/FusRock Generic S-Multi.json
- resources/profiles/Flashforge/filament/FusRock Generic S-PAHT.json
- resources/profiles/Flashforge/filament/Polymaker Generic CoPA.json
- resources/profiles/Flashforge/filament/Polymaker Generic S1.json
- resources/profiles/Flashforge/machine/fdm_adventurer5m_common.json
1. Update AD5M series gcode: E-0.2;
2. Correct the filament mapping for those filaments specifically used on G3U;
3. Fix the filament type for S-Multi and S-PAHT.
Looks good on local test.
Hi @SoftFever ,  for your review. I kept the file-naming as usual this time.
> Flashforge-06-12: gcode and filament mapping

- src/imguizmo/ImGuizmo.cpp
The old `drawList->_VtxWritePtr` will be invalid if the VtxBuffer get resized during text rendering, which caused this crash. Use the vtx index instead of the raw printer.
> Fix crash caused by wrong pointer used after VtxBuffer resized during 3d navigator rendering

- src/libslic3r/GCode.cpp
- src/libslic3r/GCode/SmallAreaInfillFlowCompensator.cpp
- src/libslic3r/GCode/SmallAreaInfillFlowCompensator.hpp
- src/libslic3r/PrintObject.cpp
- Fix regression, always create SmallAreaInfillFlowCompensator model
`small_area_infill_flow_compensation` is per-region parameter, it's not necessary to iterate though all regions to check whether to create a model.
- Make SmallAreaInfillFlowCompensator more robust
1. handle spaces/tabs/new lines etc.
2. don't throw exception, fall back to no-op instead if parsing failed
- Fixing an issue that changing small_area_infill_flow_compensation per modifier didn't take effect
Fixed #5780
> Fix small area flow comp regression and some other small tweaks

- .github/workflows/build_all.yml
- .github/workflows/build_check_cache.yml
- .github/workflows/build_deps.yml
- .github/workflows/build_orca.yml
- build_release_macos.sh
This fixed some strange MMU issues on Mac
> Upgrade Mac CI/CD to macos-14

- src/libslic3r/Model.cpp
Fixes bugs like #5578, #4719 by not using `get_scaling_factor`
Fix  #5578, Fix #4719
Issue can be easily reproduced by:
> Fix few mirror related issues

- src/libslic3r/GCode/Thumbnails.cpp
- src/libslic3r/GCode/Thumbnails.hpp
- src/libslic3r/PrintConfig.cpp
Building without precompiled header support revealed some missing includes that are added with this change for code health purposes. Those missing includes were hidden by precompiled header support due to the fact that the precompiled header file provides some definitions despite not being defined in directly or indirectly included header files.
> add missing includes

- src/libslic3r/GCode/PressureEqualizer.cpp
Currently extrusion rate smoothing outputs a float to the set speed command. However this results on occasion in trivial speed fluctuations midway through continuous speed segments like seen below. This may or may not have an effect on print output; however it should be addressed to eliminate redundant gcode commands.
By rounding the speed to whole numbers this issue is eliminated, while also allowing speed adjustments to continue to be emitted where the speed delta is more than 1mm/sec
> Extrusion Rate Smoothing: Round speed values to prevent needless & trivial speed fluctuations

- src/slic3r/GUI/MainFrame.cpp
- src/slic3r/GUI/Plater.cpp
- src/slic3r/GUI/Plater.hpp
- src/slic3r/GUI/ProjectDirtyStateManager.cpp
Unsaved (changed) project is marked with asterisk like in many other applications:
Clean (saved):
Modified:
Handled config changes, objects moves, Undo/Redo commands.
Tested on Windows only.
> Mark unsaved project title with *

- build_release_vs2022.bat
- use DEPS variable for both deps and slicer build
- use installed WinSDK version
- echo real cmake command line
> VS2022 Win10 build fix

- src/libslic3r/GCode/SmallAreaInfillFlowCompensator.cpp
- src/libslic3r/Interlocking/VoxelUtils.cpp
- src/libslic3r/Interlocking/VoxelUtils.hpp
- src/libslic3r/PerimeterGenerator.cpp
- src/slic3r/Utils/Http.hpp
Here are more missing header files recently identified by building without precompiled header support.
> more missing includes

- .github/workflows/build_orca.yml
This PR fixes the issue that only one of the two Linux builds gets published due to a naming collision (a small oversight from #5919).
> CI: Avoid Linux Asset Name Collision

- src/slic3r/GUI/Gizmos/GLGizmoCut.cpp
Fixes several utf-8 related issues in Cut gizmo, when using languages in non-ascii characters, such as Chinese:
- Groove Angle rest button not working
- Reset cut plane button and tooltip are garbled:
- Z reset button tooltip is garbled:
- Avoid some unnecessary std::string -> char* -> std::string conversion
> Fix some utf-8 related issues in Cut gizmo

- src/libslic3r/GCode/WipeTower2.cpp
The speed of the outer wall may exceed the max speed on the wipe tower, which may lead to insufficient adhesion between different materials, such as PETG and PLA.
> Limit the max speed on the wipe tower

- doc/Calibration.md
After doing the pattern pressure advance calibration test, I saw that there was no difference in each line. After searching, it turns out that often the stock Marlin firmware does not have the pressure advance activated (as in my case for a stock Creality Ender 3 S1 Pro).
The linked Ellis' Print Tuning Guide does mention this, but in the [introduction page](https://ellis3dp.com/Print-Tuning-Guide/articles/pressure_linear_advance/introduction.html), not in the [pattern page](https://ellis3dp.com/Print-Tuning-Guide/articles/pressure_linear_advance/pattern_method.html).
I've also changed the notes and warning with github markdown alert to better highlight the reader about the warnings and notes.
> [doc] Warn Marlin user that Linear Advance must be enabled in firmware to do the Pressure Advance/Linear Advance calibration

- src/platform/unix/BuildLinuxImage.sh.in
When user built Mesa from GIT and load it using env variables `LD_LIBRARY_PATH` and `LIBGL_DRIVERS_PATH`
it overrides `LD_LIBRARY_PATH` inside AppImage but other variable `LIBGL_DRIVERS_PATH` does not override and it cause EGL init error (see screenshots).
Here I did paththrough `LD_LIBRARY_PATH` to application and Mesa loader
PS: I see that other guys works on Flatpak version - it use own Mesa containerized with application and should works perfectly without changes in such case.
Only bug fix for users that has Mesa from GIT
Here should not be anything that can break something
It should start successfully, otherwise it just segfault on startup not even shown UI
> AppImage: Fix env overrides that cause segfault and EGL initialization error for Mesa from GIT

- resources/profiles/UltiMaker/filament/UltiMaker Generic ABS.json
- resources/profiles/UltiMaker/filament/UltiMaker Generic PLA.json
- resources/profiles/UltiMaker/filament/fdm_filament_abs.json
I found that the UM2, barely reaching 5 mm3/s, was set to 12 mm3/s for PLA, so I checked various settings and corrected them:
ABS from 2 to 4.5 mm3/s (tested myself on Cura, it's the standard settings)
PLA from 12 to 5 (tested myself)
I changed one flow multiplier for ABS because it was too low (my experience on multiple ABS on the UM2, using Cura).
And I increased the bed temperature for ABS from 80C to 90C.
I used my experience with UM2 and Cura.
> Correction material settings for Ultimaker 2

- localization/i18n/zh_CN/OrcaSlicer_zh_CN.po
只是补充了中文翻译，
Add
圆弧拟合 选项描述
精准外墙尺寸 选项描述
Edit
视角控制器的六个面名字，使其更符合直觉且有更高的可读性
顶部 => 上
底部 => 下
左面 => 左
右面 => 右
前面 => 前
后面 => 后
抱歉，只修改了po文件，无截图和测试。
一个建议，希望能够将翻译独立到例如 weblate 等在线翻译协作平台，其使用Git进行版本管理和署名等，具有GUI，相比于直接编辑po文件方便得多，也能更容易整体审查和调整翻译。
当前版本翻译充斥着大量口语化措辞以及对于同一个行为的不同描述，如果可能的话希望能够提供一个更方便的翻译编辑方式进行统一。
> Update zh_CN translaton.

- src/slic3r/GUI/GCodeViewer.cpp
First time contributing, I hope I'm doing this correctly.
Removed `imgui.set_requires_extra_frame()`, this line causes Slic3r::GUI::GLCanvas3D::render() to be called repeatedly when 'Filament' or 'Speed' is selected in the preview panel (even when OrcaSlicer is minimized)
This should fix #3594 
I see that this line was added in #3363. I don't fully understand the intention behind it, but removing this line does not seem to affect the legend window fix
Now in "Filament" or "Speed" preview, GPU usage is 0% when OrcaSlicer is minimized or idle.
Before:
After:
> Fixing high GPU usage when color scheme is set to "Filament" or "Speed"

- src/slic3r/GUI/CreatePresetsDialog.cpp
Added Styrene Butadiene Styrene (SBS) to filament_types.  This is a very popular filament in South Africa with multiple manufacturers.
Examples:
https://www.filx.co.za/products/sbs/
https://dc3dprinters.co.za/product/sa-filament-sbs-plus-1-75mm-white-750g/
> Added Styrene Butadiene Styrene (SBS) to filament_types

- src/libslic3r/GCode.cpp
This PR will increase draft shield stability.
N.B. `layer_id % 2 == 1` is odd mathematically, but from user POV layer number starts from one, not zero.
> Reverse draft shield direction on even layers to reduce thermal stress.

- src/slic3r/GUI/Preferences.cpp
Update the way the preferences dialog size is set. Currently, on multi monitor setups, only the resolution of the main display is used, even if the window is on a different monitor with a different resolution. Now, the resolution of the monitor displaying the window is used in the sizing calculation. Also, rather than getting the total vertical resolution of the monitor, it gets the usable (or as wxWidgets calls it, the client resolution). This gets the area of the screen that does not include the task bar.
Before:
After:
Tested on Windows 11
fixes #5782
> Fix Preferences dialog sizing on multi monitor setups

- src/libslic3r/Slicing.cpp
- src/slic3r/GUI/GLCanvas3D.cpp
Currently in variable layer height slider heights are shown with six digits precision:
It has no meaning as Z height is rounded to three digits anyway (and to two digits in slider):
This PR rounds variable height calculation and displaying to three digits:
> Limit variable layer height displaying precision to 3 digits

- src/libslic3r/GCode/ToolOrdering.cpp
Slice will fail if:
1. support is enabled
2. object is floating (by having a very sharp edge touching the build plate)
3. print-by-object
4. Only a single filament is used
This project demonstrate this issue:
[toolorderissue.3mf.txt](https://github.com/user-attachments/files/16064973/toolorderissue.3mf.txt)
The same issue was presented in by-layer mode and was patched by this commit before: 612204b443ca716b9a9936386327b1e45120d06b
And this PR applies this same patch to by-object mode.
> Fix access violation when slicing project with print-by-object mode

- CMakeLists.txt
- src/libslic3r/Extruder.cpp
- src/libslic3r/TreeSupport.cpp
- src/slic3r/GUI/Gizmos/GLGizmoFdmSupports.cpp
- src/slic3r/GUI/UnsavedChangesDialog.hpp
- src/slic3r/Utils/ESP3D.cpp
Suppress compiler warnings we not going to fix. Fix few obvious errors.
While looking at issue #6137 I found suspicious code: 
https://github.com/SoftFever/OrcaSlicer/blob/5e4dd4d84792682accff3ae8c965444fcb5d242e/src/libslic3r/Extruder.cpp#L12
This led me to an idea that no one is looking at warnings produced by compilers.
Currently there are 3056 warnings emitted for OrcaSlicer build using GCC, nearly half of which are unused functions and variables. All that noise distracts developer making them completely ignore compiler output and because of this some obvious mistakes makes into the code base.
> Suppress some compiler warnings, fix few possible bugs.

- src/slic3r/GUI/GLCanvas3D.cpp
Moved number to a bit more close to corner. Fixes number overlaps with thumbnails on some models
Didnt tested on high resolution monitors. if there is a problem it can be fixed with using dpi ratio
before - after
> Update plate list > plate number position

- run_gettext.bat
A small follow-up for #5959
This PR changes the name of Python executable called in `run_gettext.bat` from `python3` to `python`. This is because the name of the Python interpreter (provided by [python/cpython](https://github.com/python/cpython)) in Windows is `python`, not `python3`.
> Localization: Change Python executable name for Windows

- src/libslic3r/GCodeWriter.cpp
- src/libslic3r/GCodeWriter.hpp
Currently both X/Y jerks are limited by lower jerk value from **Jerk limitation** settings. But for large bedslingers Y axis could have much less jerk then X due to weight. This PR set each axis jerk according to corresponding limit.
> Jerk - per axis maximum limit

- src/libslic3r/PrintConfig.cpp
Clarified flow ratio tooltips to explain how the object flow ratio, filament flow ratio, bridge flow ratio, internal bridge flow ratio, Top surface flow ratio and Bottom surface flow ratio are related and used.
Fixes: #6326
> Clarified flow ratio tooltips

- src/libslic3r/MeshBoolean.cpp
Surface_mesh iterators no longer return references, so it's necessary to use const references or copies when iterating.
This was previously merged in #3045 but isn't references in the current main branch any more. No idea where why it is gone, but the issue still persists thus the patch should still be added.
> Fix build with CGAL 5.6 (again)

- src/libslic3r/PrintConfig.cpp
- src/slic3r/GUI/ConfigManipulation.cpp
Clarified the gap fill selection drop down tool tip.
fixes: #6467 
**Edit:**
Following feedback, the tooltip of filter_out_gap_fill is also amended for clarity as well as the setting not being hidden any more if None is selected on the apply gap fill option, as this also controls the classic wall generator gap fill filter.
> Gap fill tool tip clarification & filter_out_gap_fill setting visibility

- src/slic3r/GUI/Field.cpp
- src/slic3r/GUI/Field.hpp
- src/slic3r/GUI/Tab.cpp
> Fix crash on Linux when switching between tabs in printer config

- README.md
- doc/Home.md
- doc/adaptive-pressure-advance.md
- doc/developer-reference/Home.md
- src/slic3r/GUI/Tab.cpp
Update the readme page to include link to wiki
Updated wiki homepage links to (hopefully) work :) 
Updated developer reference link to go to the "doc" folders instead of the wiki as the wiki has broken images and broken links.
Updated settings linkage in the slicer to the wiki for the new wiki sections.
Created adaptive pressure advance documentation ahead of 2.2 release.
> Wiki updates v2 & adaptive PA documentation

- src/OrcaSlicer.cpp
- src/libslic3r/Format/bbs_3mf.cpp
- src/slic3r/GUI/DeviceManager.cpp
- src/slic3r/GUI/GLCanvas3D.cpp
- src/slic3r/GUI/GLTexture.cpp
- src/slic3r/GUI/GUI_App.cpp
- src/slic3r/GUI/GUI_Factories.cpp
- src/slic3r/GUI/GUI_ObjectList.cpp
- src/slic3r/GUI/Jobs/PrintJob.cpp
- src/slic3r/GUI/Jobs/SendJob.cpp
- src/slic3r/GUI/ModelMall.cpp
- src/slic3r/GUI/PartPlate.cpp
- src/slic3r/GUI/Plater.cpp
- src/slic3r/GUI/Project.cpp
- src/slic3r/GUI/Search.cpp
- src/slic3r/GUI/UserManager.cpp
- src/slic3r/GUI/WebDownPluginDlg.cpp
- src/slic3r/GUI/Widgets/WebView.cpp
Following to **Fix Compile Warnings #5963** - incremental warnings elimination.
This PR only removes unused variables, it should be harmless change.
> Reduce warnings: remove unused variables

- CMakeLists.txt
- src/slic3r/GUI/PartPlate.cpp
- src/slic3r/GUI/Tab.cpp
- src/slic3r/GUI/Widgets/TabCtrl.cpp
> Fix crash in printer config when switching tabs

- src/libslic3r/Fill/FillConcentric.cpp
Followup to **Stagger concentric infill seams. #6184** 
1. Use `min_nozzle_diameter / 2` for shift.
2. Use if density >= 90%
3. Random spiral direction for not seams overlap:
> Refactor stagger concentric seams

- src/libslic3r/GCode.cpp
Initialize comment variable each time, otherwise it's growing unlimited and causes crash.
> Fix crash when both Flow compensator and Verbose Gcode are enabled.

- src/libslic3r/GCode/CoolingBuffer.cpp
- src/libslic3r/GCode/CoolingBuffer.hpp
Slow down proportionally code was removed in Prusa more than six year ago https://github.com/prusa3d/PrusaSlicer/commit/cbaf0ccc51133db07b47e1de0177b5db4fae2a02.
Let's cleanup code base.
> Remove unused slow down proportionally code

- src/slic3r/GUI/OG_CustomCtrl.cpp
- src/slic3r/GUI/PresetComboBoxes.cpp
- src/slic3r/GUI/Tab.cpp
- src/slic3r/GUI/Widgets/TabCtrl.cpp
Fixes a few tab related issues:
- The speed tab is not hidden properly when toggle off advance mode with speed tab currently selected:
- Crash when toggling off advance mode if you switched tabs in the printer config (similar to #6519):
- Crash if current selected tab is positioned after the removed tab (introduced in #6537):
- Wrong text boldness when the number of tabs changed (also introduced in #6537)
Known issue:
- In some cases the tab highlight will off (again, introduced in #6537):
> A bunch of tab fixes

- resources/profiles/Elegoo/machine/Elegoo Neptune 4 (0.2 nozzle).json
- resources/profiles/Elegoo/machine/Elegoo Neptune 4 (0.4 nozzle).json
- resources/profiles/Elegoo/machine/Elegoo Neptune 4 (0.6 nozzle).json
- resources/profiles/Elegoo/machine/Elegoo Neptune 4 (0.8 nozzle).json
Default printer profile for Elegoo Neptune 4 sets inexplicable retraction length of 5mm, which way too much for 
machine with direct extruder. It causes fusible filament like PLA slip between gears during deretractions, which leads to significant defects in model.
I copied profile settings from Neptune 5 Pro, because its settings have been fixed long time ago and both printers have exactly the same extruder. Also it is often recommended online to use Np4Pro profile for regular Neptune 4.
Default retraction settings of 5mm on the left VS 0.8mm retraction length on the right
⚙️ Eryone PLA 0.4 nozzle / 205°C / flow 1.05
You can see the difference on the photo above.
> UseElegoo Neptune 4 retraction from Np4 Pro profile

- src/slic3r/Utils/Http.cpp
`SLIC3R_APP_NAME + SoftFever_VERSION` is used in Gcode, but `SLIC3R_VERSION` is used incorrectly here.
> update User-Agent in http request header

- src/libslic3r/PerimeterGenerator.cpp
> Fix `only one wall on first layer` when raft is used

- src/libslic3r/PrintConfig.cpp
Make `Support style` and `Filter small bridges` option description and order more straightforward.
> Clarify support and filter bridge config options

- src/slic3r/Utils/MacDarkMode.mm
> Fix crash when dragging text in WebViews on macOS

- src/slic3r/GUI/AMSMaterialsSetting.cpp
- src/slic3r/GUI/Widgets/AMSControl.cpp
Fix ` 'wxPen::wxPen': deprecated: use wxPENSTYLE_XXX constants` warning. 
In latest `wx/peninfobase.h`:
```
enum wxPenStyle
{
wxPENSTYLE_INVALID = -1,
wxPENSTYLE_SOLID = wxSOLID,
....
}
```
> Warnings: replace wxSOLID with wxPENSTYLE_SOLID

- src/slic3r/GUI/Mouse3DController.cpp
When loading 3d mouse parameters from the config file, the x-axis inversion setting was incorrectly assigned to the y and z as well, which is remedied by this PR.
Since this seems a trivial enough change, I haven't done any local building/testing. Let me know if you need anything like that from me anyways.
> Fix loading 3d mouse params from config

- src/libslic3r/PerimeterGenerator.cpp
- src/libslic3r/PrintConfig.cpp
Currently every second layer for "on odd layer" options is checked as `layer_id % 2 == 1`. Though from mathematics POV it's correct, but in GUI first layer is one and not zero, thus actually option is applied for even layers.
I guess this is SuperSlicer legacy, and this PR fix this confusing description in GUI.
> Correct odd layer GUI description

- src/libslic3r/GCode/ExtrusionProcessor.hpp
During the overhang slowdown process, the overhang lines are split to apply the slowdown algorithm.
However there are certain cases where micro segments are generated (less than 0.01 mm in length). These micro segments result in wall extrusion consistency issues as reported here: https://github.com/SoftFever/OrcaSlicer/issues/6583
This PR aims to filter out the generation of these micro paths by ensuring that any new points generated are at least 25% of the line width long.
Fixes #6583
**Before:**
Micro paths generated.
**After:**
Micro paths filtered out.
Confirmed no regression in overhang performance due to filtered out segmentation with standard test model collection
**Before (2.2 beta):**
**After (this PR):**
Unchanged slowdown areas between the two versions.
> Filter out micro segments generated during the overhang slowdown process

- src/libslic3r/GCode.cpp
Without the trailing `\n` the internal gcode will look like this:
Then during the gcode export the gcode processor will remove it from file as it failed to parse this line,
which causes the missing of "total filament used [g]" in the final file
1. Select non-bbl printer
2. Slice anything and export the gcode
3. Check the gcode and see if "total filament used [g]" presents
> Fix issue that "total filament used [g]" is missing from gcode

- .github/workflows/build_orca.yml
- build_release_vs2022.bat
> Fix issue that github action windows build could not find win10sdk

- src/slic3r/GUI/GLCanvas3D.cpp
> Prevent toolbar clicking when mouse is hovering over layer height editor

- resources/profiles/Flashforge/machine/fdm_adventurer3_common.json
After conversation with original author of machine start g-code that causes problem with latest FlashPrint version bringing back pre-extrusion line but with slitly different position. With new value g-code exported from OrcaSlicer works as demand.
Flow rate calibration sliced, exported and loaded to FlashPrint without errors.
> FlashForge Adventurer 3 machine start gcode second fix #6282

- src/slic3r/GUI/GUI_App.cpp
Orca now check if a data directory (`data_dir`) exists at the application path. If so, use it as the data location. Otherwise, fall back to the `--datadir` option specified on the command line.
Fixes #1027
> Check and use data_dir folder if exists under application path

- src/libslic3r/PerimeterGenerator.cpp
Fix #6228 by applying the same fix as #5682 to Arachne wall generator.
Current:
Fixed:
> Fix fuzzy skin randomness for Arachne wall generator

- src/libslic3r/GCode/ToolOrdering.cpp
Fix #6807
All places that use `current_extruder_id` will first do a `if(current_extruder_id)` check, which will only be false if this optional is not set. But when it's initialized with `-1` all the checks will become useless which causes this crash.
> Fix crash when first layer is empty

- src/libslic3r/LayerRegion.cpp
Fix two issues introduced in PR #6654
- Use the variable `sparse` after been `std::move`-d
- The order of `expand_merge_surfaces()` call and the small region filtering block are reversed
This fixes the following bug:
> Fix small top/bottom solid infill filtering

- src/libslic3r/GCode.cpp
- src/libslic3r/GCode/GCodeProcessor.cpp
- src/libslic3r/GCode/GCodeProcessor.hpp
Reverts SoftFever/OrcaSlicer#6709
This reverts the spiral lift modifications by @ziehmon for this reason:
> unfortunately we need to revert this MR. There is a bug when AMS is used, since the position after changing filaments will be at X asis boundary and a spiral Z hop will move the axis out of physical boundaries. Details here: https://github.com/bambulab/BambuStudio/issues/4841#issuecomment-2362988198
> 
> I am working on fixing this and will provide the fix here too. Sorry, I should've bought an AMS...
and additionally:
> New PR: https://github.com/bambulab/BambuStudio/pull/4848
> Let's wait for review and testing. Will surely take some time, but at least that's fixed again...for now
The corrected spiral lift modification will be resubmitted once Bambu has completed testing their …
> Revert "Tsmith35 per BS PR4631 (#6709)"

- resources/profiles/Ratrig/machine/RatRig V-Core 4 300 0.4 nozzle.json
- resources/profiles/Ratrig/machine/RatRig V-Core 4 300 0.5 nozzle.json
- resources/profiles/Ratrig/machine/RatRig V-Core 4 300 0.6 nozzle.json
- resources/profiles/Ratrig/machine/RatRig V-Core 4 400 0.4 nozzle.json
- resources/profiles/Ratrig/machine/RatRig V-Core 4 400 0.5 nozzle.json
- resources/profiles/Ratrig/machine/RatRig V-Core 4 400 0.6 nozzle.json
- resources/profiles/Ratrig/machine/RatRig V-Core 4 500 0.4 nozzle.json
- resources/profiles/Ratrig/machine/RatRig V-Core 4 500 0.5 nozzle.json
- resources/profiles/Ratrig/machine/RatRig V-Core 4 500 0.6 nozzle.json
- resources/profiles/Ratrig/machine/RatRig V-Core 4 HYBRID 300 0.4 nozzle.json
- resources/profiles/Ratrig/machine/RatRig V-Core 4 HYBRID 300 0.5 nozzle.json
- resources/profiles/Ratrig/machine/RatRig V-Core 4 HYBRID 300 0.6 nozzle.json
- resources/profiles/Ratrig/machine/RatRig V-Core 4 HYBRID 400 0.4 nozzle.json
- resources/profiles/Ratrig/machine/RatRig V-Core 4 HYBRID 400 0.5 nozzle.json
- resources/profiles/Ratrig/machine/RatRig V-Core 4 HYBRID 400 0.6 nozzle.json
- resources/profiles/Ratrig/machine/RatRig V-Core 4 HYBRID 500 0.4 nozzle.json
- resources/profiles/Ratrig/machine/RatRig V-Core 4 HYBRID 500 0.5 nozzle.json
- resources/profiles/Ratrig/machine/RatRig V-Core 4 HYBRID 500 0.6 nozzle.json
This PR fixes a pretty major bug in the current Rat Rig V-Core 4 profiles shipped in OrcaSlicer, where the START_PRINT arguments where broken up by a linebreak, resulting in non functional g-code files.
> Fix invalid START_PRINT in unofficial Rat Rig profiles.

- resources/images/orca_bed_pct_left.svg
- src/libslic3r/GCode.cpp
- src/libslic3r/Preset.cpp
- src/libslic3r/Print.cpp
- src/libslic3r/PrintConfig.cpp
- src/libslic3r/PrintConfig.hpp
- src/slic3r/GUI/PartPlate.cpp
- src/slic3r/GUI/Tab.cpp
Support textured cool plates like BigTree's CryoGrip Textured Coating Steel Sheet. 
This allows users to adjust z offset for textured plates.
> Add support for textured cool plate

- src/libslic3r/ClipperZUtils.hpp
- src/libslic3r/Slicing.hpp
Here are more missing header files recently identified by building without precompiled header support.
> Fix building errors when precompiled header support is disabled

- src/slic3r/GUI/Plater.cpp
Followup to  **Auto arrange plate after cloning #6009** 
Use current plate as if arrange were called manually from menu.
> Followup to clones auto arrange:  use current plate

- src/slic3r/GUI/Gizmos/GLGizmoCut.cpp
Sync with latest PrusaSlicer code.
This option doesn't work when dovetail is used anyway so disable it to make it less confusing, and this matches the behavior as PrusaSlicer and BambuStudio.
> Disable "cut to parts" when dovetail is selected.

- src/libslic3r/GCode/WipeTower2.cpp
- src/slic3r/GUI/ConfigManipulation.cpp
Fix a bug where the wipe tower has missing extrusions when ramming is disabled.
Additionally, this update improves the logic for the 'Enable Filament Ramming' feature. We no longer need to set the cooling parameters to 0 to completely disable ramming.
Before:  
After fix:
> Fix a bug that wipe tower has missing extrusions when ramming is disabled

- src/libslic3r/GCode.cpp
- src/libslic3r/GCode/WipeTower2.cpp
Fixes issues discussed here: https://github.com/SoftFever/OrcaSlicer/pull/6894
**EDIT: Reverted changes for Z issues when next layer starts over the wipe tower.** Keeping the below commentary for reference only.
@SoftFever Would appreciate a review for the nozzle crash on the last wipe tower layer issue please. This was added here https://github.com/SoftFever/OrcaSlicer/commit/13ddb38119f7e86b2ff60916e73a80790649815c but with the model below I get a nozzle crash on the top layer as the nozzle is forced one layer down. For some reason this:
```
double current_z = gcodegen.writer().get_position().z();
if (z == -1.) // in case no specific z was provided, print at current_z pos
z = current_z;
```
Returns the previous layer Z when on the final wipe tower layer, so it pushes the nozzle down to …
> Fix wipe tower issues with SEMM and ramming turned off

- src/clipper/clipper.cpp
Fix #6933
Apply the patch from https://sourceforge.net/p/polyclipping/bugs/160/
> Fix issue that `z` is not properly set in some cases when clipping polygon

- localization/i18n/ru/OrcaSlicer_ru.po
I figured I didn't contribute as many translations, and also in some places the context wasn't taken into account, as there were some controversial translation situations. So I decided to remove the editor's label from the file, otherwise someone else will think I did it (no, I didn't) 🙂
> Removed editor's label from Russian translation file

- src/libslic3r/GCode.cpp
- src/libslic3r/GCode.hpp
- src/libslic3r/GCode/WipeTower2.cpp
- src/libslic3r/GCodeWriter.cpp
- src/libslic3r/GCodeWriter.hpp
…
This update, along with #6934, resolves the remaining issues with the wipe tower.
The GCode class will no longer maintain its own Z height information (m_nominal_z). Instead, it will utilize the Z height from GCodeWriter's m_pos. This approach is less error-prone.
This PR also fixes #6755.
It also enforce "Enable Filament ramming" option
@igiannakas It should fix the wipe tower crashing issue
> Fix an issue that wrong z value was used if a new layer is started with wipe tower extrusions.

- src/libslic3r/PerimeterGenerator.cpp
- src/libslic3r/PrintConfig.cpp
- src/slic3r/GUI/ConfigManipulation.cpp
> Allow reverse on odd without detect overhang wall

- src/OrcaSlicer.cpp
This PR aims to solve an exception when using OrcaSlicer in CLI which caused the --scale option to not work. 
All credits to @lanewei120 from BambuStudio for pushing it on BS repo.
Related commit on BS:
https://github.com/bambulab/BambuStudio/commit/2d4655e780e85e84445bb0b1987445e9e8d66b95#diff-2fa194122e892282ec589e51d5f7da65da83ec0488ced4b63930345d1273a353R3797
Related issue on BS:
https://github.com/bambulab/BambuStudio/issues/4628
Related issue on Orca:
https://github.com/SoftFever/OrcaSlicer/issues/6454
fixes #6454
```
./orca-slicer.exe --scale 2 --slice 1 --allow-newer-file test_model.stl --debug 5
```
The command above works again and scale the model then slice the scaled model. Before, the scale would not complete.
> FIX: CLI: fix an exception when parsing scale params

- src/slic3r/GUI/PartPlate.cpp
Currently, the grid has 3 round corners and 1 sharp corner. It seems like bambu lab hard coded this specifically to fit their bed model. As a non-bambu user, I dont like how the corners look.
Another point I'd like to bring up is that rounded corners do not match the boundary detection box. 
Tested locally on windows and macos.
> making all four corners of the grid sharp instead of round

- src/libslic3r/CSGMesh/CSGMesh.hpp
- src/libslic3r/CSGMesh/PerformCSGMeshBooleans.hpp
- src/slic3r/GUI/Plater.cpp
Porting from Prusa exporting negative parts.
Before:
After:
> Export negative parts

- src/slic3r/GUI/GUI_App.cpp
> Fixed an issue that if Orca was invoke by associated files, local data_dir was not used

- resources/profiles/Anker/machine/fdm_machine_common.json
Using the default 0.4 M5 profile in AnkerMakeStudio to compare, I updated the values to match
Updates the jerk limits, max feedrate, max acceleration, retraction length to match what ankermake studio has.
NA
> Update AnkerMake Jerk and Extruder settings to match AnkerMakeStudio

- resources/web/guide/22/22.js
fix the problem that the filament's selection varied depending  on the  different nozzles chosen in the Wizard.
- If choose Bambu 0.4mm nozzles, the ABS filament will be chosen.
- but If choose Bambu 0.2mm nozzles, the ABS filament will not be chosen
In configuration file，we only set that the machine's default filament is Bambu ABS for example. we don't distinguish the BambuABS and BambuABS 0.2mm and so is the wizard do. The wizard doesn't also show the BambuABS 0.2mm but BambuABS.
> Fix: Decouple the default material selection from the nozzle size on the machine.

- src/slic3r/GUI/DeviceManager.cpp
Allow printing prohibited filaments when 'Skip AMS Blacklist Check' is enabled.
Until now for prohibited filaments (even with Skip Check enabled) you get a warning and when clicking on 'Confirm' nothing happens. If using the 'Send' instead of 'Printing' it sends it fine to the printer as no check is performed but the print has to be started manually at the printer.
The PR checks if 'Skip AMS Blacklist Check' is enabled and overwrites the prohibit action from the blacklist file while the check is running with a warning action, so there is still a popup window but when confirming the print actually starts.
This is for sure not the most beautiful solution but the least intrusive as everything stays the same for the standard case where  'Skip AMS Blacklist Check' is disabled (default).
No UI …
> Allow printing prohibited filaments when 'Skip AMS Blacklist Check' is enabled

- src/clipper/clipper.cpp
The Eigen vector type compares all components, while the ClipperLib own IntPoint type compared x and y only.
Fixed by overriding the ==/!= operators to compare just x and y components for Eigen types.
Cherry-picked from prusa3d/PrusaSlicer@0202eec4b715eaa28a79f8bb82b0330c1efce8c9
This fixes #7160
Before:
After:
> Fixed Clipper library (our own fork of it) when working with Z coordinate

- src/slic3r/GUI/3DScene.cpp
- src/slic3r/GUI/GLCanvas3D.cpp
> Fix issue that thumbnail color not updated properly when AMS slot mapping changes

- src/slic3r/GUI/Plater.cpp
Reproduce:
1. Get a gcode file
2. Open Orca
3. Drag the gcode file into Orca
4. Drag the gcode file into Orca, again
5. Crash
> Fix crash when loading gcode file twice

- src/libslic3r/PrintApply.cpp
- src/libslic3r/TriangleSelector.cpp
- src/libslic3r/TriangleSelector.hpp
Fixes #7198
The issue can be easily reproduced on any platform by:
1. Add 16 filaments
2. Add a cube
3. Paint the cube using the 16th color
4. Slice & crash
Or simply slice the project from #7198.
> Fix crash when extruder 16 is used in color painting

- src/slic3r/GUI/GLToolbar.cpp
This reverts commit a26c573b1b13867ce50a16f0ae924be9aa05f26c.
Currently some of the toolbar icon is not hovered after mouse click (such as the add plate icon), and you have to move the cursor a little bit to highlight the icon again then you're able to click the icon again. Not a big deal in noremal use cases, however in sutuations like adding a lot of empty plates at once this could be annoying.
Not sure why BambuLab did this.
And not sure why I care about this and created this PR... (
> Allow clicking the toolbar icon multiple times without moving the cursor

- deps/CMakeLists.txt
A bunch of warnings printed at dependencies build:
```
CMake Warning (dev) at /usr/share/cmake-3.30/Modules/ExternalProject/shared_internal_commands.cmake:1282 (message):
The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is
not set.  The policy's OLD behavior will be used.  When using a URL
download, the timestamps of extracted files should preferably be that of
the time of extraction, otherwise code that depends on the extracted
contents might not be rebuilt if the URL changes.  The OLD behavior
preserves the timestamps from the archive instead, but this is usually not
what you want.  Update your project to the NEW behavior or specify the
DOWNLOAD_EXTRACT_TIMESTAMP option with a value of true to avoid this
robustness issue.
Call Stack (most recent call first): …
```
> Fix cmake warning on policy CMP0135

- src/libslic3r/Slicing.cpp
- src/libslic3r/Slicing.hpp
- src/slic3r/GUI/GLCanvas3D.cpp
This PR enforces Height Range Modifiers for Adaptive Layers. If object has such modifiers they layer height will be used and not be affected by Adaptive/Smooth/Editing:
> Adaptive layers - respect layer height range modifiers.

- localization/i18n/uk/OrcaSlicer_uk.po
Currently on Ukrainian language word "Bottom" is misspelled. Currently it is "Hіз", but correct is "Низ". This word is displayed on coordinate system widget and it is pretty disturbing to see it written all the time incorrectly
> Fix the incorrect translation of 'Bottom' into Ukrainian

- src/slic3r/GUI/ImageGrid.cpp
I was trying to download a file when it deleted instead, oops!
`HitTest()` expects only two buttons at this point, however `renderContent1` would always show 3. See images for demonstration.
I double checked Bambu Studio for the intended behavior, they show 2 buttons in this state. 
Applied the code changes in the PR and got the expected fix:
> fix: ImageGrid download button would delete instead

- src/slic3r/GUI/Downloader.cpp
OrcaSlicer: 2.2.0
Operator: Win10/11 Simplified Chinese 
when download from makerworld.com.cn, if filename contain chinese, the downloaded filename is in wrong encode. if the invalid encode contain character not allowed in windows path, the download will failed.
check the wxwidget docs: https://docs.wxwidgets.org/3.2.6/overview_unicode.html
> Notice that the narrow strings used with wxWidgets are always assumed to be in the current locale encoding
So, this code `wxString(escaped_url)`, wxWidgets will think the string is in current locale(gbk in chinese windows).
test file: https://makerworld.com.cn/zh/models/648200?designId=648200#profileId-589194
before: 
after:
this is also can use python to check:
```python
'拉面套装分盘'.encode().decode("gbk", errors='replace')
```
> fix filename encode issue when download chinese filename

- flatpak/io.github.softfever.OrcaSlicer.yml
This PR includes libspnav in the flatpak builds. Allowing usage of 3Dconnexion devices on linux systems with spacenavd is installed.
This partially fixes #5204 . However I'm only including my patch for flatpak, as I didn't confirm that the additional patches by @buzzhuzz ([commit](https://github.com/buzzhuzz/OrcaSlicer/commit/141b7c8154abe1bebac99478598c07ba9b45afd0)) are working.
Built and verified working on my system.
> Include libspnav in flatpak builds

- src/libslic3r/GCode/GCodeProcessor.cpp
- src/libslic3r/GCode/GCodeProcessor.hpp
With external purging solutions becoming more common, I’ve come across a limitation when assembling mine - it is impossible to estimate the amount of filament purged during slicing!
For example, when using Happy Hare together with the blobifier, it is not possible currently to estimate the volume of filament purged, because there are no G1 Ex commands issued by the slicer, but rather the purge volumes are calculated and executed by the printer/ happy hare and blobifier software and macros themselves.
**This PR aims to address this limitation by tagging the purge commands as specially formatted comments and use that to calculate the projected flushed filament volume.** This is particularly useful in combination with Spoolman as you can actually compare now the projected filament use vs …
> Integrate external purge estimates (eg Blobifier) to the filament consumption UI

- src/slic3r/GUI/3DScene.cpp
- src/slic3r/GUI/3DScene.hpp
- src/slic3r/GUI/GCodeViewer.cpp
Preview will be rebuilt every time we made any changes to the project, such as moving an object, even when the Preivew page is not shown. Creating raycasters (called from `GCodeViewer::load_shells`) is slow when model has lots of triangles, and those raycasters won't be used at all since we can't interact with any model on the Preview page, so those raycasters are useless, and should not be created at all.
This should make the GUI more responsive when working with projects that has lots of complicated models.
Further more, should we skip the preview reload entirely if the preview page is not shown?
> Do not create raycaster when loading the gcode preview

- src/slic3r/GUI/GUI_App.cpp
- src/slic3r/GUI/UnsavedChangesDialog.hpp
When I switch printers from the left tab bar, Orca checks if there have been any modifications relative to the system presets. If there are changes, it pops up the Unsaved Changes Dialog.
But sometimes I find that the change content display section in the dialog is empty. This is undoubtedly very confusing for users.
Upon investigation, it was found that this confusion arises because when comparing the initial preset with the current preset, there are some attributes that have not been changed, but the comparison still shows them as different. However, these attributes cannot be displayed in the dialog box (for example, the attribute long_retraction_when_cut).
So, I've made the size of m_presetitems the criterion for whether to pop up the dialog box or not, because what is actually …
> Fix: The "Unsaved Changes Dialog" pops up, but the content display section is empty.

- src/slic3r/GUI/GUI_App.cpp
- src/slic3r/GUI/ReleaseNote.cpp
* Removes `Preview` overwrite for pre-releases so that Semver can differentiate/compare the versions better. 
* Also removes the logic that tries to find a URL to load in the release notes. This used to cause blank release notes for releases that had 3x `###` followed by a URL in the description. v2.2.0-rc is a good example of this.
Applied this change to versions 2.1.0 and 2.2.0 beta so I could test both stable and unstable functionality.
Stable finds 2.1.1
Unstable finds 2.2.0 beta (Even though beta2 and rc are already released)
Stable finds 2.1.1
Unstable finds 2.0.0 rc
Stable finds nothing newer
Unstable finds nothing newer
Stable finds nothing newer
Unstable finds 2.2.0 rc
Unstable finds 2.2.0 beta2 when I manually remove 2.2.0 rc from the api response.
> Differentiates beta releases. Always shows release notes as text.

- src/libslic3r/PresetBundle.cpp
- src/libslic3r/PresetBundle.hpp
- src/slic3r/GUI/Tab.cpp
The core advantage of multi-tools devices lies in multi-color printing. For machines with multi-tools, it is more reasonable to set different default colors for each extruders.
- original effect:
- current effect:
> Feature: set different colors to tools on devices with multitools

- resources/profiles/Anycubic/process/0.08mm HighDetail @Anycubic Kobra 3 0.4 nozzle.json
- resources/profiles/Anycubic/process/0.10mm Detail @Anycubic Kobra 3 0.2 nozzle.json
- resources/profiles/Anycubic/process/0.12mm Detail @Anycubic Kobra 3 0.4 nozzle.json
- resources/profiles/Anycubic/process/0.16mm Optimal @Anycubic Kobra 2 Pro 0.4 nozzle.json
- resources/profiles/Anycubic/process/0.16mm Optimal @Anycubic Kobra 3 0.4 nozzle.json
- resources/profiles/Anycubic/process/0.20mm Standard @Anycubic Kobra 2 Max 0.4 nozzle.json
- resources/profiles/Anycubic/process/0.20mm Standard @Anycubic Kobra 2 Neo 0.4 nozzle.json
- resources/profiles/Anycubic/process/0.20mm Standard @Anycubic Kobra 2 Plus 0.4 nozzle.json
- resources/profiles/Anycubic/process/0.20mm Standard @Anycubic Kobra 2 Pro 0.4 nozzle.json
- resources/profiles/Anycubic/process/0.20mm Standard @Anycubic Kobra 3 0.4 nozzle.json
- resources/profiles/Anycubic/process/0.24mm Draft @Anycubic Kobra 3 0.4 nozzle.json
- resources/profiles/Anycubic/process/0.28mm Draft @Anycubic Kobra 2 Pro 0.4 nozzle.json
- resources/profiles/Anycubic/process/0.28mm SuperDraft @Anycubic Kobra 3 0.4 nozzle.json
- resources/profiles/Anycubic/process/0.30mm Standard @Anycubic Kobra 3 0.6 nozzle.json
- resources/profiles/Anycubic/process/0.40mm Standard @Anycubic Kobra 3 0.8 nozzle.json
This PR fixes a config issue found on the Kobra 2 / Pro / Plus / Neo / Max and Kobra 3 where "single_extruder_multi_material_priming" is enabled, causing all used filaments to be primed.
Before change:
Filament is primed at the edge of the build plate
After change:
> Disable priming extruders on Anycubic Kobra 2 / 3 

- resources/profiles/Anker/machine/Anker M5 0.2 nozzle.json
- resources/profiles/Anker/machine/Anker M5 0.25 nozzle.json
- resources/profiles/Anker/machine/Anker M5 0.4 nozzle.json
- resources/profiles/Anker/machine/Anker M5 0.6 nozzle.json
- resources/profiles/Anker/machine/Anker M5 All-Metal 0.2 nozzle.json
- resources/profiles/Anker/machine/Anker M5 All-Metal 0.25 nozzle.json
- resources/profiles/Anker/machine/Anker M5 All-Metal 0.4 nozzle.json
- resources/profiles/Anker/machine/Anker M5 All-Metal 0.6 nozzle.json
- resources/profiles/Anker/machine/Anker M5C 0.2 nozzle.json
- resources/profiles/Anker/machine/Anker M5C 0.25 nozzle.json
- resources/profiles/Anker/machine/Anker M5C 0.4 nozzle.json
- resources/profiles/Anker/machine/Anker M5C 0.6 nozzle.json
There was duplicate JSON keys in the Ankermake M5 and M5C json files. This just removes the useless duplicate keys.
NA
NA
> remove duplicate key "printer_structure" from Ankermake machine files

- src/libslic3r/PrintObjectSlice.cpp
> Fix overlapping regions caused by "Make Overhangs printable"

- linux.d/debian
When trying to compile OrcaSlicer on a minimal Ubuntu 20.04 and 24.04 (e. g. a container) `./BuildLinux.sh -u` exits silently:
```bash
root@6ababa89c422:/OrcaSlicer# ./BuildLinux.sh -u ; echo $? 
1
```
`./linux.d/debian` exits on the [first line](https://github.com/SoftFever/OrcaSlicer/blob/3caca2215db3eaf00ae97073763ab10579f900dd/linux.d/debian#L1) due to `set -e` in [`BuildLinux.sh`](https://github.com/SoftFever/OrcaSlicer/blob/3caca2215db3eaf00ae97073763ab10579f900dd/BuildLinux.sh#L5)
Tested compiling on Ubuntu 20.04 and 24.04
> fix: Don't exit if libgtk is not found

- CMakeLists.txt
- linux.d/fedora
Fedora 40 and 41 use GNU c++ version 14.2.1 which throws an error compiling OrcaSlicer:
`error: template-id not allowed for constructor in C++20`
To ignore this error `-Wno-error=template-id-cdtor` can be added to the compiler flags.
Furthermore Fedora 40 and 41 need an additional package to be installed: `libquadmath-devel`. On Fedora 39 this package is not needed, but it exists and does no harm.
A full compile run was carried out on these OS:
OS | Version | c++ -v | -Wno-error=template-id-cdtor needed? | libquadmath-devel needed? | Compile test passed?
-- | -- | -- | -- | -- | --
Fedora | 41 | 14.2.1 20240912 (Red Hat 14.2.1-3) | yes | yes | ✅
Fedora | 40 | 14.2.1 20240912 (Red Hat 14.2.1-3) | yes | yes | ✅
Fedora | 39 | 13.3.1 20240913 (Red Hat 13.3.1-3) | no | no | ✅
Ubuntu | 24.04 | …
> fix: allow build on Fedora >= 40

- src/slic3r/GUI/CreatePresetsDialog.cpp
1. some machine which names with "(0.x nozzle)" can not be used to create custom filament, eg: Snapmaker J1 (0.4 nozzle), Eleego
Neptune (0.2 nozzle). 
So, I added the processing code for this category of machine names.
2. Additionally, I believe that the logic for handling the @ character in material names is incorrect, which could lead to many compatible materials being missed. Therefore, I have also made corresponding modifications.
> fix: create custom filament

- resources/profiles/BBL/machine/fdm_machine_common.json
Issue is caused by #7629, which overwriten the profile with BBL's, which has some our unique properties missing. This PR brings them back.
Fixes #7751
> Fix Prime volume missing on BBL printers

- src/libslic3r/GCode/FanMover.cpp
This fixes #7171
Fna mover now manipulate part cooling fans only and ignore all other fans (which is what it's designed for).
> Fan mover: Ignore non-part cooling fans (SoftFever/OrcaSlicer#7171)

- src/libslic3r/Geometry/Voronoi.cpp
> Fix rare Arachne crash due to invalid voronoi diagram

- src/libslic3r/PrintConfig.cpp
- src/slic3r/GUI/Tab.cpp
As per title, fixes regression with the introduction of super tack plate for non BBL printers with multi bed support enabled.
In addition, generalised supertack plate title to make it suitable also for non BBL printers.
> Fix regressions with introduction of supertak plate for non BBL printers. Generalised plate title.

- resources/profiles/Elegoo/filament/Elegoo Generic ASA.json
- resources/profiles/Elegoo/filament/Elegoo Generic PETG PRO.json
- resources/profiles/Elegoo/filament/Elegoo Generic PLA Matte.json
- resources/profiles/Ratrig/filament/RatRig BigNozzle ABS.json
- resources/profiles/Ratrig/filament/RatRig BigNozzle ASA.json
- resources/profiles/Ratrig/filament/RatRig BigNozzle PCTG.json
- resources/profiles/Ratrig/filament/RatRig BigNozzle PETG.json
- resources/profiles/Ratrig/filament/RatRig BigNozzle PLA.json
- resources/profiles/Ratrig/filament/RatRig Generic PCTG.json
- resources/web/guide/22/22.js
Filaments that don't have compatible printers defined will invalidate filter in filament selection UI
This PR:
1. Fix profiles with missing compatible printers attributes
2. Change code logic so that we don't show such filaments
> Fix profiles with missing compatible printers

- src/libslic3r/PrintBase.cpp
- src/slic3r/GUI/AuxiliaryDataViewModel.cpp
- src/slic3r/GUI/Plater.cpp
- src/slic3r/GUI/RemovableDriveManager.cpp
Function was removed https://www.boost.org/doc/libs/develop/libs/filesystem/doc/deprecated.html
N/A
Did not check whether this change is enough to compile for recent boost versions. Certainly one step closer.
> Fix compatibility with newer Boost

- src/slic3r/GUI/CreatePresetsDialog.cpp
Orca doesnt recognize capitalized letter in 'Nozzle' in the printer name. Those printer profiles will not show up when creating custom filaments, which blocks users the ability to create custom filament profiles for those printers.
This fixes #7953 
2.3.0-dev:
after:
Tested locally on Windows11
> fixed a custom filament creation bug

- src/libslic3r/Support/TreeSupport.cpp
- src/libslic3r/calib.cpp
- src/slic3r/GUI/DeviceManager.cpp
- src/slic3r/GUI/Gizmos/GLGizmosManager.cpp
- src/slic3r/GUI/Jobs/PrintJob.cpp
- src/slic3r/GUI/Jobs/SendJob.cpp
- src/slic3r/GUI/MainFrame.cpp
- src/slic3r/GUI/MediaPlayCtrl.cpp
- src/slic3r/GUI/ReleaseNote.cpp
- src/slic3r/GUI/SendMultiMachinePage.cpp
- src/slic3r/GUI/Tab.cpp
- src/slic3r/Utils/UndoRedo.cpp
Fix some of the compiler warnings I was seeing while compiling the project with gcc 14.2.
Some things uncovered real bugs.
> Fix some errors uncovered via compiler warnings

- src/slic3r/GUI/Plater.cpp
Fixes https://github.com/SoftFever/OrcaSlicer/issues/5829
OrcaSlicer silently saves current project into the file "model.3mf" if new project was created and "model.step" object was imported into the project.
- Create new project
- Import object using "Add" button or by "Ctrl-I"
- Press "Save Project" or "Ctrl+S"
With this change "Save As" dialog should pop up
> do not set project filename on object import

- src/libslic3r/GCode/GCodeProcessor.cpp
Some portions of GCode (like BTT_TFT thumbnails)  has to be CRLF in order to work correctly. However, gcode post processor was ignoring input line endings style emitting '\n' (LF) into post-processed output.
Modified printer config to have 32x32/BTT_TFT thumbnails. Sliced and exported test model.
Thumbnail lines has CRLF line endings while actual gcode has LF line endings.
Test file:  [post-cap-Cap_PETG_40m55s-btt.gcode.zip](https://github.com/user-attachments/files/18466845/post-cap-Cap_PETG_40m55s-btt.gcode.zip)
> gcode: keep line endins in post processing

- src/libslic3r/PrintConfig.cpp
Just capitalized Tree and Normal plus added a space before (auto) for UI consistency.
I manually verified slicing still works and selects the correct support type
> capitalize support names in the UI for consistency

- src/libslic3r/Support/SupportMaterial.cpp
when interface layer number is set to 0
Cherry-picked from prusa3d/PrusaSlicer@ca5f6da08d38c75e0e00ea2604de9709b9caa8aa
Fix #7900
> Fix issue that the support contact layer is printed in wrong filament

- src/slic3r/GUI/GLCanvas3D.cpp
- src/slic3r/GUI/PartPlate.cpp
- src/slic3r/GUI/PartPlate.hpp
- src/slic3r/GUI/Plater.cpp
- src/slic3r/GUI/SceneRaycaster.hpp
This was caused by not unregistering the previous bed raycasters before resetting the bed polygons (which are used by the raycaster).
Also fixing the raycaster IDs for beds.
> Fix random crash when opening 3mf files that have bed size different than current

- src/libslic3r/GCode.cpp
- src/libslic3r/GCode.hpp
> Fix per-object overhang slow down

- src/libslic3r/Support/SupportMaterial.cpp
- src/libslic3r/Support/SupportMaterial.hpp
> Fix issue that support surfaces get filtered out unexpectly 

- src/slic3r/GUI/Field.cpp
Fix #7982
cherry picked from commit prusa3d/PrusaSlicer@555193f6ec477d4107f8998c7a3c441cde72382c
Thanks Prusa!
> Fix crash on macOS that you could set extruder number to 0

- src/slic3r/Utils/CalibUtils.cpp
> Fix flow dynamics calib crash when last bed type is selected

- src/libslic3r/Arrange.cpp
- src/libslic3r/Arrange.hpp
- src/slic3r/GUI/Jobs/ArrangeJob.cpp
- src/slic3r/GUI/Jobs/FillBedJob.cpp
Fix #5153
Fix #7745
Partly revert 0b6a1d36360448c5e6818001b9d8ea99a57567a7
> Fix arrange when print-by-object and have object off-plate

- src/libslic3r/GCode.cpp
- src/libslic3r/GCode.hpp
- src/libslic3r/Layer.cpp
Fix #8111
Similar problem as #7976, that regional options been used before regional config is applied. This PR fixes this issue.
> Fix issue that `is_infill_first` doesn't work correctly on regions

- src/libslic3r/Preset.cpp
- src/libslic3r/PrintConfig.cpp
- src/libslic3r/PrintConfig.hpp
- src/libslic3r/PrintObject.cpp
- src/libslic3r/Support/SupportMaterial.cpp
- src/libslic3r/Support/TreeSupport3D.cpp
- src/slic3r/GUI/ConfigManipulation.cpp
- src/slic3r/GUI/GUI_Factories.cpp
- src/slic3r/GUI/Tab.cpp
This PR unlocks and configure overhang offset support threshold in addition to angle threshold. Actually angle threshold has no intrinsic meaning, because it's offset which affects overhangs quality. Angle that could be printed without support is function of layer width and height.
This option sets percent of not supported external perimeter width triggering support
Width 0.62, layer 0.32, offset threshold 50%
Width 0.62, layer 0.32, offset threshold 80%
Width 0.62, layer 0.12, offset threshold 80%
So we don't need to adjust offset threshold when layer height is changed.
> Support threshold overlap

- resources/profiles/Creality/filament/Creality Generic ABS @K2-all.json
- resources/profiles/Creality/filament/Creality Generic ASA @K2-all.json
- resources/profiles/Creality/filament/Creality Generic PA-CF @K2-all.json
- resources/profiles/Creality/filament/Creality Generic PETG @K2-all.json
- resources/profiles/Creality/filament/Creality Generic PLA @K2-all.json
- resources/profiles/Creality/filament/Creality Generic TPU @K2-all.json
- resources/profiles/Creality/machine/Creality K2 Plus 0.2 nozzle.json
- resources/profiles/Creality/machine/Creality K2 Plus 0.4 nozzle.json
- resources/profiles/Creality/machine/Creality K2 Plus 0.6 nozzle.json
- resources/profiles/Creality/machine/Creality K2 Plus 0.8 nozzle.json
- resources/profiles/Creality/process/0.08mm SuperDetail @Creality K2 Plus 0.2 nozzle.json
- resources/profiles/Creality/process/0.08mm SuperDetail @Creality K2 Plus 0.4 nozzle.json
- resources/profiles/Creality/process/0.10mm HighDetail @Creality K2 Plus 0.2 nozzle.json
- resources/profiles/Creality/process/0.12mm Detail @Creality K2 Plus 0.2 nozzle.json
- resources/profiles/Creality/process/0.12mm Detail @Creality K2 Plus 0.4 nozzle.json
- resources/profiles/Creality/process/0.14mm Optimal @Creality K2 Plus 0.2 nozzle.json
- resources/profiles/Creality/process/0.16mm Optimal @Creality K2 Plus 0.4 nozzle.json
- resources/profiles/Creality/process/0.18mm Detail @Creality K2 Plus 0.6 nozzle.json
- resources/profiles/Creality/process/0.20mm Standard @Creality K2 Plus 0.4 nozzle.json
- resources/profiles/Creality/process/0.24mm Detail @Creality K2 Plus 0.8 nozzle.json
- resources/profiles/Creality/process/0.24mm Draft @Creality K2 Plus 0.4 nozzle.json
- resources/profiles/Creality/process/0.24mm Optimal @Creality K2 Plus 0.6 nozzle.json
- resources/profiles/Creality/process/0.28mm SuperDraft @Creality K2 Plus 0.4 nozzle.json
- resources/profiles/Creality/process/0.30mm Standard @Creality K2 Plus 0.6 nozzle.json
- resources/profiles/Creality/process/0.32mm Optimal @Creality K2 Plus 0.8 nozzle.json
- resources/profiles/Creality/process/0.36mm Draft @Creality K2 Plus 0.6 nozzle.json
- resources/profiles/Creality/process/0.40mm Standard @Creality K2 Plus 0.8 nozzle.json
- resources/profiles/Creality/process/0.42mm SuperDraft @Creality K2 Plus 0.6 nozzle.json
- resources/profiles/Creality/process/0.48mm Draft @Creality K2 Plus 0.8 nozzle.json
- resources/profiles/Creality/process/0.56mm SuperDraft @Creality K2 Plus 0.8 nozzle.json
Creality K2 Plus profile have some flaws, this is a first step in the right direction.
It fixes default parameters so filament is not flushed into the prime tower anymore, adds nozzle volume, fixes retraction travel moves, enables precise walls, ...
PS : I had to re-create this PR because of failing automated test related to untouched Prusa MK3S profiles.
> Improvements and fixes for Creality K2 Plus

- resources/profiles/Sovol/machine/Sovol SV06 ACE 0.2 nozzle.json
- resources/profiles/Sovol/machine/Sovol SV06 ACE 0.4 nozzle.json
- resources/profiles/Sovol/machine/Sovol SV06 ACE 0.6 nozzle.json
- resources/profiles/Sovol/machine/Sovol SV06 ACE 0.8 nozzle.json
SV06 ACE is compatible with some Bed from Bambu/Biqu/Elegoo.
Some print have been success more easily than the official bed.
> Sovol SV06 ACE Enable Multi Bed

- src/slic3r/GUI/GCodeViewer.cpp
This PR fixes the following issues:
1. Gcode Statistics Panel: open/close state not persistent between slicing: https://github.com/SoftFever/OrcaSlicer/discussions/6021
2. open/close button width is too wide
> Gcode Statistics Panel Fixes

- src/slic3r/Utils/Duet.cpp
This pull request includes a change to the `src/slic3r/Utils/Duet.cpp` file. The change ensures that passwords containing special characters are properly encoded in the URL.
* [`src/slic3r/Utils/Duet.cpp`](diffhunk://#diff-8fdf65478dafba9670beac4c1402b9031ad24c5dce09348d7773138b89735c99L208-R208): Modified the `get_connect_url` method to use `Http::url_encode` for encoding the password, ensuring special characters like `&` and `#` are handled correctly.
This is a very simple fix if there is a better approach, I am open to learn.
1.  Set the password on the controller to something like `password1`
2.  Inside the Orca physical printer dialog select Duet as the host type.
3.  Provide the simple password `password1`, this should result in a passing connection test.
4.  Set the password on the …
> Fix: URL-encode password in Duet::get_connect_url

- resources/profiles/Anycubic/filament/Anycubic PETG @Anycubic Kobra 3 0.4 nozzle.json
- resources/profiles/Anycubic/filament/Generic ABS @Anycubic Kobra 3 0.4 nozzle.json
- resources/profiles/Anycubic/filament/Generic TPU @Anycubic Kobra 3 0.4 nozzle.json
This removes filament_density: 0 setting from Kobra 3 profiles (fixes #7367)
> QOL fix : Removed filament_density: 0 from Kobra 3 profiles (fixes #7367)

- resources/profiles/Sovol/process/fdm_process_common.json
This PR fixes a missing "%" in the internal_bridge_speed setting for Sovol.
> Fix missing "%" on Sovol profiles fixes #8207

- src/libslic3r/PerimeterGenerator.cpp
When one wall top surface and precise wall is enabled with Arachne, the precise wall spacing is not observed in intermediate top surfaces.
See below spacing change between external perimeter and first internal when one wall is applied inside the model (the lettering on the right).
This issue can create external wall inconsistencies as on the one wall surface plane, the spacing between the first internal and external perimeter is different to all other layers. This can aggravate the so called benchy hull line issue.
https://github.com/user-attachments/assets/6c6d10a6-997b-48ad-8e7f-df4b8686b271
With this fix, we are resizing the internal polygons by the precise wall offset to align the first wall extrusions with the anticipated spacing. …
> Fix one wall top surface incorrect spacing when precise wall is enabled

- src/slic3r/GUI/GLCanvas3D.cpp
Fixes https://github.com/SoftFever/OrcaSlicer/issues/8214
glcanvas: workaround for touchpad nav on Win
Releasing ALT on windows platform result in GLCanvas losing focus.
Because of this mouse movements not being processed by on_mouse() event
handler and camera rotation have not cleaned up.
Make a workaround for Windows to cleanup camera rotate state on
releasing ALT modifier.
> Fix sticky camera rotate for touchpad navigation style on Windows

- resources/profiles/Anycubic/filament/Anycubic ABS @Anycubic Kobra S1 0.4 nozzle.json
- resources/profiles/Anycubic/filament/Anycubic ASA @Anycubic Kobra S1 0.4 nozzle.json
- resources/profiles/Anycubic/filament/Anycubic PETG @Anycubic Kobra S1 0.4 nozzle.json
The Anycubic Kobra S1 has a bad PETG profile by default, this PR aims to fix it.
So changes also for ABS and ASA but it's just in case other plate types are added later.
> Fix some filaments profiles for Anycubic Kobra S1

- doc/Calibration.md
Fix markdown format for text that was most likely intended to be bold
> Fix bold text in Calibration.md

- src/slic3r/GUI/Plater.cpp
Hides delete button if there is only 1 filament. Flushing button already hides itself so who not hiding delete button
• Changed position of add / delete buttons
Reason to this change > it adds filament back when user spams delete button
• Decreased area for expand/collapse feature on titlebar
Reason to this change > it expand/collapse filament section when user spams delete button and it creates confusion
Fixed
• Existing bug on current build > Flushing volumes icon visible on first launch while only 1 filament exist
I can remove all other changes and only keep fix above if you found changes unnecessary
Preview
how it looks with ams button
> Hide delete filament button while only 1 filament exist

- resources/profiles/Sovol/machine/Sovol SV06 ACE 0.2 nozzle.json
- resources/profiles/Sovol/machine/Sovol SV06 ACE 0.4 nozzle.json
- resources/profiles/Sovol/machine/Sovol SV06 ACE 0.6 nozzle.json
- resources/profiles/Sovol/machine/Sovol SV06 ACE 0.8 nozzle.json
- resources/profiles/Sovol/machine/Sovol SV06 Plus ACE 0.4 nozzle.json
Sets up the filament change and pause print commands for these printers.
There's only one toolhead, so `manual_filament_change` is required to avoid generating tool swap G-code that the printer won't recognize.
Hat tip: Oliver on the Sovol forums for [pointing out how to do this](https://forum.sovol3d.com/t/multicolor-with-the-sv06-ace/6715). :)
Ran a print with a pause and a filament change (see above).
> Configure filament change and pause commands for SV06 (Plus) ACE

- src/slic3r/GUI/SelectMachine.cpp
Fix text color for "Can't find device?" link in dark mode
> use orca color for "can't find device" link

- src/slic3r/GUI/ParamsPanel.cpp
Matches advanced text size on sidebar with toggle used on material/machine settings window
before - it uses same text size with title text. sub items should use smaller text size
after - Text size matched with Global/Objects toggle and Window version of Advanced toggle
> Match text size of advanced toggle text

- resources/profiles/Flashforge.json
The machine list of  `resources/profiles/Flashforge.json` contains a doubled entry `fdm_flashforge_common`.
The second entry is associated with ` "sub_path": "machine/fdm_adventurer3_common.json"`. 
This appears to be incorrect. Entry name has been renamed to the apparently more correct `fdm_adventurer3_common`.
> fix profile assignment of Flashforge.json

- src/slic3r/GUI/Plater.cpp
PROBLEM
• Current color palette has many repeating or very similar colors
• Colors looks came from 80s and all raw colors like rgb(0,255,255)
• Black and White colors shows less details on surfaces due to shadows and highlights
SOLUTION
• Picked more specific color tones. Tried to make every alternative to easily identifiable
• Didnt used black, white or gray
QUESTIONABLE
• New colors follows given order and i used orca color as first. Maybe orange one is better pick
• I can add, remove, or change order of colors
COMPARISON
before
after
old color set
new color set
as text if you want to experiment
`
wxColour("#00C1AE"),
wxColour("#F4E2C1"),
wxColour("#ED1C24"),
wxColour("#00FF7F"),
wxColour("#F26722"),
wxColour("#FFEB31"),
wxColour("#7841CE"),
wxColour("#115877"),
wxColour("#ED1E79"), …
> Update color palette for new filaments

- src/slic3r/GUI/SelectMachine.cpp
backported https://github.com/bambulab/BambuStudio/pull/5751
> Fix "Enable AMS" checkbox font inconsistency

- src/slic3r/GUI/Jobs/PrintJob.cpp
If the model comes from model mall, the name from the mall will be used when sending and printing. When there are special characters in the name, it will cause the sending to fail.
cherry picked from commit https://github.com/bambulab/BambuStudio/commit/1bcf30c39c648763952703c9060573baa2782f87
Fix #8136
> FIX:filter the characters of model names in the model mall

- src/slic3r/GUI/Tab.cpp
`interface_shells` option exists in original PrusaSlicer, this PR just expose this option as this is a useful feature for people want to print multi color logo or sign.
https://github.com/user-attachments/assets/449d6868-5791-4845-89d7-75e8d9f85826
Fixes #5106
> Expose interface_shells option

- src/libslic3r/GCode/GCodeProcessor.cpp
- src/libslic3r/GCode/GCodeProcessor.hpp
> Solve M73 issue: remove TimeProcessor::post_process

- src/libslic3r/GCode/SpiralVase.cpp
- src/libslic3r/Preset.cpp
- src/libslic3r/PrintConfig.cpp
- src/libslic3r/PrintConfig.hpp
- src/slic3r/GUI/ConfigManipulation.cpp
- src/slic3r/GUI/Tab.cpp
Currently when starting the spiral vase the extrusion rate is ramped from 0 to 100% on the first layer and from 100% to 0% on the last layer. In some cases it can lead to underextrusion at the beginning and end of the spiral.
This change adds minimum flow rate options for the beginning and the end of the vase. This means that instead of ramping from 0% to 100% it instead ramps from for example 20% to 100%.
This issue has been reported in SuperSlicer
https://github.com/supermerill/SuperSlicer/issues/4195
Created a Spiral Vase slice that is limited by flow rate. Observed Flow Color scheme of the slice to verify that flow rate is now scaled from and to the selected percentage.
> Add minimum flow rates for spiral vase transitsions

- src/slic3r/GUI/NotificationManager.cpp
position of close button changes existence of minimize button. rendering close button before minimize button causing issue.
just changed order to fix it
before
https://github.com/user-attachments/assets/b48de02c-a66d-4e1f-a465-b2e8a3dd6347
after
https://github.com/user-attachments/assets/d31223b4-ba3d-465b-9d3f-4e6256836da6
> Fix shaky close button on notification

- src/libslic3r/GCode/WipeTower.cpp
- src/libslic3r/GCode/WipeTower.hpp
and modify the overlap of wall and infill for wipe tower jira:none
cherry picked from commit bambulab/BambuStudio@4db196b11f052d6a7a7c7a8aafe0d2b34a7d2d80
- Optimize the starting position of the printing wiper tower after material change, the initial print on the wipe tower sometimes had under-extrusion issues, and all layers of wipe tower have the same starting position, increasing the risk of collision. This optimization distributes the initial extrusion over four corners, reducing the accumulation of defects.
- Reducing the rivet length between the wipe tower's outer wall and infill to 0mm minimizes the risk of collision when switching between printing infill and outer walls.
> ENH: modify the start pos of wall for wipe tower[affects BBL machines only]

- src/libslic3r/PrintConfig.cpp
Though code uses default jerk value if the parameter is set to zero, some parameters wasn't allow to have zero. This PR allows zero value for them.
> Allow default acceleration/jerk for all parameters.

- src/libslic3r/PrintConfig.cpp
- src/libslic3r/PrintConfig.hpp
- src/slic3r/GUI/Plater.cpp
- Fix crash when selected bed type is not supported by current version. This could happen if you downgrade Orca to old version that does not have that bed type.
- For example, if you ever run 2.3.0-beta and having current bed type set to the last one from the drop down, then if you use 2.2 again the app will crash during startup.
- This PR fix this by falling back to default bed type if current value is out of range.
- This PR also fixes issue that current bed type is changed after upgrading to 2.3 from previous version, due to adding the supertack in the wrong place in the enum.
> Fix issues with supertack bed type

- resources/profiles/BBL.json
- resources/profiles/BBL/filament/AliZ/AliZ PA-CF @P1-X1.json
- resources/profiles/BBL/filament/AliZ/AliZ PETG @P1-X1.json
- resources/profiles/BBL/filament/AliZ/AliZ PETG-CF @P1-X1.json
- resources/profiles/BBL/filament/AliZ/AliZ PETG-Metal @P1-X1.json
- resources/profiles/BBL/filament/AliZ/AliZ PLA @P1-X1.json
- resources/profiles/OrcaFilamentLibrary.json
- resources/profiles/OrcaFilamentLibrary/filament/AliZ/AliZ PA-CF @System.json
- resources/profiles/OrcaFilamentLibrary/filament/AliZ/AliZ PA-CF @base.json
- resources/profiles/OrcaFilamentLibrary/filament/AliZ/AliZ PETG @System.json
- resources/profiles/OrcaFilamentLibrary/filament/AliZ/AliZ PETG @base.json
- resources/profiles/OrcaFilamentLibrary/filament/AliZ/AliZ PETG-CF @System.json
- resources/profiles/OrcaFilamentLibrary/filament/AliZ/AliZ PETG-CF @base.json
- resources/profiles/OrcaFilamentLibrary/filament/AliZ/AliZ PETG-Metal @System.json
- resources/profiles/OrcaFilamentLibrary/filament/AliZ/AliZ PETG-Metal @base.json
- resources/profiles/OrcaFilamentLibrary/filament/AliZ/AliZ PLA @System.json
- resources/profiles/OrcaFilamentLibrary/filament/AliZ/AliZ PLA @base.json
This PR demonstrates how to add filament profiles to Orca.
There are two parts:
1. Add filaments into the global Orca Filament Library, we shall define all the major parameters in `AliZ PLA @base.json` file
```
resources\profiles\OrcaFilamentLibrary\filament\AliZ\AliZ PLA @base.json
resources\profiles\OrcaFilamentLibrary\filament\AliZ\AliZ PLA @System.json
```
2. (Optional) Add machine specialized version of filament into vendor's profiles
```
resources\profiles\BBL\filament\AliZ\AliZ PLA @P1-X1.json
```
`AliZ PLA @P1-X1` is derived from `AliZ PLA @base` and includes only the modified parameters. Additionally, we must define `compatible_printers` for these profiles to inform OrcaSlicer which printer models they are optimized for
```json
{
"type": "filament",
"setting_id": "AliZPX1FSA04", …
```
> Add some AliZ filament profiles as example

- README.md
The readme didn't mention the new website as added in the 2.3.0-beta release:
> Orca Slicer has it's own official website now! https://www.OrcaSlicer.com
https://github.com/SoftFever/OrcaSlicer/releases/tag/v2.3.0-beta
> Mention orcaslicer.com as an official platform

- resources/profiles/Prusa/process/process_common_mk4s.json
Simply sets "exclude_object" to "1" in the base MK4S profile, which was missed in the initial translation from Prusa Slicer.
> Turn on exclude object for Prusa MK4S

- src/libslic3r/Measure.cpp
> Measure: Fix wrong diameter when selecting a circle feature

- src/slic3r/Utils/Flashforge.cpp
- src/slic3r/Utils/TCPConsole.hpp
When Flashforge AD5m is connected via Wi-fi, I have got frequent timeout errors on big models upload. 
So I increased timeouts for this operation from 10 seconds to 10 minutes, which definely helped. 
Fixes issue #4834 
Tested by large Ad5m community - it works.
> Increase upload timeout for Flashforge printers to 10 minutes

- resources/profiles/FlyingBear/machine/FlyingBear Ghost 6 0.4 nozzle.json
- resources/profiles/FlyingBear/machine/S1/FlyingBear S1 0.4 nozzle.json
Current values are wrong as previously was pointed out here https://github.com/SoftFever/OrcaSlicer/pull/7822
The head size of these two 3D printers is the same.
> Correct Flying Bear S1 / Ghost 6 extruder clearance radius

- BuildLinux.sh
Fixes #7803
If a Linux distribution is based on Ubuntu/Debian, it will compile Orca Slicer rather than giving a unsupported distro error.
> Allow compilation on distributions based on Ubuntu/Debian

- src/slic3r/GUI/MeshUtils.cpp
This copy frees the OpenGL VBOs and IBOs at the end of the loop and cause the crash.
Fix #8579
> Cut: Fix crash caused by unexpected copy of the cut island

- src/slic3r/GUI/Tab.cpp
Bambu Studio has an boolean option scan_first_layer and this is used in the G-Code to allow the slicer to enable or disable the first layer scan. 
Orca Slicer has all the logic for this in place but does not allow the user to edit this setting. 
This pull request simply enables a checkbox to control this in the printer profile on the basic tab under advanced. This option will be hidden by default unless the user selects to enable advanced settings or developer mode
This has compiled successfully, and I have confirmed that when the printer profile is saved the setting is restored on reloading.
> Enable checkbox in printer profiles to permit first layer scanning to be enabled/disabled via the slicer

- src/OrcaSlicer.cpp
- src/slic3r/GUI/GUI_App.cpp
Move init sys font into GUI_App, after logging has been set up properly
This avoid annoying messagebox if somehow failed to load font on windows, and write the message into log files instead:
Fix #8603
> Avoid message box if font load failure during startup

- src/libslic3r/LayerRegion.cpp
- src/libslic3r/PerimeterGenerator.cpp
- src/libslic3r/PerimeterGenerator.hpp
This PR aims to enhance OrcaSlicer's `Only one wall on top surfaces` feature.
Previously, walls were incorrectly generated if both `interface_shells` and `only_one_wall_top` are enabled where there should be a wall because(Ref to the screenshot)
[KayTag_Test.zip](https://github.com/user-attachments/files/19039228/KayTag_Test.zip)
> Enhancement "Only one wall on top surfaces": better support for interface_shells

- src/slic3r/GUI/PresetComboBoxes.cpp
Fix issue that filament combox could disappear under certain circumstances:
Fix #8628
> Fix filament combox disappearing

- localization/i18n/OrcaSlicer.pot
- localization/i18n/ca/OrcaSlicer_ca.po
- localization/i18n/cs/OrcaSlicer_cs.po
- localization/i18n/de/OrcaSlicer_de.po
- localization/i18n/en/OrcaSlicer_en.po
- localization/i18n/es/OrcaSlicer_es.po
- localization/i18n/fr/OrcaSlicer_fr.po
- localization/i18n/hu/OrcaSlicer_hu.po
- localization/i18n/it/OrcaSlicer_it.po
- localization/i18n/ja/OrcaSlicer_ja.po
- localization/i18n/ko/OrcaSlicer_ko.po
- localization/i18n/nl/OrcaSlicer_nl.po
- localization/i18n/pl/OrcaSlicer_pl.po
- localization/i18n/pt_BR/OrcaSlicer_pt_BR.po
- localization/i18n/ru/OrcaSlicer_ru.po
- localization/i18n/sv/OrcaSlicer_sv.po
- localization/i18n/tr/OrcaSlicer_tr.po
- localization/i18n/uk/OrcaSlicer_uk.po
- localization/i18n/zh_CN/OrcaSlicer_zh_CN.po
- localization/i18n/zh_TW/OrcaSlicer_zh_TW.po
- src/slic3r/GUI/Plater.cpp
Changing "% d" to " %d".  Also, "non-zero" with an hyphen.
> Fix typo on format string

- localization/i18n/OrcaSlicer.pot
- localization/i18n/ca/OrcaSlicer_ca.po
- localization/i18n/cs/OrcaSlicer_cs.po
- localization/i18n/de/OrcaSlicer_de.po
- localization/i18n/en/OrcaSlicer_en.po
- localization/i18n/es/OrcaSlicer_es.po
- localization/i18n/fr/OrcaSlicer_fr.po
- localization/i18n/hu/OrcaSlicer_hu.po
- localization/i18n/it/OrcaSlicer_it.po
- localization/i18n/ja/OrcaSlicer_ja.po
- localization/i18n/ko/OrcaSlicer_ko.po
- localization/i18n/nl/OrcaSlicer_nl.po
- localization/i18n/pl/OrcaSlicer_pl.po
- localization/i18n/pt_BR/OrcaSlicer_pt_BR.po
- localization/i18n/ru/OrcaSlicer_ru.po
- localization/i18n/sv/OrcaSlicer_sv.po
- localization/i18n/tr/OrcaSlicer_tr.po
- localization/i18n/uk/OrcaSlicer_uk.po
- localization/i18n/zh_CN/OrcaSlicer_zh_CN.po
- localization/i18n/zh_TW/OrcaSlicer_zh_TW.po
- src/libslic3r/PrintConfig.cpp
The strings were marked as "c-format" by default, making them fail the pull checks when translated.
> Add markers to allow translation of strings with '%'

- resources/profiles/Artillery/machine/Artillery Genius 0.4 nozzle.json
- resources/profiles/Artillery/machine/Artillery Genius Pro 0.4 nozzle.json
- resources/profiles/Artillery/machine/Artillery Sidewinder X1 0.4 nozzle.json
- resources/profiles/Artillery/machine/Artillery Sidewinder X2 0.4 nozzle.json
- Fixed bed-size of Genius (Pro) profile.
- Fixed default retraction values for the Artillery Genius (Pro) 0.4 profile, which were set too high for this direct-drive machine.
- Slightly increased default retraction value for Sidewinder X1 & X2, to match the Genius profiles. Tested values on all machines.
- Matching minimum layer height for Genius & Sidewinder profiles.
- Fixed line endings & indentation.
Tested on Genius & Sidewinder printers.
> Update Artillery Genius & Sidewinder profiles

- src/libslic3r/GCode.cpp
Reverts SoftFever/OrcaSlicer#8681
> Revert "Bug fix: Check for air filtration support on the printer level before emitting air filtration gcode command"

- src/slic3r/GUI/UnsavedChangesDialog.cpp
The issue is caused by #7573, the order of the combox no longer matches the order of enum `Preset::Type`, which breaks `DiffPresetDialog::get_left_preset_name` and `DiffPresetDialog::get_right_preset_name`, which rely on the combox order:
https://github.com/SoftFever/OrcaSlicer/blob/36a5a14507db6cdecbfc9b0d2768f06b18123f30/src/slic3r/GUI/UnsavedChangesDialog.cpp#L2384-L2394
This PR fixes this by using `std::find_if` instead so it no longer relies on the enum order.
Fix #7991
Fix #8632
Fix #8674
Fix #8678
Fix #8715
Fix #8732
> Fix preset transfer crash

- src/libslic3r/Print.cpp
- src/slic3r/GUI/Plater.cpp
When launching the software and directly loading a GCode file, the GCode preview may lose a lot of information. This happens because `GCodeProcessor::s_IsBBLPrinter` is set to true by default, causing the GCode to be loaded following Bambu's rules.
Before
After
> Launching and directly loading GCode will result in missing information.

- src/libslic3r/Preset.cpp
- src/libslic3r/Preset.hpp
- src/slic3r/GUI/Tab.cpp
…t this custom profile won't be visible automatically for all printers.
When users save custom filament profiles, if the base profile is from the Orca Filament Library, these user profiles will automatically become visible to all printers, which can be annoying.
To address this, we will ensure that new user profiles derived from system profiles (from the Orca Filament Library) are automatically set to be visible only to the selected printer model.
Users can also manually adjust the compatibility of filament profiles in the filament settings.
> Limit visibility of custom filament profiles based on OrcaFilamentLibrary to currently selected printer only

- localization/i18n/ca/OrcaSlicer_ca.po
- localization/i18n/cs/OrcaSlicer_cs.po
- localization/i18n/de/OrcaSlicer_de.po
- localization/i18n/en/OrcaSlicer_en.po
- localization/i18n/es/OrcaSlicer_es.po
- localization/i18n/fr/OrcaSlicer_fr.po
- localization/i18n/hu/OrcaSlicer_hu.po
- localization/i18n/it/OrcaSlicer_it.po
- localization/i18n/ja/OrcaSlicer_ja.po
- localization/i18n/ko/OrcaSlicer_ko.po
- localization/i18n/nl/OrcaSlicer_nl.po
- localization/i18n/pl/OrcaSlicer_pl.po
- localization/i18n/pt_BR/OrcaSlicer_pt_BR.po
- localization/i18n/ru/OrcaSlicer_ru.po
- localization/i18n/sv/OrcaSlicer_sv.po
- localization/i18n/tr/OrcaSlicer_tr.po
- localization/i18n/uk/OrcaSlicer_uk.po
- localization/i18n/zh_CN/OrcaSlicer_zh_CN.po
- localization/i18n/zh_TW/OrcaSlicer_zh_TW.po
I believe one of my patches removed a trailing space, but I forgot to update the .po files.  Restoring the translations.
> Restore translations for string with removed space at the end

- resources/profiles/Creality/machine/Creality Hi 0.4 nozzle.json
- resources/profiles/Creality/machine/Creality Hi 0.6 nozzle.json
Fix extruder_clearance_height_to_lid parameter for Creality Hi.
Profile parameter comes from Creality Print but it is not correct.
This change will allow printing by object in different colors.
Before
After
> Fix Creality Hi extruder_clearance_height_to_lid

- resources/profiles/Co Print.json
- resources/profiles/Co Print/filament/CoPrint Generic ABS.json
- resources/profiles/Co Print/filament/CoPrint Generic PETG.json
- resources/profiles/Co Print/filament/CoPrint Generic TPU.json
Description:
This PR adds new print profiles for TPU, ABS, and PETG to the Co Print ChromaSet profile.
Changes Made:
Added TPU, ABS, and PETG material settings to the resources/profiles/Co Print.json file.
Optimized filament paths and parameters to align with Co Print ChromaSet.
Adjusted settings to maintain compatibility with the existing PLA profile.
These updates will enhance the printing experience for Co Print ChromaSet users by providing optimized profiles for a wider range of materials.
> Added TPU, ABS, and PETG Profiles for Co Print ChromaSet-2

- src/slic3r/GUI/SelectMachine.cpp
The BambuStudio string this function queries would never be present in OrcaSlicer generated gcode, as it's replaced with the equivalent OrcaSlicer versioning string.  
This update makes it look for the OrcaSlicer string instead, so that it doesn't read through the potentially hundreds of thousands of unrelated gcode lines after line 2.  This fixes the issues seen with responsiveness when opening the print dialog with large models, as the function is repeatedly called.
This fixes issue #3893.
> Fix query of gcode's slicer version.

- src/libslic3r/GCode.cpp
> Fix wrong first layer temperature when ooze prevention and print-by-obj are enabled

- src/BaseException.cpp
The original crash report only output registers for x86 build. This PR add similar register output for x64 builds too.
This should help debugging windows crashes.
> Output x64 registers to windows crash report too

- deps/MPFR/MPFR.cmake
Needed an update, the old link is 404.
The old version is no longer available for download.
> Update to mpfr-4.2.2.tar.bz2

- src/slic3r/Utils/Flashforge.cpp
- src/slic3r/Utils/Flashforge.hpp
- src/slic3r/Utils/TCPConsole.cpp
- src/slic3r/Utils/TCPConsole.hpp
- Added TCP Queue Delay parameter to delay TCP messages in queue
- Updated Flashforge Serial comms - Upload/Print to older Flashforge devices (AD3/AD4 etc) now working alongside FF Klipper devices
Tested and validated TCP Upload & Print on Adventurer 3 and Adventurer 5 with both small and large prints.
> Added TCP Queue Delay + Fixed Flashforge Serial comms

- src/libslic3r/PrintConfig.cpp
Current code 
```
void ReplaceString(std::string &resource_str, const std::string &old_str, const std::string &new_str)
{
std::string::size_type pos = 0;
while ((pos = resource_str.find(old_str)) != std::string::npos) {
resource_str.replace(pos, old_str.length(), new_str);
}
}
```
always search and replace from very beginning, thus endless replaces the same string in the case when `new_str `starts from the same sequence as `old_str`, like `some_key` -> `some_key_new`.
This fix advances searching position:
```
while ((pos = resource_str.find(old_str, pos)) != std::string::npos) {
resource_str.replace(pos, old_str.length(), new_str);
pos += new_str.length(); //advance position to continue after replacement
}
```
Credits to ChatGPT, DeepSeek and Grok. They all found the problem and provided …
> Fix endless loop in ReplaceString

- .github/workflows/build_all.yml
This should cause the build workflow to run when any changes are made under the flatpak folder. One example of this being needed is the PR #8964 not causing the build workflow to be triggered.
> Trigger build workflow when flatpak changes are made

- src/libslic3r/Model.cpp
- src/libslic3r/Model.hpp
- src/slic3r/GUI/3DScene.cpp
- src/slic3r/GUI/PartPlate.cpp
Fix #8218
Before:
After:
Note: there is still an issue that you still cannot slice if object below plate overlaps exclusion area. It won't be easy to fix and also will be computational costy, so I won't try to solve this in this PR yet.
> Only consider part above plate when checking for object outside

- src/slic3r/GUI/PresetComboBoxes.cpp
Fix #8895
In some cases, updating multiline text fields during dialog pop up crashes GTK. This PR changes the order by updating the fields first then show the UI.
> Fix filament editor crash on Linux

- src/slic3r/GUI/PrinterWebView.cpp
- src/slic3r/GUI/PrinterWebView.hpp
This should make Linux user life a bit easier so Orca don't crash unless switch to device tab manually.
> Do not loade web page until switching to device page

- src/libslic3r/PrintObject.cpp
- src/libslic3r/libslic3r.h
jira: STUDIO-8588
Change-Id: Ia566fa14f7f786ff905fc3484885634811a6d686 (cherry picked from commit bambulab/BambuStudio@82c72b19bdaa5d1dd3b7e62faa87a8e9b471ac0a)
Fix #9035
Now the file size is reduced a lot when arc fitting is enabled:
> FIX: enable circle fitting of tree support with larger threshold

- resources/profiles/Sovol/filament/Sovol SV06 ACE PLA.json
When the Sovol SV06 ACE 0.2/0.6/0.8 nozzle configs were split out of the default 0.4 nozzle config, it looks like no PLA filament was configured as compatible with  the 0.2 nozzle machine. There isn't currently a dedicated 0.2 nozzle version of this filament, so I'm just associated the regular Sovol PLA one.
N/A
Verified PLA filament profiles can now be selected for the Sovol SV06 ACE 0.2 nozzle machine.
> Mark SV06 ACE PLA compatible with 0.2 nozzle

- src/slic3r/GUI/Plater.cpp
Disable firmware retraction when running retraction calibration.
https://github.com/SoftFever/OrcaSlicer/issues/8332
> Disable FirmwareRetraction in RetractionTest

- src/slic3r/GUI/calib_dlg.cpp
It looks like start and end values are swapped. Start needs to be greater than end. If you try to hit "Ok" for the default values, it results in this error:
```
Please input valid values:
Start temp: <= 350
End temp: >= 170
Start temp > End temp + 5)
```
> Fix PCTG calibration temperatures

- src/slic3r/GUI/GUI_ObjectTable.cpp
> Fix brim type combox in object table

- src/libslic3r/GCode.cpp
Fixes Bridge and Perimeter roles' speed which were being clamped using path.mm3_per_mm instead of _mm3_per_mm. This results in ignoring any flow multipliers in _mm3_per_mm (like print_flow_ratio, bridging flow ratio, etc.), so we could exceed the user’s filament_max_volumetric_speed.
This change should ensure bridging and overhanging perimeter segments do not overshoot the actual volumetric cap if these flow multipliers are active.
Now this lines up with the rest of _extrude(), which already uses _mm3_per_mm for volumetric speed capping.
This should solve issues similar to https://github.com/SoftFever/OrcaSlicer/issues/7307 where max_volumetric_flow is passed, but this doesn't address filament_flow_ratio being used > 1 to extrude more plastic intentionally instead of as a corrective …
> Fix bridge & perimeter paths to use set flow ratios in Volumetric Speed Capping

- localization/i18n/pt_BR/OrcaSlicer_pt_BR.po
The pt-BR translation was using "..." which looks worse and takes more space than the Unicode "…".
> Use the correct Unicode codepoint for ellipsis in pt-BR

- src/libslic3r/GCode/ExtrusionProcessor.hpp
On some edge cases mostly observed when curled perimeter detection is enabled, and the perimeter speeds are limited due to flow rate limits, the resulting overhang speed calculation creates a speed ramp up. This could also happen with the curled perimeter detection being disabled too.
This happens because the calculated overhang speed is not limited by the actual print speed but instead calculated by the speed thresholds in the overhang % boxes. Typically this is not an issue, as the overhang speed should be set to less than the profile print speeds; however when slowing down due to flow rates, this is not the case.
This PR addresses this by clamping the resulting speed to the min between the flow rate limited external perimeter speed and calculated slowdown for curled overhang speeds. …
> Fix speed up during overhang slowdown when curled perimeters is enabled.

- BuildLinux.sh
The existing support to use a specified number of cores for compilation was setting the variable `CMAKE_BUILD_PARALLEL_LEVEL` but not exporting it, so CMake was not being affected. In a 16 core SMT 32 GiB RAM system this meant the default concurrency was used and RAM was very soon exhausted while compiling.
The `-1` option did work (as it was exporting the value).
Tested that `./BuildLinux.sh -dsi -j 8` now can build OrcaSlicer in my machine without running out of RAM.
> Fix -j to export CMAKE_BUILD_PARALLEL_LEVEL.

- localization/i18n/de/OrcaSlicer_de.po
- localization/i18n/fr/OrcaSlicer_fr.po
de and fr translated "in" as "inside", should be "inches".  I removed the wrong translation in french, and marked other translations so that they can be reviewed.
> Fix the translation of "in" (inches) in fr, de

- src/slic3r/GUI/Plater.cpp
By remove the auxiliary directory when sending for printing
cherry picked from commit bambulab/BambuStudio@6eb533019eda9c810f3eaf80a81fd7698ebb4578
Thanks BambuLab.
> Make gcode 3mf file smaller when sending to BBL printers

- src/libslic3r/GCode/ConflictChecker.cpp
cherry picked from commit bambulab/BambuStudio@b952006e4db49f00054cc2ac539074222c890d08
Fix #9094
> FIX: prevent dead loop of conflict checker

- src/slic3r/GUI/Plater.cpp
such as AMS group selection.
Fix #8656 
Could not reproduce this myself, need verification from original poster, and anyone who has the same setup.
> Make sure sidebar is not triggered by child notebook tab changes 

- src/slic3r/GUI/WipeTowerDialog.cpp
Fixes https://github.com/SoftFever/OrcaSlicer/issues/8342
Some printers require extreme flushes to prevent color bleeding or weird mixed material issues. This change simply bumps the UI constraint by an order of magnitude. 
Filament manufacturers rejoice at the waste!
I have made no attempt to test this change or its impact on purge/flushing calculations.
> Remove MAX_FLUSH_VALUE

- src/slic3r/GUI/GCodeViewer.cpp
Hotfix for PR #8198 (see https://github.com/SoftFever/OrcaSlicer/pull/8198#issuecomment-2767451338).
> hotfix: avoids legend-viewer horizontal overexpansion on linux

- src/libslic3r/GCode.cpp
- src/libslic3r/PrintConfig.cpp
- src/slic3r/GUI/Tab.cpp
Followup to  **Introduce option to control one wall draft shield #8562** 
Apply single_loop_draft_shield also to skirt itself, thus allowing one loop limited draft shield and skirt as well, saving filament and still allowing easy skirt removing. Reorder config items in settings.
> Apply single_loop_draft_shield also to skirt

- src/slic3r/GUI/ConfigManipulation.cpp
This PR fixes some skirt settings GUI  bugs:
- "Single loop after first layer" is not visible only if "Draft shield" is enabled even thou it has an effect on skirt also by the merging of PR #9298
- "Skirt height" is not disabled (as initially intended) if "Draft shield" is enabled
The fix:
- show "Single loop after first layer" if skirt is enabled
- disable "Skirt height" if "Draft shield" is enabled
> Skirt settings GUI fixes

- src/slic3r/GUI/PartPlate.cpp
After adding "Move to front" icon, vertical alignment of icons broken on circular shaped plates
• Removed gap_top from calculation to get perfect center
• Added a reminder near calc_vertex_for_icons that recommends change icon number for future changes
Before-After
> Fix: Bed icons not vertically centered on circular shaped plates

- src/slic3r/GUI/3DBed.cpp
• Matches colors of bed plate with 3D model and bed plate without 3D model
• Adds dark mode support for bed plate without 3D model
I have to shift color to darker tone after matching colors because flat shader caused much brighter color
Before
After
After - Before
> Fix: Correct color of bed plates without 3D model

- src/slic3r/GUI/Gizmos/GLGizmoBrimEars.cpp
- src/slic3r/GUI/Gizmos/GLGizmoBrimEars.hpp
- src/slic3r/GUI/ImGuiWrapper.cpp
- You are now able to select multiple brim ears in brim paint tool with shift+left mouse click.
- Fix the brim size preview when dragging the brim size slider. Now the size of selected brim will update while dragging the slider.
- Fix a memory leaking when moving cursor on the model
> Fix brim ear paint memory leaking & multi-selection with shift+left click

- src/slic3r/GUI/Gizmos/GLGizmoBrimEars.cpp
- src/slic3r/GUI/Gizmos/GLGizmoBrimEars.hpp
- src/slic3r/GUI/Gizmos/GLGizmosManager.cpp
1. Change the section view shortcut to Alt+mouse wheel, makes it consistent with other paint gizmos such as support/seam/color paint
2. Add new ctrl+mouse wheel up/down shortcut to change the size of the brim, similar to other paint gizmos that uses the same shortcut to change brush size
> Improve brim paint gizmo shortcuts

- src/slic3r/GUI/Gizmos/GLGizmoPainterBase.cpp
If object has modifier, in some paint gizmos such as seam and support paint, if you click the modifier, the gizmo will exit:
This PR fixes this issue so the gizmo won't accidentally exit.
> Don't allow selection change in paint gizmo

- src/libslic3r/GCode.cpp
- src/libslic3r/GCode.hpp
Fix #9109
don't modify `last_pos`, otherwise it could move out of plate/to wrong places and cause issue
Old:
New:
> Fix wrong travel before printing first skirt point

- src/slic3r/GUI/Plater.cpp
> Fix flow calibration overlapping objects with nozzle > 0.4mm

- src/libslic3r/GCode.cpp
> Fix `M486` still presented even with obj exclusion disabled

- src/libslic3r/GCode.cpp
> Fix wipe tower initial movement when switching extruder offsets

- src/slic3r/GUI/WebGuideDialog.cpp
`m_OrcaFilaLibPath` is used in `LoadProfileFamily` so it should be initialized first
> Fix orca filament lib load

- src/libslic3r/Algorithm/RegionExpansion.cpp
Fix #9281
Cherry picked from prusa3d/PrusaSlicer@5f843cc93470c96483abcbd47cf8ee5fe38dffe2 and prusa3d/PrusaSlicer@a3f75133c8baead6f8d7bb01722a6bfcdc2e9038, huge thanks to Prusa!
> Fix rare crash when calculating bridge expansion

- src/slic3r/GUI/GLCanvas3D.cpp
I use mostly "Add model" from context menu but current code blocks right click if an object selected that forces me to unnecessary left click to deselect objects first 
Code changes allows right click on empty space while an object selected
deselects objects then shows context menu
tried pan, multiple selection etc. and it works as expected
Current code has minor issues for right click but can be blocked. right click on bed icons and toolbar
> Allow right click on empty space while an object selected

- README.md
'www.orcaslicer.com' creates certificate warnings, and ultimately redirects to 'orcaslicer.com' anyway. Thus, I opened this PR to remove the subdomain.
I clicked the new link.
> Remove 'www' subdomain from official link to avoid certificate warnings

- src/slic3r/GUI/3DBed.cpp
I'm not fully sure condition is proper but it works as expected
Fixes default bed shape position for circular beds without 3D model
BEFORE - AFTER
> Fix: Circular bed shape (without 3D model) not rendering in correct position

- src/libslic3r/PrintConfig.cpp
Small area Flow Compensation Model demands semicolon at the each line end. Correct description to match actual behavior.
> Small area semicolon description.

- src/slic3r/GUI/fts_fuzzy_match.h
Currently option search brings matches where letters are nor adjacent, thus revealing many not relevant options:
This PR outputs only matches with exact substring:
> Search whole option string.

- localization/i18n/list.txt
replace AMSMappingPopup.cpp with AmsMappingPopup.cpp (the case-sensitive filename)
in localization/i18n/list.txt its called AMSMappingPopup.cpp but the actual filename is AmsMappingPopup.cpp, running `run_gettext.sh --full` will produce an error because of a case-sensitive mismatches. 
I opened issue #9065 before, because I wasn't sure the problem is the list or the filename. But on a second look it's probably the list…
> fix case-sensitive mismatches in localization/i18n/list.txt

- src/libslic3r/Extruder.hpp
- src/libslic3r/GCode.cpp
Update: Due to lots of noise and confusion from people having similar issues but not quite related, here is a distilled version of what's the PR And what it fixes:
If filament_flow_ratio is strictly bringing an underfeeding extruder up to the “true geometry volume,” then in physical terms, you are not actually overextruding – you’re merely achieving what the slicer’s geometry said you should. In that scenario:
1.	Geometry says: 0.12 mm³/mm
2.	Your extruder hardware was previously underfeeding by 10%. Without a 1.10 filament ratio, it would only deliver ~0.108 mm³/mm physically.
3.	By setting filament_flow_ratio = 1.10, you correct the hardware so that physically 1.0 mm of extruder steps now yields 0.12 mm³/mm for real.
4.	Result: The nozzle truly extrudes 0.12 mm³/mm, matching the …
> Fixed an issue where the Max Volumetric Speed doesn't consider the Filament Flow Ratio

- src/slic3r/GUI/ParamsPanel.cpp
• Add a cube model
• Right click to object in canvas > Edit Process Settings
• Removed AddStretchSpacer() after advanced toggle
• Slightly decreaced distance between tip_arrow and global / objects switch
videos starts a bit late but its in loop
BEFORE
AFTER - Only Global / Objects switch moves
> Fix: Prevent move of Advanced toggle when highlighting Global / Objects switch

- src/slic3r/GUI/PlateSettingsDialog.cpp
> Fix alignment of plate name text an its input box on plate settings window

- resources/profiles/OrcaFilamentLibrary.json
- resources/profiles/OrcaFilamentLibrary/filament/Overture/Overture ABS Basic @System.json
- resources/profiles/OrcaFilamentLibrary/filament/Overture/Overture ABS Basic @base.json
- resources/profiles/OrcaFilamentLibrary/filament/Overture/Overture TPU @System.json
- resources/profiles/OrcaFilamentLibrary/filament/Overture/Overture TPU @base.json
This PR adds support for Overture ABS and TPU filament profiles across all printers. 
- Created new filament profile files for Overture ABS and TPU
- Updated `OrcaFilamentLibrary.json` to reference these profiles
- Located in: `/resources/profiles/OrcaFilamentLibrary/filament/Overture`
Improves accessibility and convenience for users printing with Overture filaments.
Tested basic compatibility across multiple printer configs to ensure smooth integration.
Sorry for the second one
> adding overture TPU & ABS profiles

- src/slic3r/GUI/Gizmos/GLGizmoRotate.cpp
Fixes https://github.com/SoftFever/OrcaSlicer/issues/3357
BEFORE
• Line colors and directions not matches with Axis and that makes confusion
AFTER
• No color, no confusion
• Didn't used proper colors on lines because that makes more confusing. Grabber and line color will not match if lines has correct color
> Fix: Rotation gizmo axis line colors not matches with axis colors

- src/slic3r/GUI/PhysicalPrinterDialog.cpp
- src/slic3r/GUI/PhysicalPrinterDialog.hpp
- src/slic3r/GUI/Tab.cpp
- src/slic3r/GUI/Tab.hpp
- src/slic3r/GUI/Widgets/StateColor.cpp
i decided to send this PR https://github.com/SoftFever/OrcaSlicer/pull/8184 as small parts since it needs a lot work. i will limit that PR as "style management"
This PR matches style of wxButtons that exist on parameters and printer connection window
• Removed icons
• Matched button widths with parameter boxes
• Makes buttons look same on all platforms
• Added a min width to buttons that same with width of input box
• Used "Refresh ..." instead "Refresh Printers" on Obico
Before-After
Before-After
• Used "Set ..." for Ramming Parameters button
Before-After
Before-After
Before-After
> Modernize wxButtons on Parameters & Physical Printer window

- src/libslic3r/GCode.cpp
- src/libslic3r/PrintConfig.cpp
The empty assignments are unnecessary.  Removing them makes the code smaller.
I have added translation markers to the commented-out empty strings so that if they are actually filled someday, they will be added to translation.
> Remove empty string initializations

- src/slic3r/GUI/PartPlate.cpp
limited max grid size to 100mm, i can add more if needed. didnt want to use "while"
• Simplified calculation and standardized steps
| Bed short edge length | Step x Count = Main Grid Size |
| :--- | :--- |
|   < 600mm |  10 x 5 = 50mm |
| >= 600mm |   20 x 5 = 100mm |
| >= 1200mm |  50 x 5 = 250mm |
| >= 6000mm | 100 x 5 = 500mm |
1000x1000 bed plate (Ginger G1)
BEFORE - 33 gridlines with non standard step
AFTER - 50 gridlines with 20mm grid size. Distance between thick lines 10 cm
10000x10000(10mt x 10mt) bed plate
BEFORE
AFTER  - 100 gridlines with 100mm grid size.  Distance between thick lines 50 cm
> Fix: Grid size calculation wrong on large scale

- localization/i18n/ca/OrcaSlicer_ca.po
- localization/i18n/cs/OrcaSlicer_cs.po
- localization/i18n/de/OrcaSlicer_de.po
- localization/i18n/en/OrcaSlicer_en.po
- localization/i18n/es/OrcaSlicer_es.po
- localization/i18n/fr/OrcaSlicer_fr.po
- localization/i18n/hu/OrcaSlicer_hu.po
- localization/i18n/it/OrcaSlicer_it.po
- localization/i18n/ja/OrcaSlicer_ja.po
- localization/i18n/ko/OrcaSlicer_ko.po
- localization/i18n/lt/OrcaSlicer_lt.po
- localization/i18n/nl/OrcaSlicer_nl.po
- localization/i18n/pl/OrcaSlicer_pl.po
- localization/i18n/sv/OrcaSlicer_sv.po
- localization/i18n/tr/OrcaSlicer_tr.po
- localization/i18n/zh_CN/OrcaSlicer_zh_CN.po
- localization/i18n/zh_TW/OrcaSlicer_zh_TW.po
I found many duplicate strings (translation identical to source) on the translation files.
This makes no difference for the end-user, but makes the work harder for the translator, since the translation tools show these strings as already translated.
Most of the duplicate strings were inherited from BambuStudio.
> Remove non-translated translations

- flatpak/io.github.softfever.OrcaSlicer.yml
- src/slic3r/GUI/2DBed.hpp
Fixes #9544 compile error with `SLIC3R_PCH=OFF`, meaning a successful build could be only achieved with `SLIC3R_PCH=ON` introduced in a91ee67ac7f2936f3ec3fb7522c07d0f7a6b4ca6.
Compiler errors with `SLIC3R_PCH=OFF`:
```bash
orca-slicer/src/OrcaSlicer.cpp:3240: note: at offset 16 into object ‘wipe_tower_y’ of size 16
3240 |                     ConfigOptionFloat wipe_tower_y(wipe_y_option->get_at(index) + wipe_offset(1));
[468/474] Building CXX object src/slic3r/CMakeFiles/libslic3r_gui.dir/GUI/BedShapeDialog.cpp.o
FAILED: src/slic3r/CMakeFiles/libslic3r_gui.dir/GUI/BedShapeDialog.cpp.o 
/usr/lib/ccache/c++ -DBOOST_ATOMIC_NO_LIB -DBOOST_ATOMIC_STATIC_LINK -DBOOST_CHRONO_NO_LIB -DBOOST_CHRONO_STATIC_LINK -DBOOST_CONTAINER_NO_LIB -DBOOST_CONTAINER_STATIC_LINK -DBOOST_DATE_TIME_NO_LIB …
```
> Fixes compile error with `SLIC3R_PCH=OFF`

- src/slic3r/GUI/Tab.cpp
- src/slic3r/GUI/Tab.hpp
Replaces wxCheckbox with custom class Checkbox like other parameter checkboxes that used on UI
Matches style of checkboxes on all platforms
BEFORE
AFTER
> Match style of checkboxes on Material Settings > Setting Overrides

- src/imguizmo/ImGuizmo.cpp
- src/libslic3r/Color.hpp
- src/slic3r/GUI/2DBed.cpp
- src/slic3r/GUI/3DBed.cpp
- src/slic3r/GUI/3DBed.hpp
- src/slic3r/GUI/GLCanvas3D.cpp
- src/slic3r/GUI/Gizmos/GLGizmoBase.cpp
- src/slic3r/GUI/Gizmos/GLGizmoCut.cpp
- src/slic3r/GUI/Gizmos/GizmoObjectManipulation.cpp
I will send a separate PR for grabbers when i finish
• Used fine tuned colors instead raw colors for axes
• Matches all axis colors on UI (Navigation cube, axes on plate, gizmos, grabbers, 2D bed on set shape dialog)
• Makes all axes colors controllable from one place. Color.hpp
• Makes navigation cube axis text uppercase like on transform widgets
• Removes arrows from axes of main origin
• Removes arrows from axes of navigation cube
• Removes arrows from axes of 2D bed on set bed shape dialog
About arrows
• Line that drew from origin to a point already shows a direction. so no arrows needed on axes
• Axes looks much more modern without arrows 
About change on transform widgets
• I have to use TextColored instead TextAlignCenter on gizmos otherwise i have to change code on …
> Color & shape improvements for Axes

- src/libslic3r/GCode/ToolOrdering.cpp
> Fix crash when `start_extruder_id` is empty

- src/slic3r/GUI/Plater.cpp
Brackets were missing when merging BBS 1.8 code, which cause crash when switching back to prepare tab after clicking the support paint icon in preview:
1. Paint support on any object
2. Switch to preview tab
3. Switch to object list
4. Click the support painting icon in object list
5. Switch back to prepare tab
6. Crash
> Fix crash when switching back to prepare tab after clicking the support paint icon in preview

- src/slic3r/GUI/EditGCodeDialog.cpp
- src/slic3r/GUI/GUI_Utils.cpp
- src/slic3r/GUI/GUI_Utils.hpp
Fix #9385
FYI @Ocraftyone @discip
I also reverts https://github.com/SoftFever/OrcaSlicer/commit/aef74ab0050783bfaf7d67f531dd6877008e843c (https://github.com/SoftFever/OrcaSlicer/pull/3417#issuecomment-1886793312) because I don't think that really matters, given you are not clicking the plus button while changing the selected variable at the same time. And it's not possible to set the button at a fixed position since it's resizeable now. And the resizability brings more benifits than having a perfect fixed plus button.
Now the dialog can be expanded and shrinked, and its initial size should now never exceeds the usable size of your monitor:
> Make Custom GCode Editor resizable

- src/slic3r/GUI/ConfigManipulation.cpp
This PR makes "Support critical regions only" parameter visible for all auto tree support styles. This parameter was hidden when "Organic" and "Default" style is used although this parameter's setting is taken into account for these styles also.
> Organic tree support GUI fix

- src/slic3r/GUI/Tab.cpp
- src/slic3r/GUI/Tab.hpp
uses wxStaticText instead to fix checkbox label not appears on linux and macos
also adds click event to text of checkbox
let me know if you dont prefer this method
note
i assume double click event not defined for checkbox thats why has issue described before
i will send an another pr for checkboxes
> fixes for dependencies tab

- src/libslic3r/PrintConfig.cpp
- src/slic3r/GUI/CameraPopup.cpp
- src/slic3r/GUI/ConfigWizard.cpp
- src/slic3r/GUI/GCodeViewer.cpp
- src/slic3r/GUI/Gizmos/GLGizmoCut.cpp
- src/slic3r/GUI/Gizmos/GLGizmoMeasure.cpp
- src/slic3r/GUI/Gizmos/GLGizmoSimplify.cpp
- src/slic3r/GUI/Gizmos/GLGizmoText.cpp
- src/slic3r/GUI/Gizmos/GizmoObjectManipulation.cpp
- src/slic3r/GUI/PrintOptionsDialog.cpp
- src/slic3r/GUI/StatusPanel.cpp
- src/slic3r/GUI/StepMeshDialog.cpp
- src/slic3r/GUI/Widgets/AMSControl.cpp
There are some symbols marked for translation that are the same on all languages.
> Remove markers from strings that don't need to be translated

- src/libslic3r/PrintConfig.cpp
- src/slic3r/GUI/Field.cpp
- src/slic3r/GUI/Field.hpp
tested on windows 11
• Matches width with other parameters on all platforms
• Adds a function for resetting value system default (no color / transparent) with right click
• Matches UI style of button on Windows
---- • Matched style with buttons and used "Pick ..." as label. used 3 dots because its opens a dialog like on other buttons
---- • Added support for focus border and hover effects
BEFORE-AFTER - No color chosen
BEFORE-AFTER - Color chosen
> Improvements for Default color button in filament settings 

- src/slic3r/GUI/Tab.cpp
- src/slic3r/GUI/Tab.hpp
Fix crash illustrated in following gif:
This issue only happens that the project 3mf file, but not installed locally; Then when you new project, it will switch to a different printer profile that has only single extruder, which cause the extruder tabs been destroied, but the callback still holds an ref to the old tab, thus cause the crash.
> Fix new project crash on Windows if multi-extruder printer profile is edited

- linux.d/arch
- linux.d/debian
- linux.d/fedora
Fixes #4965[ SpaceMouse no longer working with Orca Slicer 2.0](https://github.com/SoftFever/OrcaSlicer/issues/4965) (except ClearLinux)
- added missing dependency `libspnav-dev`
- compiled
- started spacenav daemon: `sudo spacenavd`
- started OrcaSlicer
- actuated spacemouse
- build plate moved accordingly
> adds `libspnav-dev` dependency to `linux.d/debian`

- src/slic3r/GUI/GUI_ObjectList.cpp
Actually it's left click, not right. Also use word "repair" to make it consistent with other messages.
> Correct repair menu message

- BuildLinux.sh
- CMakeLists.txt
- linux.d/arch
Arch has switched to cmake 4.x breaking build process again - this PR fixes that for Arch only, because I wasn't sure what would happen if fix was applied with an older version of cmake present. 
This PR alone is not enough to build Orca on Arch - GCC 15 fixes are required too https://github.com/SoftFever/OrcaSlicer/pull/9643
Closes https://github.com/SoftFever/OrcaSlicer/issues/9147
> Fix building with cmake 4.x on Arch

- resources/profiles/Prusa/machine/Prusa CORE One HF 0.4 nozzle.json
- Adds `corexy` to CORE One 0.4 nozzle config
Closes #9678
> fix(coreone): adds printer structure

- resources/profiles/OrcaFilamentLibrary/filament/AliZ/AliZ PETG-CF @base.json
- resources/profiles/OrcaFilamentLibrary/filament/AliZ/AliZ PETG-Metal @base.json
- resources/profiles/OrcaFilamentLibrary/filament/base/fdm_filament_sbs.json
- scripts/orca_extra_profile_check.py
When set certain filament in AMS slots, such as AliZ PETG-CF, the filament dropdown will reset to empty when you open the setting dialog again. This PR fixes this issue.
> Make sure `filament_id` is not longer than 8 chars if the filament can be set in AMS

- src/slic3r/GUI/AboutDialog.cpp
Before
After - Banner and version text properly scaled
> Fix scaling on about dialog

- src/slic3r/GUI/MainFrame.cpp
BEFORE - AFTER
• Arrows rendered with normal size on %150 scaling
• Gap between dropdown button and its button rendered with correct gap. i assume 2 x FromDIP(1) not equal to  FromDIP(2) at %150 scaling
> Fix scaling on SideButton

- src/libslic3r/Fill/FillLine.cpp
- src/slic3r/GUI/ConfigManipulation.cpp
Line Infill doesn't work when `Maximum length of the infill anchor` is set below `0.05`, because it's using a condition with `params.dont_connect()` that doesn't make sense in this context.
Before:
After:
> Fix Line Infill with no anchor

- src/slic3r/GUI/GLCanvas3D.cpp
Tested on windows 11
Before - After at %150 scaling
```
float f_scale = get_scale();
#ifdef WIN32
const int dpi = get_dpi_for_window(wxGetApp().GetTopWindow());
f_scale *= (float) dpi / (float) DPI_DEFAULT;
#endif // WIN32
```
btw if this one proper method we can apply to
```
const float GLCanvas3D::get_scale() const
{
#if ENABLE_RETINA_GL
return m_retina_helper->get_scale_factor();
#else
return 1.0f;
#endif
}
```
so all gizmos scaled properly (at least on windows). most of them uses `imgui.push_toolbar_style(m_scale);` already but they not scaling because get_scale() returns 1.0 on non apple systems
not sure correct method for linux
alternatively we can create a new function then replace existing ones with testing
```
#include <wx/wx.h>
#include <wx/display.h>
float …
```
> Fix scaling on Plates toolbar for Windows

- README.md
This PR adds the official Twitter/X account mentioned in the README and https://orcaslicer.com to the fake website security alert (might have been missed in #9375) to clarify that real_OrcaSlicer is the only real account.
Previewed on GitHub
> add official Twitter/X account in security alert

- resources/profiles/Flashforge/machine/fdm_adventurer3_common.json
Updated position of purge line in start g-code for Adventurer 3. New FlashPrint shows out of build plate error but it has to be used to upload print to the printer. Bug and fix found by user @Amok1983.
File exported with this start g-code works fine with FlashPrint.
> Update Adventurer3 machine start g-code.json

- README.md
Instructions for building on Ubuntu used single quotes. Changed to use backticks so that Github applies the `code` style
Extremely small tweak. Just properly formats two places in the README with `code` styling.
N/A
N/A
> Use backticks instead of single quotes on code example in README.md

- src/slic3r/GUI/WebViewDialog.cpp
Fix error when drag-n-drop a file from network location to home screen on Windows:
> Fix error when drag-n-drop a file from network location to home screen

- src/libslic3r/Format/3mf.cpp
- src/libslic3r/Format/bbs_3mf.cpp
See https://guncadindex.com/wiki/techdocs/bambu/on-project-files/ for more details.
Now the `CreationDate`, `ModificationDate` and `DesignerUserId` are all set to empty when saving the 3mf.
> Remove sensitive data in 3mf files

- src/libslic3r/GCode.cpp
Generate the GCode for the skirt before the GCode for the wipe tower.
Before the change, the GCode for the wipe tower is generated before code generation for the skirt. See,
After the change, the GCode for the skirt is generated before the code for the wipe tower. See,
On the 2nd+ layer, the filament used as the last on the previous layer will be used to print the skirt. 
Manual checks.
> Generate GCode for skirt prior wipe tower.

- src/slic3r/Utils/CalibUtils.cpp
Disables thin wall detection on VFA test as it can cause incorrect seams to be placed in the model. This makes it consistent with what spiral mode is expecting.
> Disable detect thin wall for VFA test

- src/slic3r/GUI/AboutDialog.cpp
- src/slic3r/GUI/AmsMappingPopup.cpp
- src/slic3r/GUI/BindDialog.cpp
- src/slic3r/GUI/Calibration.cpp
- src/slic3r/GUI/CreatePresetsDialog.cpp
- src/slic3r/GUI/DownloadProgressDialog.cpp
- src/slic3r/GUI/GUI_ObjectTable.cpp
- src/slic3r/GUI/KBShortcutsDialog.cpp
- src/slic3r/GUI/ModelMall.cpp
- src/slic3r/GUI/MsgDialog.cpp
- src/slic3r/GUI/MultiMachinePage.cpp
- src/slic3r/GUI/ObjColorDialog.cpp
- src/slic3r/GUI/ParamsPanel.cpp
- src/slic3r/GUI/PlateSettingsDialog.cpp
- src/slic3r/GUI/Preferences.cpp
- src/slic3r/GUI/PrintOptionsDialog.cpp
- src/slic3r/GUI/PrivacyUpdateDialog.cpp
- src/slic3r/GUI/PublishDialog.cpp
- src/slic3r/GUI/RecenterDialog.cpp
- src/slic3r/GUI/ReleaseNote.cpp
- src/slic3r/GUI/SavePresetDialog.cpp
- src/slic3r/GUI/SelectMachine.cpp
- src/slic3r/GUI/SendMultiMachinePage.cpp
- src/slic3r/GUI/SendToPrinter.cpp
- src/slic3r/GUI/StatusPanel.cpp
- src/slic3r/GUI/StepMeshDialog.cpp
- src/slic3r/GUI/UnsavedChangesDialog.cpp
- src/slic3r/GUI/UpdateDialogs.cpp
- src/slic3r/GUI/WebUserLoginDialog.cpp
- src/slic3r/GUI/WipeTowerDialog.cpp
I assume its only visible on Windows OS. Linux and macOS already not uses icons
Half of dialogs already not uses titlebar icons. i tried to add them all but it started to annoy me after some use
Looks old fashion in my opinion. so send a PR to remove them. its ok to if not approved
i can delete these lines if requested instead commenting them
before
after - looks cleaner
> Remove usage of titlebar icons

- src/slic3r/GUI/NotificationManager.cpp
on %100 scaling
Tested on %150 scaling
BEFORE - Notification not aligns with gCode viewer and leaves extra spacing on bottom
AFTER
BEFORE - Notification not aligns with gCode viewer and leaves extra spacing on bottom
AFTER
> Fix notification position on scaling

- resources/profiles/Anker/machine/fdm_marlin_common.json
fix for time discrepancy, ;LAYER_COUNT was missing which made it impossible for the anker M5/M5C to have a correct predicted time.
added a command to the machine g-code to add the LAYER_COUNT into the gcode to make time estimated on ankermake/eufymake printers work again. see PR : #9457
does not  break any code, its a small update to the printer profile
no UI changes
manually added the ;LAYER_COUNT : 50 into a g-code and verified the result in the printer firmware and display.
> fix for printer time estimate on anker/eufy M5 M5C printers

- src/slic3r/GUI/GUI_ObjectLayers.cpp
- src/slic3r/GUI/Widgets/LabeledStaticBox.cpp
- src/slic3r/GUI/Widgets/LabeledStaticBox.hpp
• Removed 2 time usage of GetTextExtent because font metrics consistent and no difference between "y" and "Y" while getting its height
• Fixes wrong frame while it doesnt have a title
• Fixes wrong padding for macOS. thanks to @Noisyfox 
• Restores visibility https://github.com/SoftFever/OrcaSlicer/issues/9942
• Fixes flicker while Refresh()
• Aligns vertically "mm" text and add / delete buttons
> Fixes for LabeledStaticBox & Height Range UI

- resources/profiles/Ginger Additive/process/0.60mm Standard.json
- resources/profiles/Ginger Additive/process/1.50mm Standard.json
- resources/profiles/Ginger Additive/process/1.80mm Vasemode.json
- resources/profiles/Ginger Additive/process/2.50mm Standard.json
- resources/profiles/Ginger Additive/process/4.00mm Standard.json
This PR add the values for **skin_infill_line_width** and **skeleton_infill_line_width** inside the profiles because having nozzles larger than 0.4mm it cause a bug if not defined as reported in the Issue https://github.com/SoftFever/OrcaSlicer/issues/9993
N.A.
opened and sliced a project correctly with the default parameters
> added skin_infill_line_width and skeleton_infill_line_width to fix Ginger Additive profiles

- doc/developer-reference/How-to-build.md
This PR updates the [How to build](https://github.com/SoftFever/OrcaSlicer/wiki/How-to-build) wiki page with the following improvements:
- Introduced a table of contents at the top for easier navigation across sections (Windows, macOS, Linux, Ubuntu).
- Added an introductory paragraph to clarify the purpose of the page.
- Adds a pragraph on how to use the `data_dir` folder
Co-authored-by: @ianalexis
N.A.
- Verified that the new section renders correctly in Markdown.
- Validated that the `data_dir` functionality works as described (place data_dir next to OrcaSlicer.exe and it uses it as the configuration folder).
- Checked links and internal anchors in the Table of Contents.
> Updated the documentation on how to build OrcaSlicer

- src/libslic3r/Fill/FillRectilinear.cpp
- src/slic3r/GUI/ConfigManipulation.cpp
In this pull request, I add support for 2D lattice and 2D honeycomb infill patterns. Previously, I couldn't provide multiline support for them due to the issue of overlapping lines. To solve this, a function was added that removes overlapping lines, allowing the generation of multiline patterns without problems.
>   Multiline infill support  for 2D lattice and 2DHoneycomb patterns

- src/slic3r/GUI/Plater.cpp
- src/slic3r/GUI/SavePresetDialog.cpp
- src/slic3r/GUI/SavePresetDialog.hpp
- src/slic3r/GUI/Widgets/Button.cpp
- src/slic3r/GUI/Widgets/LabeledStaticBox.cpp
- src/slic3r/GUI/Widgets/RadioGroup.cpp
- src/slic3r/GUI/Widgets/RadioGroup.hpp
Tested on windows 11
@Noisyfox this solution much simpler, i have tried similar method but coulnt get it working properly before
This one is alternative PR for https://github.com/SoftFever/OrcaSlicer/pull/9930 will close that one depends on comments
Differences;
• Labels uses Button instead wxStaticText or wxBannerWindow
• No overrides for paint or focus events
text below copied from other PR
• Added Disable() / Enable() functionality. Its used on save preset dialog
• Adding disabling function lead to new problem. disabling wxPanel caused unwanted effect on wxStaticText so i removed usage of it and switched to Button class
• Added ability to SetTooltip() per each radio control
• Removed some of definations from loop to improve draw speed on Refresh()
• Limited focus rectangle with text …
> Improvements / Fixes for RadioGroup and apply to more windows II

- src/libslic3r/Fill/Fill.cpp
- src/slic3r/GUI/ConfigManipulation.cpp
Based in #10097 from @KaarelP2rtel to allow edition in "Top surface" pattern and density when using vase mode.
Created a new PR because i needed to test this different implementation and enabling ironing when using "top surface".
> Enable ironing and shell options for spiral vase mode

- src/expat/xmlparse.c
Fixes [CVE-2024-45492](https://nvd.nist.gov/vuln/detail/cve-2024-45492) integer overflow vulnerability in bundled libexpat library's nextScaffoldPart function. Adds overflow check to prevent buffer overflow when parsing maliciously crafted XML data on 32-bit platforms.
- Added integer overflow check in nextScaffoldPart function
- Applied upstream patch from libexpat commit [9bf0f2c](https://github.com/libexpat/libexpat/pull/892/commits/9bf0f2c16ee86f644dd1432507edff94c08dc232)
- Prevents potential RCE through XML parsing
**Security Impact:**
- Fixes HIGH severity vulnerability (CVSS 7.3)
- Prevents buffer overflow on 32-bit systems
- No breaking changes to existing functionality
> Security Fix : CVE-2024-45492 in libexpat library.

- src/slic3r/GUI/GLCanvas3D.cpp
The issue was introduced in #8776.
See below for issue details:
https://github.com/SoftFever/OrcaSlicer/pull/9979#issuecomment-3065575889
https://github.com/SoftFever/OrcaSlicer/pull/9979#issuecomment-3084251484
> Fix issue that clicking paint gizmos while mouse is hovering above the model, view panning doesn't work

- resources/profiles/Anycubic/machine/Anycubic Kobra 2 0.4 nozzle.json
Fixed error:
Relative extruder addressing requires resetting the extruder position at each layer to prevent loss of floating point accuracy.
When you load the system preset for the Anycubic Kobra 2 you can't slice, and it just gives an error
I changed it in the slicer and exported it, and the line was the same as the one in this pull request
>  Fixed error in Anycubic Kobra 2 0.4 nozzle.json

- src/libslic3r/GCode.cpp
- src/libslic3r/PlaceholderParser.cpp
- src/libslic3r/PlaceholderParser.hpp
- src/libslic3r/PrintBase.cpp
This PR introduces a new placeholder, `{user}`, available for use in G-code and output filenames. This placeholder is replaced with the username of the current user logged into the computer.
The primary goal of this feature is to improve traceability in multi-user environments. In settings where a single 3D printer is shared among multiple people (e.g., in a makerspace, school, or office), it can be difficult to identify who generated a specific print file. By allowing the username to be embedded in the G-code or filename, this feature makes it easy to determine the author of each print job.
There are no breaking changes with this addition.
I have verified that the `{user}` placeholder correctly retrieves the username on the following operating systems:
> add user name placeholder

- src/libslic3r/Feature/FuzzySkin/FuzzySkin.cpp
- src/libslic3r/PerimeterGenerator.hpp
- src/libslic3r/Preset.cpp
- src/libslic3r/PrintConfig.cpp
- src/libslic3r/PrintConfig.hpp
- src/libslic3r/PrintObject.cpp
- src/slic3r/GUI/ConfigManipulation.cpp
- src/slic3r/GUI/Tab.cpp
This extension allows you to add new features to the fuzzy skin generator.
I must say right away that I am newby to GitHub and this is my first OrcaSlicer mod, so I will be happy to listen to comments, suggestions or any criticism for me. It would be nice if you notice inaccuracies in the code, spelling or stylistic errors and tell me to fix them. Or maybe there will be some additions.
Here is a fuzzy skin generator add-on to expand its capabilities. Now the skin can be formed not only by shifting the nozzle from side to side, but also by forming an amount of extruded plastic. This code functions only when the Arachne engine is on, and it operates effectively with a skin pattern thickness of roughly ±75% of the perimeter thickness.
I tried to make the code as light as possible and not …
> Feature: Fuzzy Skin Extrusion Mode

- src/libslic3r/GCode.cpp
This pull request partially addresses the issue described in #5217.
Problem:
At the end of a perimeter, after retraction, the following travel move does not respect the restriction that prevents crossing other perimeters. 
Notes:
Works best when using Arachne perimeter generator.
Spiral Z-hop should be avoided for better results.
this PR may close #5217 
this PR may close #9770
> Bug fix: avoid crossing perimeters

- src/slic3r/GUI/CreatePresetsDialog.cpp
Export Preset Bundle->Printer config bundle will not consider the currently selected printer as a valid option. Fixes #10327 
Removed this check `(preset_bundle.printers.select_preset_by_name(preset_name,` false))`
Tried out the user config in the bug report. If you create and select another printer, you can get Bambu Lab P1S 0.4 nozzle to show up.
> Fix: export printer config skipping currently selected preset

- .github/workflows/validate-documentation.yml
It is an attempt to convert some scripts I had in PowerShell to GitHub Actions to avoid errors I encountered while updating the wiki.
> [!IMPORTANT]
> In current docs are a lot of errors. They are fixed in #10369 
This PR introduces a GitHub Actions workflow that automatically validates documentation integrity in OrcaSlicer, ensuring all links, references, and images are properly formatted and functional.
- **Pull Requests**: Changes to `src/slic3r/GUI/Tab.cpp` or `doc/**/*.md`
- **Manual**: Via `workflow_dispatch`
- Validates internal markdown links (`[text](#fragment)`) point to existing anchors
- Ensures cross-document links (`[text](file#fragment)`) reference valid files and anchors
- Checks `Tab.cpp` documentation references in `optgroup->append_single_option_line()` calls
- Enforces …
> Wiki Validation Workflow Action

- src/slic3r/GUI/Plater.cpp
Previously, the PA was deactivated, but in reality, a value of 0 is desired. When deactivating it, if it has a value due to FW, that value is used. Now it is forced to 0.
Fixes https://discord.com/channels/1137181739773603922/1407842411572625569
> Fix IS & JD test

- .github/workflows/build_all.yml
- .github/workflows/build_orca.yml
Uses "nightly" instead of the current version when uploading nightly releases. This is helpful for package managers such as homebrew to easily pick up the changes when the version bumps.
See original issue I created: #10442 
N/A
I don't have access to CI but the changes are pretty simple. There may be other changes that need to be made for updating the website. If so, please let me know if I can help.
> feat: use "nightly" instead of version code for nightly builds

- .github/workflows/build_deps.yml
- .github/workflows/build_orca.yml
This PR addresses a build issue in GitHub Actions where STL repair via Netfabb is skipped due to missing Windows SDK detection.
Although local builds work correctly, the GitHub CI output shows:
WIN10SDK_PATH is invalid: C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ -- PROJECT_SOURCE_DIR: D:/a/OrcaSlicer/OrcaSlicer C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\/winrt/windows.graphics.printing3d.h was not found STL fixing by the Netfabb service will not be compiled Building without Win10 Netfabb STL fixing service support
fix #10461
fix #10463
>  Fix  netfab  model repair service in github compilation

- .github/workflows/build_orca.yml
Fixes the path of OrcaSlicer_profile_validator during the orca_custom_preset_tests step
<https://github.com/SoftFever/OrcaSlicer/actions/runs/17189194833/job/48762463678>
<https://github.com/SoftFever/OrcaSlicer/actions/runs/17190909397?pr=10510>
<https://github.com/NanashiTheNameless/OrcaSlicer/actions/runs/17190932412>
> Correct OrcaSlicer_profile_validator path

- src/slic3r/GUI/StatusPanel.cpp
Button icon size already scaling in class so no need to use scaling on argument
**%100 scaling**
**Before %200 scaling**
**After %200 scaling**
> Fix scaling on bed and extruder icons in BBL > Device tab

- resources/profiles/Anycubic/machine/Anycubic Kobra 2 Neo 0.4 nozzle.json
This PR addresses several issues with the Anycubic Kobra 2 Neo printer profile that were causing print failures and inconsistent extrusion behavior. Mainly, the machine's start and end G-code instructions to optimize performance and ensure consistency in operation. These changes improve the overall workflow associated with initialization and conclusion of machine tasks.
- **Updated G-code flavor**: Changed from `marlin` to `marlin2` for better firmware compatibility
- **Fixed extrusion mode**: Enabled relative E distances (`use_relative_e_distances: 1`) to prevent cumulative positioning errors
- **Enhanced bed leveling**: Added `M420 S1` command to start G-code to properly enable the printer's bed leveling mesh
- **Improved layer transitions**: Added `G92 E0` before layer changes to reset …
> Fix Anycubic Kobra 2 Neo Machine Profile

- resources/profiles/Phrozen/machine/Phrozen Arco 0.4 nozzle.json
Changes M109 S200 in machine_start_gcode to allow printer to properly utilize filament profile temperatures. With original code, the temperature will be stuck at 200c for duration of print despite filament profile having different first layer and other layer temperatures settings.
Fixes https://github.com/SoftFever/OrcaSlicer/issues/10555
> [Profiles] Optimize Phrozen Arco 0.4 nozzle.json start up gcode

- src/libslic3r/Fill/Fill3DHoneycomb.hpp
Bridge flow isn't necessary; the pattern is fully supported on the lines that matter for structural stability.
I noticed in a recent comment for the PrusaSlicer version of this that I had forgotten to disable bridge flow for this pattern; that is now fixed.
> [OPTIMIZATION] Update Fill3DHoneycomb.hpp - remove bridge flow

- localization/i18n/OrcaSlicer.pot
- localization/i18n/ca/OrcaSlicer_ca.po
- localization/i18n/cs/OrcaSlicer_cs.po
- localization/i18n/de/OrcaSlicer_de.po
- localization/i18n/en/OrcaSlicer_en.po
- localization/i18n/es/OrcaSlicer_es.po
- localization/i18n/fr/OrcaSlicer_fr.po
- localization/i18n/hu/OrcaSlicer_hu.po
- localization/i18n/it/OrcaSlicer_it.po
- localization/i18n/ja/OrcaSlicer_ja.po
- localization/i18n/ko/OrcaSlicer_ko.po
- localization/i18n/lt/OrcaSlicer_lt.po
- localization/i18n/nl/OrcaSlicer_nl.po
- localization/i18n/pl/OrcaSlicer_pl.po
- localization/i18n/pt_BR/OrcaSlicer_pt_BR.po
- localization/i18n/ru/OrcaSlicer_ru.po
- localization/i18n/sv/OrcaSlicer_sv.po
- localization/i18n/tr/OrcaSlicer_tr.po
- localization/i18n/uk/OrcaSlicer_uk.po
- localization/i18n/zh_CN/OrcaSlicer_zh_CN.po
- localization/i18n/zh_TW/OrcaSlicer_zh_TW.po
- src/libslic3r/PrintConfig.cpp
Fixes typo on
"Sparse infill **rotatation** template" to "Sparse infill **rotation** template"
"Solid infill **rotatation** template" to "Solid infill **rotation** template"
> [DOC] Fix typo "rotatation" 

- src/libslic3r/GCode.cpp
As you can see, it's checking the local variable
`custom_gcode_placeholders` which comes from
`custom_gcode_specific_placeholders()` which is:
```
const std::map<t_custom_gcode_key, t_config_option_keys>& custom_gcode_specific_placeholders()
{
return s_CustomGcodeSpecificPlaceholders;
}
```
not s_CustomGcodeSpecificOptions
> Fix variable name comment and message

- resources/profiles/Anycubic/machine/Anycubic Kobra 2 Neo 0.4 nozzle.json
This PR updates the end g-code in Anycubic Kobra 2 Neo printer profile. The machine's end G-code instructions to home X and Y only instead of Z to prevent crashing into final prints, and reduce the amount of retraction to avoid melting the stock PTFE. These changes improves the end of print step.
- Reduced total amount of retraction as stock PTFE liner may not be able to take the heat. (7mm to 3mm)
- Added X Y to final G28 to avoid crashing into prints.
Tested by printing https://www.printables.com/model/594620-cute-low-poly-cat-no-supports. Originally, experienced a near miss where print head could have crashed into print.
These changes ensure end step on Anycubic Kobra 2 Neo printers does not crash into print and reduce amount of molten filament going into PTFE.
> Update Anycubic Kobra 2 Neo machine profile fine tune end gcode

- .github/workflows/build_all.yml
- .github/workflows/build_check_cache.yml
- .github/workflows/build_deps.yml
When an external dependency breaks a build, ensures a record exists of it happening.
Half of #10404
> Add a once-daily Build All which skips caches

- src/slic3r/Utils/RetinaHelperImpl.mm
This PR addresses an issue where colors in the 3D view are over-saturated on displays with a wide color gamut and also fixes flickering colors after the window is dragged between displays with different color profiles. 
Note: this change does not affect Windows or Linux.
Left is with this change, right is original
If you do not have a display that supports a wide color gamut or your system's color management is not properly configured, you may find it difficult to see the difference in this screenshot. (Try viewing it on a recent smartphone)
Tested on macOS
> Set NSWindow color space to sRGB on macOS
